begin;

create table if not exists public.dkd_urgent_courier_push_audit (
  dkd_audit_id bigint generated by default as identity primary key,
  dkd_dedupe_key text not null,
  dkd_event_key text not null,
  dkd_order_id uuid not null,
  dkd_message_id uuid null,
  dkd_target_user_id uuid null,
  expo_push_token text not null,
  dkd_title text not null,
  dkd_body text not null,
  dkd_payload jsonb not null default '{}'::jsonb,
  dkd_send_status text not null default 'pending',
  dkd_send_error text null,
  dkd_created_at timestamptz not null default now(),
  dkd_sent_at timestamptz null
);

create unique index if not exists dkd_urgent_courier_push_audit_dedupe_unique
  on public.dkd_urgent_courier_push_audit(dkd_dedupe_key);

create index if not exists dkd_urgent_courier_push_audit_order_event_idx
  on public.dkd_urgent_courier_push_audit(dkd_order_id, dkd_event_key, dkd_created_at desc);

create index if not exists dkd_urgent_courier_push_audit_status_idx
  on public.dkd_urgent_courier_push_audit(dkd_send_status, dkd_created_at desc);

drop function if exists public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid);

create or replace function public.dkd_urgent_courier_push_targets_dkd(
  dkd_param_order_id uuid,
  dkd_param_event_key text,
  dkd_param_message_id uuid default null
)
returns table(
  dkd_target_user_id uuid,
  expo_push_token text,
  dkd_title text,
  dkd_body text,
  dkd_payload jsonb,
  dkd_dedupe_key text
)
language sql
security definer
set search_path = public
as $dkd_push_targets$
  with dkd_order_scope as (
    select
      dkd_order_row.*,
      coalesce(nullif(trim(dkd_order_row.dkd_customer_full_name), ''), 'Müşteri') as dkd_customer_name_value,
      coalesce(nullif(trim(dkd_courier_profile_row.nickname), ''), 'Kurye') as dkd_courier_name_value,
      coalesce(dkd_order_row.dkd_courier_fee_tl, 0) as dkd_courier_fee_value,
      coalesce(dkd_order_row.dkd_product_total_tl, 0) as dkd_product_total_value
    from public.dkd_urgent_courier_orders dkd_order_row
    left join public.dkd_profiles dkd_courier_profile_row
      on dkd_courier_profile_row.user_id = dkd_order_row.dkd_courier_user_id
    where dkd_order_row.dkd_order_id = dkd_param_order_id
  ),
  dkd_message_scope as (
    select
      dkd_message_row.dkd_message_id,
      dkd_message_row.dkd_sender_user_id,
      dkd_message_row.dkd_sender_role_key,
      dkd_message_row.dkd_message_text
    from public.dkd_urgent_courier_messages dkd_message_row
    where dkd_message_row.dkd_message_id = dkd_param_message_id
  ),
  dkd_customer_message_target_scope as (
    select
      dkd_order_scope.dkd_courier_user_id as dkd_target_user_id,
      'dkd_courier'::text as dkd_target_role_key
    from dkd_order_scope
    join dkd_message_scope on true
    where dkd_param_event_key = 'dkd_urgent_message_sent'
      and dkd_message_scope.dkd_sender_role_key = 'dkd_customer'
      and dkd_order_scope.dkd_courier_user_id is not null
  ),
  dkd_courier_message_target_scope as (
    select
      dkd_order_scope.dkd_customer_user_id as dkd_target_user_id,
      'dkd_customer'::text as dkd_target_role_key
    from dkd_order_scope
    join dkd_message_scope on true
    where dkd_param_event_key = 'dkd_urgent_message_sent'
      and dkd_message_scope.dkd_sender_role_key = 'dkd_courier'
      and dkd_order_scope.dkd_customer_user_id is not null
  ),
  dkd_direct_target_scope as (
    select dkd_order_scope.dkd_customer_user_id as dkd_target_user_id, 'dkd_customer'::text as dkd_target_role_key
    from dkd_order_scope
    where dkd_param_event_key in (
      'dkd_urgent_courier_accepted',
      'dkd_urgent_product_total_sent',
      'dkd_urgent_invoice_uploaded',
      'dkd_urgent_items_picked_up',
      'dkd_urgent_delivery_completed'
    )
    union all
    select dkd_order_scope.dkd_courier_user_id as dkd_target_user_id, 'dkd_courier'::text as dkd_target_role_key
    from dkd_order_scope
    where dkd_param_event_key in (
      'dkd_urgent_order_cancelled',
      'dkd_urgent_fee_approved',
      'dkd_urgent_product_total_approved'
    )
      and dkd_order_scope.dkd_courier_user_id is not null
    union all
    select dkd_order_scope.dkd_customer_user_id as dkd_target_user_id, 'dkd_customer'::text as dkd_target_role_key
    from dkd_order_scope
    where dkd_param_event_key in ('dkd_urgent_chat_opened', 'dkd_urgent_auto_message')
    union all
    select dkd_order_scope.dkd_courier_user_id as dkd_target_user_id, 'dkd_courier'::text as dkd_target_role_key
    from dkd_order_scope
    where dkd_param_event_key in ('dkd_urgent_chat_opened', 'dkd_urgent_auto_message')
      and dkd_order_scope.dkd_courier_user_id is not null
  ),
  dkd_pool_target_scope as (
    select distinct
      dkd_token_row.user_id as dkd_target_user_id,
      'dkd_courier_pool'::text as dkd_target_role_key
    from dkd_order_scope
    join public.dkd_push_tokens dkd_token_row
      on dkd_param_event_key = 'dkd_urgent_order_created'
     and dkd_token_row.is_active = true
     and nullif(trim(coalesce(dkd_token_row.expo_push_token, '')), '') is not null
     and dkd_token_row.user_id <> dkd_order_scope.dkd_customer_user_id
     and public.dkd_urgent_courier_license_active_dkd(dkd_token_row.user_id) is true
  ),
  dkd_all_target_scope as (
    select * from dkd_direct_target_scope
    union all
    select * from dkd_customer_message_target_scope
    union all
    select * from dkd_courier_message_target_scope
    union all
    select * from dkd_pool_target_scope
  ),
  dkd_token_scope as (
    select
      dkd_all_target_scope.dkd_target_user_id,
      dkd_all_target_scope.dkd_target_role_key,
      dkd_token_row.expo_push_token,
      row_number() over (
        partition by dkd_token_row.expo_push_token
        order by dkd_token_row.updated_at desc nulls last, dkd_token_row.id desc
      ) as dkd_token_rank
    from dkd_all_target_scope
    join public.dkd_push_tokens dkd_token_row
      on dkd_token_row.user_id = dkd_all_target_scope.dkd_target_user_id
     and dkd_token_row.is_active = true
     and nullif(trim(coalesce(dkd_token_row.expo_push_token, '')), '') is not null
    where dkd_all_target_scope.dkd_target_user_id is not null
  ),
  dkd_message_text_scope as (
    select
      coalesce(nullif(trim(dkd_message_scope.dkd_message_text), ''), 'Yeni mesajın var.') as dkd_message_text_value,
      coalesce(dkd_message_scope.dkd_sender_role_key, '') as dkd_sender_role_key_value
    from dkd_message_scope
    union all
    select 'Yeni mesajın var.'::text, ''::text
    where not exists (select 1 from dkd_message_scope)
  )
  select
    dkd_token_scope.dkd_target_user_id,
    dkd_token_scope.expo_push_token,
    case
      when dkd_param_event_key = 'dkd_urgent_order_created' then 'Yeni Acil Kurye Siparişi'
      when dkd_param_event_key = 'dkd_urgent_courier_accepted' then 'Kurye Görevi Kabul Etti'
      when dkd_param_event_key = 'dkd_urgent_order_cancelled' then 'Acil Kurye Siparişi İptal Edildi'
      when dkd_param_event_key = 'dkd_urgent_fee_approved' then 'Taşıma Ücreti Onaylandı'
      when dkd_param_event_key = 'dkd_urgent_chat_opened' then 'Acil Kurye Sohbeti Açıldı'
      when dkd_param_event_key = 'dkd_urgent_product_total_sent' then 'Mağaza Ürün Fiyatları Girildi'
      when dkd_param_event_key = 'dkd_urgent_product_total_approved' then 'Ürün Toplamı Onaylandı'
      when dkd_param_event_key = 'dkd_urgent_invoice_uploaded' then 'Fatura Yüklendi'
      when dkd_param_event_key = 'dkd_urgent_items_picked_up' then 'Kurye Ürünleri Aldı'
      when dkd_param_event_key = 'dkd_urgent_delivery_completed' then 'Sipariş Teslim Edildi'
      when dkd_param_event_key = 'dkd_urgent_message_sent' and dkd_message_text_scope.dkd_sender_role_key_value = 'dkd_customer' then 'Müşteriden Yeni Mesaj'
      when dkd_param_event_key = 'dkd_urgent_message_sent' and dkd_message_text_scope.dkd_sender_role_key_value = 'dkd_courier' then 'Kuryeden Yeni Mesaj'
      when dkd_param_event_key = 'dkd_urgent_auto_message' then 'Acil Kurye Canlı Güncelleme'
      else 'Acil Kurye'
    end as dkd_title,
    case
      when dkd_param_event_key = 'dkd_urgent_order_created' then concat(dkd_order_scope.dkd_customer_name_value, ' yeni Acil Kurye siparişi oluşturdu. Kurye havuzunu kontrol et.')
      when dkd_param_event_key = 'dkd_urgent_courier_accepted' then concat(dkd_order_scope.dkd_courier_name_value, ' görevi kabul etti ve ', round(dkd_order_scope.dkd_courier_fee_value, 2)::text, ' TL taşıma ücreti teklif etti. Onay bekliyor.')
      when dkd_param_event_key = 'dkd_urgent_order_cancelled' then concat(dkd_order_scope.dkd_customer_name_value, ' Acil Kurye siparişini iptal etti. Bu görev kapatıldı.')
      when dkd_param_event_key = 'dkd_urgent_fee_approved' then concat('Müşteri ', round(dkd_order_scope.dkd_courier_fee_value, 2)::text, ' TL taşıma ücretini onayladı. Cüzdan ödemesi alındı; alışverişe başlayabilirsin.')
      when dkd_param_event_key = 'dkd_urgent_chat_opened' then 'Acil Kurye canlı sohbeti açıldı. Müşteri ve kurye artık bu sipariş üzerinden mesajlaşabilir.'
      when dkd_param_event_key = 'dkd_urgent_product_total_sent' then concat('Kurye mağaza bazlı ürün fiyatlarını girdi. Genel ürün toplamı: ', round(dkd_order_scope.dkd_product_total_value, 2)::text, ' TL. Onay bekliyor.')
      when dkd_param_event_key = 'dkd_urgent_product_total_approved' then concat('Müşteri ', round(dkd_order_scope.dkd_product_total_value, 2)::text, ' TL ürün toplamını onayladı. Ürünleri satın alabilirsin.')
      when dkd_param_event_key = 'dkd_urgent_invoice_uploaded' then 'Kurye faturayı yükledi. Fatura görselini sipariş detayından kontrol edebilirsin.'
      when dkd_param_event_key = 'dkd_urgent_items_picked_up' then 'Kurye ürünleri teslim aldı ve teslimat adresine doğru yola çıktı.'
      when dkd_param_event_key = 'dkd_urgent_delivery_completed' then 'Kurye siparişi teslim etti. Acil Kurye siparişin tamamlandı.'
      when dkd_param_event_key = 'dkd_urgent_message_sent' and dkd_message_text_scope.dkd_sender_role_key_value = 'dkd_customer' then concat('Müşteri mesaj gönderdi: ', left(dkd_message_text_scope.dkd_message_text_value, 120))
      when dkd_param_event_key = 'dkd_urgent_message_sent' and dkd_message_text_scope.dkd_sender_role_key_value = 'dkd_courier' then concat('Kurye mesaj gönderdi: ', left(dkd_message_text_scope.dkd_message_text_value, 120))
      when dkd_param_event_key = 'dkd_urgent_auto_message' then left(dkd_message_text_scope.dkd_message_text_value, 140)
      else 'Acil Kurye akışında yeni güncelleme var.'
    end as dkd_body,
    jsonb_build_object(
      'route', 'courier',
      'targetScreen', 'courier',
      'dkd_event_key', dkd_param_event_key,
      'dkd_urgent_courier_order_id', dkd_order_scope.dkd_order_id,
      'dkd_message_id', dkd_param_message_id,
      'dkd_push_segment', 'urgent_courier'
    ) as dkd_payload,
    concat(
      dkd_param_event_key,
      ':',
      dkd_order_scope.dkd_order_id::text,
      ':',
      coalesce(dkd_param_message_id::text, 'none'),
      ':',
      dkd_token_scope.dkd_target_user_id::text,
      ':',
      md5(dkd_token_scope.expo_push_token)
    ) as dkd_dedupe_key
  from dkd_token_scope
  cross join dkd_order_scope
  cross join dkd_message_text_scope
  where dkd_token_scope.dkd_token_rank = 1;
$dkd_push_targets$;

revoke all on function public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid) from public;
grant execute on function public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid) to authenticated, service_role;
grant select, insert, update on public.dkd_urgent_courier_push_audit to service_role;

commit;
