begin;

create table if not exists public.dkd_cargo_shipments (
  id bigint generated by default as identity primary key,
  customer_user_id uuid not null references auth.users(id) on delete cascade,
  customer_first_name text not null default '',
  customer_last_name text not null default '',
  customer_national_id text not null default '',
  pickup_address_text text not null default '',
  package_content_text text not null default '',
  package_image_url text,
  package_weight_kg numeric(10,2) not null default 0,
  status text not null default 'open',
  courier_job_id bigint,
  assigned_courier_user_id uuid references auth.users(id) on delete set null,
  assigned_courier_plate_no text,
  assigned_courier_vehicle_type text,
  courier_eta_min integer,
  pickup_lat numeric,
  pickup_lng numeric,
  accepted_at timestamptz,
  picked_up_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dkd_cargo_shipments_customer_idx
  on public.dkd_cargo_shipments(customer_user_id, created_at desc);
create index if not exists dkd_cargo_shipments_status_idx
  on public.dkd_cargo_shipments(status, created_at desc);
create index if not exists dkd_cargo_shipments_courier_idx
  on public.dkd_cargo_shipments(assigned_courier_user_id, created_at desc);

create table if not exists public.dkd_courier_live_locations (
  courier_user_id uuid primary key references auth.users(id) on delete cascade,
  lat numeric,
  lng numeric,
  eta_min integer,
  plate_no text,
  vehicle_type text,
  updated_at timestamptz not null default now()
);

alter table if exists public.dkd_courier_jobs
  add column if not exists pickup_status text not null default 'pending',
  add column if not exists picked_up_at timestamptz,
  add column if not exists merchant_name text,
  add column if not exists product_title text,
  add column if not exists delivery_note text,
  add column if not exists delivery_address_text text,
  add column if not exists order_id bigint,
  add column if not exists business_id uuid,
  add column if not exists product_id bigint,
  add column if not exists customer_user_id uuid,
  add column if not exists pickup_lat numeric,
  add column if not exists pickup_lng numeric,
  add column if not exists dropoff_lat numeric,
  add column if not exists dropoff_lng numeric,
  add column if not exists fee_tl numeric(12,2) not null default 0,
  add column if not exists cargo_shipment_id bigint,
  add column if not exists cargo_meta jsonb not null default '{}'::jsonb;

create index if not exists dkd_courier_jobs_cargo_shipment_idx
  on public.dkd_courier_jobs(cargo_shipment_id);

create index if not exists dkd_courier_live_locations_updated_idx
  on public.dkd_courier_live_locations(updated_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'dkd_courier_jobs_cargo_shipment_fk'
  ) then
    alter table public.dkd_courier_jobs
      add constraint dkd_courier_jobs_cargo_shipment_fk
      foreign key (cargo_shipment_id)
      references public.dkd_cargo_shipments(id)
      on delete set null;
  end if;
exception when undefined_table then
  null;
end $$;

do $$
begin
  if exists (
    select 1
    from pg_proc
    where proname = 'dkd_touch_updated_at'
      and pg_function_is_visible(oid)
  ) then
    execute 'drop trigger if exists dkd_cargo_shipments_touch_updated_at on public.dkd_cargo_shipments';
    execute 'create trigger dkd_cargo_shipments_touch_updated_at before update on public.dkd_cargo_shipments for each row execute function public.dkd_touch_updated_at()';
    execute 'drop trigger if exists dkd_courier_live_locations_touch_updated_at on public.dkd_courier_live_locations';
    execute 'create trigger dkd_courier_live_locations_touch_updated_at before update on public.dkd_courier_live_locations for each row execute function public.dkd_touch_updated_at()';
  end if;
exception when undefined_table then
  null;
end $$;

alter table if exists public.dkd_cargo_shipments enable row level security;
alter table if exists public.dkd_courier_live_locations enable row level security;

grant select, insert, update on public.dkd_cargo_shipments to authenticated;
grant select, insert, update on public.dkd_courier_live_locations to authenticated;

drop policy if exists dkd_cargo_shipments_select_scope on public.dkd_cargo_shipments;
create policy dkd_cargo_shipments_select_scope
on public.dkd_cargo_shipments
for select
to authenticated
using (
  auth.uid() = customer_user_id
  or auth.uid() = assigned_courier_user_id
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_cargo_shipments_insert_own on public.dkd_cargo_shipments;
create policy dkd_cargo_shipments_insert_own
on public.dkd_cargo_shipments
for insert
to authenticated
with check (
  auth.uid() = customer_user_id
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_cargo_shipments_update_scope on public.dkd_cargo_shipments;
create policy dkd_cargo_shipments_update_scope
on public.dkd_cargo_shipments
for update
to authenticated
using (
  auth.uid() = customer_user_id
  or auth.uid() = assigned_courier_user_id
  or coalesce(public.dkd_is_admin(), false)
)
with check (
  auth.uid() = customer_user_id
  or auth.uid() = assigned_courier_user_id
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_courier_live_locations_select_scope on public.dkd_courier_live_locations;
create policy dkd_courier_live_locations_select_scope
on public.dkd_courier_live_locations
for select
to authenticated
using (
  auth.uid() = courier_user_id
  or coalesce(public.dkd_is_admin(), false)
  or exists (
    select 1
    from public.dkd_cargo_shipments dkd_scope_row
    where dkd_scope_row.assigned_courier_user_id = dkd_courier_live_locations.courier_user_id
      and dkd_scope_row.customer_user_id = auth.uid()
      and dkd_scope_row.status in ('accepted', 'picked_up', 'completed')
  )
);

drop policy if exists dkd_courier_live_locations_insert_own on public.dkd_courier_live_locations;
create policy dkd_courier_live_locations_insert_own
on public.dkd_courier_live_locations
for insert
to authenticated
with check (
  auth.uid() = courier_user_id
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_courier_live_locations_update_own on public.dkd_courier_live_locations;
create policy dkd_courier_live_locations_update_own
on public.dkd_courier_live_locations
for update
to authenticated
using (
  auth.uid() = courier_user_id
  or coalesce(public.dkd_is_admin(), false)
)
with check (
  auth.uid() = courier_user_id
  or coalesce(public.dkd_is_admin(), false)
);

do $$
begin
  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  select 'lootonia-cargo-package-art', 'lootonia-cargo-package-art', true, 6291456, array['image/jpeg','image/png','image/webp','image/heic']
  where not exists (select 1 from storage.buckets where id = 'lootonia-cargo-package-art');
exception when undefined_table then
  null;
end $$;

drop policy if exists dkd_lootonia_cargo_package_art_read on storage.objects;
create policy dkd_lootonia_cargo_package_art_read
on storage.objects
for select
to authenticated
using (bucket_id = 'lootonia-cargo-package-art');

drop policy if exists dkd_lootonia_cargo_package_art_insert on storage.objects;
create policy dkd_lootonia_cargo_package_art_insert
on storage.objects
for insert
to authenticated
with check (bucket_id = 'lootonia-cargo-package-art');

drop policy if exists dkd_lootonia_cargo_package_art_update on storage.objects;
create policy dkd_lootonia_cargo_package_art_update
on storage.objects
for update
to authenticated
using (bucket_id = 'lootonia-cargo-package-art')
with check (bucket_id = 'lootonia-cargo-package-art');

drop function if exists public.dkd_cargo_shipment_create(text, text, text, text, text, text, numeric, numeric, numeric);
create function public.dkd_cargo_shipment_create(
  dkd_param_customer_first_name text default null,
  dkd_param_customer_last_name text default null,
  dkd_param_customer_national_id text default null,
  dkd_param_pickup_address_text text default null,
  dkd_param_package_content_text text default null,
  dkd_param_package_image_url text default null,
  dkd_param_package_weight_kg numeric default 0,
  dkd_param_pickup_lat numeric default null,
  dkd_param_pickup_lng numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_weight_kg numeric(10,2) := greatest(coalesce(dkd_param_package_weight_kg, 0.1), 0.1);
  dkd_reward_score integer := greatest(14, ceil(greatest(coalesce(dkd_param_package_weight_kg, 0.1), 0.1) * 8)::integer);
  dkd_fee_tl numeric(12,2) := greatest(35, ceil(25 + (greatest(coalesce(dkd_param_package_weight_kg, 0.1), 0.1) * 12))::integer)::numeric(12,2);
  dkd_eta_min integer := greatest(8, least(60, ceil(10 + (greatest(coalesce(dkd_param_package_weight_kg, 0.1), 0.1) * 4))::integer));
  dkd_shipment_id bigint;
  dkd_job_id bigint;
  dkd_first_name_value text := coalesce(nullif(trim(coalesce(dkd_param_customer_first_name, '')), ''), 'Gönderici');
  dkd_last_name_value text := coalesce(nullif(trim(coalesce(dkd_param_customer_last_name, '')), ''), 'Müşteri');
  dkd_full_name_value text;
begin
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  if length(regexp_replace(coalesce(dkd_param_customer_national_id, ''), '\\D', '', 'g')) <> 11 then
    raise exception 'national_id_required';
  end if;

  if coalesce(length(trim(coalesce(dkd_param_pickup_address_text, ''))), 0) < 10 then
    raise exception 'pickup_address_required';
  end if;

  if coalesce(length(trim(coalesce(dkd_param_package_content_text, ''))), 0) < 2 then
    raise exception 'package_content_required';
  end if;

  dkd_full_name_value := trim(concat(dkd_first_name_value, ' ', dkd_last_name_value));

  insert into public.dkd_cargo_shipments (
    customer_user_id,
    customer_first_name,
    customer_last_name,
    customer_national_id,
    pickup_address_text,
    package_content_text,
    package_image_url,
    package_weight_kg,
    status,
    pickup_lat,
    pickup_lng
  ) values (
    dkd_user_id,
    dkd_first_name_value,
    dkd_last_name_value,
    regexp_replace(coalesce(dkd_param_customer_national_id, ''), '\\D', '', 'g'),
    trim(coalesce(dkd_param_pickup_address_text, '')),
    trim(coalesce(dkd_param_package_content_text, '')),
    nullif(trim(coalesce(dkd_param_package_image_url, '')), ''),
    dkd_weight_kg,
    'open',
    dkd_param_pickup_lat,
    dkd_param_pickup_lng
  )
  returning id into dkd_shipment_id;

  insert into public.dkd_courier_jobs (
    title,
    pickup,
    dropoff,
    reward_score,
    distance_km,
    eta_min,
    job_type,
    is_active,
    status,
    pickup_status,
    merchant_name,
    product_title,
    delivery_note,
    delivery_address_text,
    customer_user_id,
    pickup_lat,
    pickup_lng,
    fee_tl,
    cargo_shipment_id,
    cargo_meta
  ) values (
    concat('Kargo • ', dkd_full_name_value),
    trim(coalesce(dkd_param_pickup_address_text, '')),
    'Kargo Operasyon Merkezi',
    dkd_reward_score,
    1.2,
    dkd_eta_min,
    'cargo',
    true,
    'open',
    'pending',
    'Kargo Operasyon Merkezi',
    trim(coalesce(dkd_param_package_content_text, '')),
    concat('Gönderici • ', dkd_full_name_value),
    trim(coalesce(dkd_param_pickup_address_text, '')),
    dkd_user_id,
    dkd_param_pickup_lat,
    dkd_param_pickup_lng,
    dkd_fee_tl,
    dkd_shipment_id,
    jsonb_build_object(
      'customer_first_name', dkd_first_name_value,
      'customer_last_name', dkd_last_name_value,
      'package_weight_kg', dkd_weight_kg,
      'package_image_url', nullif(trim(coalesce(dkd_param_package_image_url, '')), '')
    )
  )
  returning id into dkd_job_id;

  update public.dkd_cargo_shipments
  set courier_job_id = dkd_job_id,
      updated_at = now()
  where id = dkd_shipment_id;

  return jsonb_build_object(
    'ok', true,
    'cargo_shipment_id', dkd_shipment_id,
    'courier_job_id', dkd_job_id,
    'reward_score', dkd_reward_score,
    'fee_tl', dkd_fee_tl
  );
end;
$$;

revoke all on function public.dkd_cargo_shipment_create(text, text, text, text, text, text, numeric, numeric, numeric) from public;
grant execute on function public.dkd_cargo_shipment_create(text, text, text, text, text, text, numeric, numeric, numeric) to authenticated;

drop function if exists public.dkd_cargo_shipments_for_me();
create function public.dkd_cargo_shipments_for_me()
returns table (
  id bigint,
  customer_user_id uuid,
  customer_first_name text,
  customer_last_name text,
  customer_full_name text,
  customer_national_id text,
  pickup_address_text text,
  package_content_text text,
  package_image_url text,
  package_weight_kg numeric,
  status text,
  created_at timestamptz,
  accepted_at timestamptz,
  picked_up_at timestamptz,
  completed_at timestamptz,
  courier_job_id bigint,
  assigned_courier_user_id uuid,
  courier_display_name text,
  courier_plate_no text,
  courier_vehicle_type text,
  courier_lat numeric,
  courier_lng numeric,
  courier_eta_min integer,
  courier_location_updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id uuid := auth.uid();
begin
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  return query
  select
    dkd_shipment_row.id,
    dkd_shipment_row.customer_user_id,
    dkd_shipment_row.customer_first_name,
    dkd_shipment_row.customer_last_name,
    trim(concat(dkd_shipment_row.customer_first_name, ' ', dkd_shipment_row.customer_last_name)) as customer_full_name,
    dkd_shipment_row.customer_national_id,
    dkd_shipment_row.pickup_address_text,
    dkd_shipment_row.package_content_text,
    dkd_shipment_row.package_image_url,
    dkd_shipment_row.package_weight_kg,
    dkd_shipment_row.status,
    dkd_shipment_row.created_at,
    dkd_shipment_row.accepted_at,
    dkd_shipment_row.picked_up_at,
    dkd_shipment_row.completed_at,
    dkd_shipment_row.courier_job_id,
    dkd_shipment_row.assigned_courier_user_id,
    coalesce(nullif(trim(coalesce(dkd_profile_row.nickname, '')), ''), case when dkd_shipment_row.assigned_courier_user_id is null then '' else concat('Kurye ', substr(dkd_shipment_row.assigned_courier_user_id::text, 1, 6)) end) as courier_display_name,
    coalesce(nullif(trim(coalesce(dkd_location_row.plate_no, '')), ''), nullif(trim(coalesce(dkd_shipment_row.assigned_courier_plate_no, '')), ''), nullif(trim(coalesce(dkd_profile_row.courier_profile_meta->>'plate_no', '')), ''), nullif(trim(coalesce(dkd_profile_row.courier_profile_meta->>'plateNo', '')), '')) as courier_plate_no,
    coalesce(nullif(trim(coalesce(dkd_location_row.vehicle_type, '')), ''), nullif(trim(coalesce(dkd_shipment_row.assigned_courier_vehicle_type, '')), ''), nullif(trim(coalesce(dkd_profile_row.courier_vehicle_type, '')), '')) as courier_vehicle_type,
    dkd_location_row.lat as courier_lat,
    dkd_location_row.lng as courier_lng,
    coalesce(dkd_location_row.eta_min, dkd_shipment_row.courier_eta_min) as courier_eta_min,
    dkd_location_row.updated_at as courier_location_updated_at
  from public.dkd_cargo_shipments dkd_shipment_row
  left join public.dkd_profiles dkd_profile_row
    on dkd_profile_row.user_id = dkd_shipment_row.assigned_courier_user_id
  left join public.dkd_courier_live_locations dkd_location_row
    on dkd_location_row.courier_user_id = dkd_shipment_row.assigned_courier_user_id
  where dkd_shipment_row.customer_user_id = dkd_user_id
  order by dkd_shipment_row.created_at desc;
end;
$$;

revoke all on function public.dkd_cargo_shipments_for_me() from public;
grant execute on function public.dkd_cargo_shipments_for_me() to authenticated;

drop function if exists public.dkd_courier_location_ping(numeric, numeric, integer, text, text);
create function public.dkd_courier_location_ping(
  dkd_param_lat numeric default null,
  dkd_param_lng numeric default null,
  dkd_param_eta_min integer default null,
  dkd_param_plate_no text default null,
  dkd_param_vehicle_type text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id uuid := auth.uid();
begin
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  insert into public.dkd_courier_live_locations (
    courier_user_id,
    lat,
    lng,
    eta_min,
    plate_no,
    vehicle_type,
    updated_at
  ) values (
    dkd_user_id,
    dkd_param_lat,
    dkd_param_lng,
    dkd_param_eta_min,
    nullif(trim(coalesce(dkd_param_plate_no, '')), ''),
    nullif(trim(lower(coalesce(dkd_param_vehicle_type, ''))), ''),
    now()
  )
  on conflict (courier_user_id)
  do update set
    lat = excluded.lat,
    lng = excluded.lng,
    eta_min = coalesce(excluded.eta_min, public.dkd_courier_live_locations.eta_min),
    plate_no = coalesce(excluded.plate_no, public.dkd_courier_live_locations.plate_no),
    vehicle_type = coalesce(excluded.vehicle_type, public.dkd_courier_live_locations.vehicle_type),
    updated_at = now();

  update public.dkd_cargo_shipments
  set
    courier_eta_min = coalesce(dkd_param_eta_min, courier_eta_min),
    assigned_courier_plate_no = coalesce(nullif(trim(coalesce(dkd_param_plate_no, '')), ''), assigned_courier_plate_no),
    assigned_courier_vehicle_type = coalesce(nullif(trim(lower(coalesce(dkd_param_vehicle_type, ''))), ''), assigned_courier_vehicle_type),
    updated_at = now()
  where assigned_courier_user_id = dkd_user_id
    and status in ('accepted', 'picked_up');

  return jsonb_build_object('ok', true, 'courier_user_id', dkd_user_id);
end;
$$;

revoke all on function public.dkd_courier_location_ping(numeric, numeric, integer, text, text) from public;
grant execute on function public.dkd_courier_location_ping(numeric, numeric, integer, text, text) to authenticated;

create or replace function public.dkd_courier_job_accept(
  dkd_param_job_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_cargo_shipment_id bigint := null;
  dkd_eta_min integer := null;
  dkd_plate_no text := null;
  dkd_vehicle_type text := null;
begin
  if dkd_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  update public.dkd_courier_jobs
  set assigned_user_id = dkd_user_id,
      status = 'accepted',
      accepted_at = coalesce(accepted_at, now()),
      updated_at = now()
  where public.dkd_courier_jobs.id = dkd_param_job_id
    and (public.dkd_courier_jobs.assigned_user_id is null or public.dkd_courier_jobs.assigned_user_id = dkd_user_id)
    and coalesce(public.dkd_courier_jobs.status, 'open') in ('open', 'ready', 'published', 'accepted')
  returning cargo_shipment_id, eta_min
  into dkd_cargo_shipment_id, dkd_eta_min;

  if dkd_param_job_id is null or (dkd_cargo_shipment_id is null and not exists (select 1 from public.dkd_courier_jobs where id = dkd_param_job_id and assigned_user_id = dkd_user_id)) then
    return jsonb_build_object('ok', false, 'reason', 'job_not_available');
  end if;

  select
    nullif(trim(coalesce(dkd_profiles.courier_profile_meta->>'plate_no', dkd_profiles.courier_profile_meta->>'plateNo', '')), ''),
    nullif(trim(coalesce(dkd_profiles.courier_vehicle_type, dkd_profiles.courier_profile_meta->>'vehicle_type', '')), '')
  into dkd_plate_no, dkd_vehicle_type
  from public.dkd_profiles
  where public.dkd_profiles.user_id = dkd_user_id;

  if dkd_cargo_shipment_id is not null then
    update public.dkd_cargo_shipments
    set status = 'accepted',
        accepted_at = coalesce(accepted_at, now()),
        assigned_courier_user_id = dkd_user_id,
        assigned_courier_plate_no = coalesce(dkd_plate_no, assigned_courier_plate_no),
        assigned_courier_vehicle_type = coalesce(dkd_vehicle_type, assigned_courier_vehicle_type),
        courier_eta_min = coalesce(dkd_eta_min, courier_eta_min),
        updated_at = now()
    where id = dkd_cargo_shipment_id;
  end if;

  return jsonb_build_object('ok', true, 'job_id', dkd_param_job_id, 'cargo_shipment_id', dkd_cargo_shipment_id, 'reason', 'accepted');
end;
$$;

grant execute on function public.dkd_courier_job_accept(bigint) to authenticated;

create or replace function public.dkd_courier_job_mark_picked_up(
  dkd_param_job_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_cargo_shipment_id bigint := null;
begin
  if dkd_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  update public.dkd_courier_jobs
  set pickup_status = 'picked_up',
      status = 'picked_up',
      picked_up_at = coalesce(picked_up_at, now()),
      updated_at = now()
  where public.dkd_courier_jobs.id = dkd_param_job_id
    and public.dkd_courier_jobs.assigned_user_id = dkd_user_id
  returning cargo_shipment_id into dkd_cargo_shipment_id;

  if dkd_cargo_shipment_id is null and not exists (select 1 from public.dkd_courier_jobs where id = dkd_param_job_id and assigned_user_id = dkd_user_id) then
    return jsonb_build_object('ok', false, 'reason', 'job_not_found');
  end if;

  if dkd_cargo_shipment_id is not null then
    update public.dkd_cargo_shipments
    set status = 'picked_up',
        picked_up_at = coalesce(picked_up_at, now()),
        updated_at = now()
    where id = dkd_cargo_shipment_id;
  end if;

  return jsonb_build_object('ok', true, 'job_id', dkd_param_job_id, 'cargo_shipment_id', dkd_cargo_shipment_id, 'reason', 'picked_up');
end;
$$;

grant execute on function public.dkd_courier_job_mark_picked_up(bigint) to authenticated;

create or replace function public.dkd_courier_job_complete(
  dkd_param_job_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_fee_tl numeric(12,2) := 0;
  dkd_reward_score integer := 0;
  dkd_token_reward integer := 0;
  dkd_eta_min integer := 0;
  dkd_wallet_after numeric(12,2) := 0;
  dkd_token_after integer := 0;
  dkd_courier_score_after integer := 0;
  dkd_courier_completed_jobs_after integer := 0;
  dkd_cargo_shipment_id bigint := null;
begin
  if dkd_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  update public.dkd_courier_jobs
  set status = 'completed',
      completed_at = coalesce(completed_at, now()),
      is_active = false,
      pickup_status = 'delivered',
      updated_at = now()
  where public.dkd_courier_jobs.id = dkd_param_job_id
    and public.dkd_courier_jobs.assigned_user_id = dkd_user_id
    and coalesce(public.dkd_courier_jobs.status, 'accepted') <> 'completed'
  returning coalesce(public.dkd_courier_jobs.fee_tl, 0), coalesce(public.dkd_courier_jobs.reward_score, 0), coalesce(public.dkd_courier_jobs.eta_min, 0), public.dkd_courier_jobs.cargo_shipment_id
  into dkd_fee_tl, dkd_reward_score, dkd_eta_min, dkd_cargo_shipment_id;

  if dkd_fee_tl is null then
    return jsonb_build_object('ok', false, 'reason', 'job_not_found');
  end if;

  dkd_token_reward := greatest(dkd_reward_score * 4, 10);

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id)
  on conflict (user_id) do nothing;

  update public.dkd_profiles
  set courier_score = coalesce(public.dkd_profiles.courier_score, 0) + dkd_reward_score,
      courier_completed_jobs = coalesce(public.dkd_profiles.courier_completed_jobs, 0) + 1,
      token = coalesce(public.dkd_profiles.token, 0) + dkd_token_reward,
      wallet_tl = coalesce(public.dkd_profiles.wallet_tl, 0) + dkd_fee_tl,
      courier_wallet_tl = coalesce(public.dkd_profiles.courier_wallet_tl, 0) + dkd_fee_tl,
      courier_total_earned_tl = coalesce(public.dkd_profiles.courier_total_earned_tl, 0) + dkd_fee_tl,
      courier_last_completed_at = now(),
      courier_fastest_eta_min = case
        when dkd_eta_min <= 0 then public.dkd_profiles.courier_fastest_eta_min
        when public.dkd_profiles.courier_fastest_eta_min is null then dkd_eta_min
        else least(public.dkd_profiles.courier_fastest_eta_min, dkd_eta_min)
      end,
      updated_at = now()
  where public.dkd_profiles.user_id = dkd_user_id
  returning public.dkd_profiles.wallet_tl, public.dkd_profiles.token, public.dkd_profiles.courier_score, public.dkd_profiles.courier_completed_jobs
  into dkd_wallet_after, dkd_token_after, dkd_courier_score_after, dkd_courier_completed_jobs_after;

  if dkd_cargo_shipment_id is not null then
    update public.dkd_cargo_shipments
    set status = 'completed',
        completed_at = coalesce(completed_at, now()),
        courier_eta_min = 0,
        updated_at = now()
    where id = dkd_cargo_shipment_id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'job_id', dkd_param_job_id,
    'cargo_shipment_id', dkd_cargo_shipment_id,
    'reason', 'completed',
    'fee_tl', dkd_fee_tl,
    'wallet_tl', dkd_wallet_after,
    'token', dkd_token_after,
    'courier_score', dkd_courier_score_after,
    'courier_completed_jobs', dkd_courier_completed_jobs_after
  );
end;
$$;

grant execute on function public.dkd_courier_job_complete(bigint) to authenticated;

commit;
