begin;

-- DKD Lootonia / Acil Kurye v2
-- Bildirim hedefleme + mağaza bazlı ürün toplamı + fatura sonrası teslimat akışı.

alter table public.dkd_urgent_courier_order_items
  add column if not exists dkd_product_total_tl numeric(12,2) not null default 0;

alter table public.dkd_urgent_courier_orders
  add column if not exists dkd_items_picked_up_at timestamptz,
  add column if not exists dkd_delivery_completed_at timestamptz;

create table if not exists public.dkd_urgent_courier_push_audit (
  dkd_audit_id bigint generated by default as identity primary key,
  dkd_dedupe_key text not null unique,
  dkd_event_key text not null,
  dkd_order_id uuid not null,
  dkd_message_id uuid null,
  dkd_target_user_id uuid null,
  expo_push_token text not null,
  dkd_title text not null default '',
  dkd_body text not null default '',
  dkd_payload jsonb not null default '{}'::jsonb,
  dkd_send_status text not null default 'pending',
  dkd_send_error text null,
  dkd_sent_at timestamptz null,
  dkd_created_at timestamptz not null default timezone('utc', now())
);

create index if not exists dkd_urgent_courier_push_audit_order_idx
  on public.dkd_urgent_courier_push_audit(dkd_order_id, dkd_event_key, dkd_created_at desc);

create index if not exists dkd_urgent_courier_push_audit_status_idx
  on public.dkd_urgent_courier_push_audit(dkd_send_status, dkd_created_at desc);

create or replace function public.dkd_urgent_courier_order_json_dkd(
  dkd_param_order_id uuid
)
returns jsonb
language plpgsql
stable
set search_path = public
as $dkd_order_json$
declare
  dkd_result_value jsonb := '{}'::jsonb;
begin
  select jsonb_build_object(
    'dkd_order_id', dkd_order_row.dkd_order_id,
    'dkd_customer_user_id', dkd_order_row.dkd_customer_user_id,
    'dkd_courier_user_id', dkd_order_row.dkd_courier_user_id,
    'dkd_customer_full_name', dkd_order_row.dkd_customer_full_name,
    'dkd_customer_display_name', coalesce(nullif(trim(coalesce(dkd_order_row.dkd_customer_full_name, '')), ''), nullif(trim(coalesce(dkd_customer_profile_row.nickname, '')), ''), 'Müşteri'),
    'dkd_courier_display_name', coalesce(nullif(trim(coalesce(dkd_courier_profile_row.nickname, '')), ''), case when dkd_order_row.dkd_courier_user_id is null then '' else 'Kurye' end),
    'dkd_customer_avatar_image_url', coalesce(dkd_customer_profile_row.avatar_image_url, ''),
    'dkd_customer_avatar_emoji', coalesce(nullif(trim(coalesce(dkd_customer_profile_row.avatar_emoji, '')), ''), '👤'),
    'dkd_courier_avatar_image_url', coalesce(dkd_courier_profile_row.avatar_image_url, ''),
    'dkd_courier_avatar_emoji', coalesce(nullif(trim(coalesce(dkd_courier_profile_row.avatar_emoji, '')), ''), '🛵'),
    'dkd_customer_phone_text', dkd_order_row.dkd_customer_phone_text,
    'dkd_customer_address_text', dkd_order_row.dkd_customer_address_text,
    'dkd_customer_note_text', dkd_order_row.dkd_customer_note_text,
    'dkd_status_key', dkd_order_row.dkd_status_key,
    'dkd_courier_fee_tl', dkd_order_row.dkd_courier_fee_tl,
    'dkd_product_total_tl', dkd_order_row.dkd_product_total_tl,
    'dkd_invoice_image_url', dkd_order_row.dkd_invoice_image_url,
    'dkd_chat_enabled_value', dkd_order_row.dkd_chat_enabled_value,
    'dkd_items_picked_up_at', dkd_order_row.dkd_items_picked_up_at,
    'dkd_delivery_completed_at', dkd_order_row.dkd_delivery_completed_at,
    'dkd_created_at', dkd_order_row.dkd_created_at,
    'dkd_updated_at', dkd_order_row.dkd_updated_at,
    'dkd_item_values', coalesce((
      select jsonb_agg(jsonb_build_object(
        'dkd_item_id', dkd_item_row.dkd_item_id,
        'dkd_store_group_key', dkd_item_row.dkd_store_group_key,
        'dkd_store_name', dkd_item_row.dkd_store_name,
        'dkd_product_text', dkd_item_row.dkd_product_text,
        'dkd_product_total_tl', coalesce(dkd_item_row.dkd_product_total_tl, 0),
        'dkd_is_nearest_pharmacy', dkd_item_row.dkd_is_nearest_pharmacy
      ) order by dkd_item_row.dkd_created_at asc)
      from public.dkd_urgent_courier_order_items dkd_item_row
      where dkd_item_row.dkd_order_id = dkd_order_row.dkd_order_id
    ), '[]'::jsonb),
    'dkd_message_values', coalesce((
      select jsonb_agg(jsonb_build_object(
        'dkd_message_id', dkd_message_row.dkd_message_id,
        'dkd_sender_role_key', dkd_message_row.dkd_sender_role_key,
        'dkd_sender_display_name', case
          when dkd_message_row.dkd_sender_role_key = 'dkd_customer' then coalesce(nullif(trim(coalesce(dkd_order_row.dkd_customer_full_name, '')), ''), nullif(trim(coalesce(dkd_message_profile_row.nickname, '')), ''), 'Müşteri')
          when dkd_message_row.dkd_sender_role_key = 'dkd_courier' then coalesce(nullif(trim(coalesce(dkd_message_profile_row.nickname, '')), ''), nullif(trim(coalesce(dkd_courier_profile_row.nickname, '')), ''), 'Kurye')
          else coalesce(nullif(trim(coalesce(dkd_message_profile_row.nickname, '')), ''), 'Lootonia')
        end,
        'dkd_sender_avatar_image_url', coalesce(dkd_message_profile_row.avatar_image_url, ''),
        'dkd_sender_avatar_emoji', case
          when dkd_message_row.dkd_sender_role_key = 'dkd_customer' then coalesce(nullif(trim(coalesce(dkd_message_profile_row.avatar_emoji, '')), ''), '👤')
          when dkd_message_row.dkd_sender_role_key = 'dkd_courier' then coalesce(nullif(trim(coalesce(dkd_message_profile_row.avatar_emoji, '')), ''), '🛵')
          else coalesce(nullif(trim(coalesce(dkd_message_profile_row.avatar_emoji, '')), ''), '●')
        end,
        'dkd_message_text', dkd_message_row.dkd_message_text,
        'dkd_created_at', dkd_message_row.dkd_created_at
      ) order by dkd_message_row.dkd_created_at asc)
      from public.dkd_urgent_courier_messages dkd_message_row
      left join public.dkd_profiles dkd_message_profile_row
        on dkd_message_profile_row.user_id = dkd_message_row.dkd_sender_user_id
      where dkd_message_row.dkd_order_id = dkd_order_row.dkd_order_id
    ), '[]'::jsonb)
  )
  into dkd_result_value
  from public.dkd_urgent_courier_orders dkd_order_row
  left join public.dkd_profiles dkd_customer_profile_row
    on dkd_customer_profile_row.user_id = dkd_order_row.dkd_customer_user_id
  left join public.dkd_profiles dkd_courier_profile_row
    on dkd_courier_profile_row.user_id = dkd_order_row.dkd_courier_user_id
  where dkd_order_row.dkd_order_id = dkd_param_order_id;

  return coalesce(dkd_result_value, '{}'::jsonb);
end;
$dkd_order_json$;

create or replace function public.dkd_urgent_courier_set_item_totals_dkd(
  dkd_param_order_id uuid,
  dkd_param_item_totals jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $dkd_set_item_totals$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_payload_value jsonb := coalesce(dkd_param_item_totals, '[]'::jsonb);
  dkd_sum_value numeric(12,2) := 0;
  dkd_order_item_count_value integer := 0;
  dkd_payload_item_count_value integer := 0;
  dkd_updated_count_value integer := 0;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;
  if jsonb_typeof(dkd_payload_value) <> 'array' then
    raise exception 'item_totals_required';
  end if;

  if not exists (
    select 1
    from public.dkd_urgent_courier_orders dkd_order_check_row
    where dkd_order_check_row.dkd_order_id = dkd_param_order_id
      and dkd_order_check_row.dkd_courier_user_id = dkd_user_id_value
      and dkd_order_check_row.dkd_status_key in ('dkd_fee_paid_shopping', 'dkd_product_total_waiting', 'dkd_product_total_approved')
  ) then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'order_not_ready');
  end if;

  select count(*)
  into dkd_order_item_count_value
  from public.dkd_urgent_courier_order_items dkd_item_row
  where dkd_item_row.dkd_order_id = dkd_param_order_id;

  select count(*)
  into dkd_payload_item_count_value
  from jsonb_array_elements(dkd_payload_value) dkd_payload_row(dkd_payload_item)
  where coalesce((dkd_payload_row.dkd_payload_item ->> 'dkd_product_total_tl')::numeric, 0) > 0;

  if dkd_order_item_count_value <= 0 or dkd_payload_item_count_value < dkd_order_item_count_value then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'all_store_totals_required');
  end if;

  update public.dkd_urgent_courier_order_items dkd_item_row
  set dkd_product_total_tl = round(greatest(coalesce((dkd_payload_source_value.dkd_payload_item ->> 'dkd_product_total_tl')::numeric, 0), 0), 2)
  from jsonb_array_elements(dkd_payload_value) dkd_payload_source_value(dkd_payload_item)
  where dkd_item_row.dkd_order_id = dkd_param_order_id
    and dkd_item_row.dkd_item_id = (dkd_payload_source_value.dkd_payload_item ->> 'dkd_item_id')::uuid;

  get diagnostics dkd_updated_count_value = row_count;

  if dkd_updated_count_value < dkd_order_item_count_value then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'all_store_totals_required');
  end if;

  select round(coalesce(sum(dkd_item_row.dkd_product_total_tl), 0), 2)
  into dkd_sum_value
  from public.dkd_urgent_courier_order_items dkd_item_row
  where dkd_item_row.dkd_order_id = dkd_param_order_id;

  update public.dkd_urgent_courier_orders
  set dkd_product_total_tl = dkd_sum_value,
      dkd_product_total_submitted_at = now(),
      dkd_status_key = 'dkd_product_total_waiting'
  where dkd_order_id = dkd_param_order_id
    and dkd_courier_user_id = dkd_user_id_value
    and dkd_status_key in ('dkd_fee_paid_shopping', 'dkd_product_total_waiting', 'dkd_product_total_approved');

  get diagnostics dkd_updated_count_value = row_count;
  if dkd_updated_count_value <= 0 then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'order_not_ready');
  end if;

  insert into public.dkd_urgent_courier_messages (dkd_order_id, dkd_sender_user_id, dkd_sender_role_key, dkd_message_text)
  values (dkd_param_order_id, dkd_user_id_value, 'dkd_courier', concat('Mağaza bazlı ürün toplamları girildi. Genel toplam: ', dkd_sum_value::text, ' TL'));

  return jsonb_build_object('dkd_ok', true, 'dkd_order_id', dkd_param_order_id, 'dkd_product_total_tl', dkd_sum_value);
end;
$dkd_set_item_totals$;

create or replace function public.dkd_urgent_courier_set_product_total_dkd(
  dkd_param_order_id uuid,
  dkd_param_product_total_tl numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $dkd_set_product_total$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_total_value numeric(12,2) := round(greatest(coalesce(dkd_param_product_total_tl, 0), 0), 2);
  dkd_item_count_value integer := 0;
  dkd_updated_count_value integer := 0;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;
  if dkd_total_value <= 0 then
    raise exception 'product_total_required';
  end if;

  if not exists (
    select 1
    from public.dkd_urgent_courier_orders dkd_order_check_row
    where dkd_order_check_row.dkd_order_id = dkd_param_order_id
      and dkd_order_check_row.dkd_courier_user_id = dkd_user_id_value
      and dkd_order_check_row.dkd_status_key in ('dkd_fee_paid_shopping', 'dkd_product_total_waiting', 'dkd_product_total_approved')
  ) then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'order_not_ready');
  end if;

  select count(*)
  into dkd_item_count_value
  from public.dkd_urgent_courier_order_items dkd_item_row
  where dkd_item_row.dkd_order_id = dkd_param_order_id;

  if dkd_item_count_value <= 1 then
    update public.dkd_urgent_courier_order_items
    set dkd_product_total_tl = dkd_total_value
    where dkd_order_id = dkd_param_order_id;
  end if;

  update public.dkd_urgent_courier_orders
  set dkd_product_total_tl = dkd_total_value,
      dkd_product_total_submitted_at = now(),
      dkd_status_key = 'dkd_product_total_waiting'
  where dkd_order_id = dkd_param_order_id
    and dkd_courier_user_id = dkd_user_id_value
    and dkd_status_key in ('dkd_fee_paid_shopping', 'dkd_product_total_waiting', 'dkd_product_total_approved')
    and dkd_item_count_value <= 1;

  get diagnostics dkd_updated_count_value = row_count;
  if dkd_updated_count_value <= 0 then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'store_based_totals_required');
  end if;

  insert into public.dkd_urgent_courier_messages (dkd_order_id, dkd_sender_user_id, dkd_sender_role_key, dkd_message_text)
  values (dkd_param_order_id, dkd_user_id_value, 'dkd_courier', concat('Ürünlerin toplam TL fiyatı girildi: ', dkd_total_value::text, ' TL'));

  return jsonb_build_object('dkd_ok', true, 'dkd_order_id', dkd_param_order_id, 'dkd_product_total_tl', dkd_total_value);
end;
$dkd_set_product_total$;

create or replace function public.dkd_urgent_courier_customer_cancel_order_dkd(
  dkd_param_order_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $dkd_cancel_order$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_order_row_value public.dkd_urgent_courier_orders%rowtype;
  dkd_message_value text := 'Acil Kurye siparişi iptal edildi.';
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;

  select *
  into dkd_order_row_value
  from public.dkd_urgent_courier_orders
  where dkd_order_id = dkd_param_order_id
  for update;

  if dkd_order_row_value.dkd_order_id is null then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'order_not_found');
  end if;
  if dkd_order_row_value.dkd_status_key in ('dkd_completed', 'dkd_cancelled') then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'cancel_not_available');
  end if;
  if dkd_user_id_value <> dkd_order_row_value.dkd_customer_user_id
     and (dkd_order_row_value.dkd_courier_user_id is null or dkd_user_id_value <> dkd_order_row_value.dkd_courier_user_id) then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'not_order_member');
  end if;

  if dkd_user_id_value = dkd_order_row_value.dkd_customer_user_id then
    dkd_message_value := 'Müşteri Acil Kurye siparişini iptal etti.';
  else
    dkd_message_value := 'Kurye Acil Kurye siparişini iptal etti.';
  end if;

  update public.dkd_urgent_courier_orders
  set dkd_status_key = 'dkd_cancelled',
      dkd_chat_enabled_value = false
  where dkd_order_id = dkd_param_order_id;

  insert into public.dkd_urgent_courier_messages (dkd_order_id, dkd_sender_user_id, dkd_sender_role_key, dkd_message_text)
  values (
    dkd_param_order_id,
    dkd_user_id_value,
    case when dkd_user_id_value = dkd_order_row_value.dkd_customer_user_id then 'dkd_customer' else 'dkd_courier' end,
    dkd_message_value
  );

  return jsonb_build_object('dkd_ok', true, 'dkd_order_id', dkd_param_order_id);
end;
$dkd_cancel_order$;

create or replace function public.dkd_urgent_courier_send_message_dkd(
  dkd_param_order_id uuid,
  dkd_param_message_text text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $dkd_send_message$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_order_row_value public.dkd_urgent_courier_orders%rowtype;
  dkd_message_value text := trim(coalesce(dkd_param_message_text, ''));
  dkd_role_key_value text := 'dkd_customer';
  dkd_message_id_value uuid;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;
  if length(dkd_message_value) < 1 then
    raise exception 'message_required';
  end if;

  select *
  into dkd_order_row_value
  from public.dkd_urgent_courier_orders
  where dkd_order_id = dkd_param_order_id;

  if dkd_order_row_value.dkd_order_id is null then
    raise exception 'order_not_found';
  end if;
  if dkd_order_row_value.dkd_chat_enabled_value is not true then
    raise exception 'chat_not_enabled';
  end if;
  if dkd_order_row_value.dkd_status_key in ('dkd_cancelled', 'dkd_completed') then
    raise exception 'chat_closed';
  end if;
  if dkd_user_id_value = dkd_order_row_value.dkd_customer_user_id then
    dkd_role_key_value := 'dkd_customer';
  elsif dkd_user_id_value = dkd_order_row_value.dkd_courier_user_id then
    dkd_role_key_value := 'dkd_courier';
  else
    raise exception 'not_order_member';
  end if;

  insert into public.dkd_urgent_courier_messages (dkd_order_id, dkd_sender_user_id, dkd_sender_role_key, dkd_message_text)
  values (dkd_param_order_id, dkd_user_id_value, dkd_role_key_value, dkd_message_value)
  returning dkd_message_id into dkd_message_id_value;

  return jsonb_build_object('dkd_ok', true, 'dkd_order_id', dkd_param_order_id, 'dkd_message_id', dkd_message_id_value);
end;
$dkd_send_message$;

create or replace function public.dkd_urgent_courier_pickup_items_dkd(
  dkd_param_order_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $dkd_pickup_items$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_updated_count_value integer := 0;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;

  update public.dkd_urgent_courier_orders
  set dkd_status_key = 'dkd_on_the_way',
      dkd_items_picked_up_at = now(),
      dkd_chat_enabled_value = true
  where dkd_order_id = dkd_param_order_id
    and dkd_courier_user_id = dkd_user_id_value
    and dkd_status_key in ('dkd_invoice_uploaded', 'dkd_on_the_way');

  get diagnostics dkd_updated_count_value = row_count;
  if dkd_updated_count_value <= 0 then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'pickup_not_ready');
  end if;

  insert into public.dkd_urgent_courier_messages (dkd_order_id, dkd_sender_user_id, dkd_sender_role_key, dkd_message_text)
  values (dkd_param_order_id, dkd_user_id_value, 'dkd_courier', 'Kurye ürünleri teslim aldı ve müşteriye doğru yola çıktı.');

  return jsonb_build_object('dkd_ok', true, 'dkd_order_id', dkd_param_order_id);
end;
$dkd_pickup_items$;

create or replace function public.dkd_urgent_courier_complete_delivery_dkd(
  dkd_param_order_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $dkd_complete_delivery$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_updated_count_value integer := 0;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;

  update public.dkd_urgent_courier_orders
  set dkd_status_key = 'dkd_completed',
      dkd_delivery_completed_at = now(),
      dkd_chat_enabled_value = false
  where dkd_order_id = dkd_param_order_id
    and dkd_courier_user_id = dkd_user_id_value
    and dkd_status_key in ('dkd_on_the_way', 'dkd_invoice_uploaded');

  get diagnostics dkd_updated_count_value = row_count;
  if dkd_updated_count_value <= 0 then
    return jsonb_build_object('dkd_ok', false, 'dkd_reason', 'delivery_not_ready');
  end if;

  insert into public.dkd_urgent_courier_messages (dkd_order_id, dkd_sender_user_id, dkd_sender_role_key, dkd_message_text)
  values (dkd_param_order_id, dkd_user_id_value, 'dkd_courier', 'Kurye siparişi müşteriye teslim etti ve işi tamamladı.');

  return jsonb_build_object('dkd_ok', true, 'dkd_order_id', dkd_param_order_id);
end;
$dkd_complete_delivery$;

create or replace function public.dkd_urgent_courier_push_targets_dkd(
  dkd_param_order_id uuid,
  dkd_param_event_key text,
  dkd_param_message_id uuid default null
)
returns table(
  dkd_target_user_id uuid,
  expo_push_token text,
  dkd_title text,
  dkd_body text,
  dkd_payload jsonb,
  dkd_dedupe_key text
)
language sql
security definer
set search_path = public
as $dkd_push_targets$
  with dkd_order_scope as (
    select
      dkd_order_row.*,
      coalesce(nullif(trim(dkd_order_row.dkd_customer_full_name), ''), 'Müşteri') as dkd_customer_name_value,
      coalesce(nullif(trim(dkd_courier_profile_row.nickname), ''), 'Kurye') as dkd_courier_name_value
    from public.dkd_urgent_courier_orders dkd_order_row
    left join public.dkd_profiles dkd_courier_profile_row
      on dkd_courier_profile_row.user_id = dkd_order_row.dkd_courier_user_id
    where dkd_order_row.dkd_order_id = dkd_param_order_id
  ),
  dkd_message_scope as (
    select
      dkd_message_row.dkd_message_id,
      dkd_message_row.dkd_sender_user_id,
      dkd_message_row.dkd_sender_role_key,
      dkd_message_row.dkd_message_text
    from public.dkd_urgent_courier_messages dkd_message_row
    where dkd_message_row.dkd_message_id = dkd_param_message_id
  ),
  dkd_target_scope as (
    select distinct
      case
        when dkd_param_event_key = 'dkd_urgent_order_created' then dkd_token_row.user_id
        when dkd_param_event_key = 'dkd_urgent_courier_accepted' then dkd_order_scope.dkd_customer_user_id
        when dkd_param_event_key = 'dkd_urgent_order_cancelled' then dkd_order_scope.dkd_customer_user_id
        when dkd_param_event_key = 'dkd_urgent_product_total_sent' then dkd_order_scope.dkd_customer_user_id
        when dkd_param_event_key = 'dkd_urgent_invoice_uploaded' then dkd_order_scope.dkd_customer_user_id
        when dkd_param_event_key = 'dkd_urgent_items_picked_up' then dkd_order_scope.dkd_customer_user_id
        when dkd_param_event_key = 'dkd_urgent_delivery_completed' then dkd_order_scope.dkd_customer_user_id
        when dkd_param_event_key = 'dkd_urgent_message_sent' and coalesce(dkd_message_scope.dkd_sender_role_key, '') = 'dkd_customer' then dkd_order_scope.dkd_courier_user_id
        when dkd_param_event_key = 'dkd_urgent_message_sent' and coalesce(dkd_message_scope.dkd_sender_role_key, '') = 'dkd_courier' then dkd_order_scope.dkd_customer_user_id
        when dkd_param_event_key = 'dkd_urgent_auto_message' then dkd_order_scope.dkd_customer_user_id
        else null::uuid
      end as dkd_target_user_id,
      dkd_order_scope.dkd_order_id,
      dkd_order_scope.dkd_customer_user_id,
      dkd_order_scope.dkd_courier_user_id,
      dkd_order_scope.dkd_customer_name_value,
      dkd_order_scope.dkd_courier_name_value,
      coalesce(dkd_message_scope.dkd_message_text, '') as dkd_message_text_value,
      coalesce(dkd_message_scope.dkd_sender_role_key, '') as dkd_sender_role_key_value
    from dkd_order_scope
    left join dkd_message_scope on true
    left join public.dkd_push_tokens dkd_token_row
      on dkd_param_event_key = 'dkd_urgent_order_created'
     and dkd_token_row.is_active = true
     and public.dkd_urgent_courier_license_active_dkd(dkd_token_row.user_id) is true
     and dkd_token_row.user_id <> dkd_order_scope.dkd_customer_user_id
  ),
  dkd_cancel_extra_scope as (
    select
      dkd_order_scope.dkd_courier_user_id as dkd_target_user_id,
      dkd_order_scope.dkd_order_id,
      dkd_order_scope.dkd_customer_user_id,
      dkd_order_scope.dkd_courier_user_id,
      dkd_order_scope.dkd_customer_name_value,
      dkd_order_scope.dkd_courier_name_value,
      ''::text as dkd_message_text_value,
      ''::text as dkd_sender_role_key_value
    from dkd_order_scope
    where dkd_param_event_key = 'dkd_urgent_order_cancelled'
      and dkd_order_scope.dkd_courier_user_id is not null
  ),
  dkd_auto_extra_scope as (
    select
      dkd_order_scope.dkd_courier_user_id as dkd_target_user_id,
      dkd_order_scope.dkd_order_id,
      dkd_order_scope.dkd_customer_user_id,
      dkd_order_scope.dkd_courier_user_id,
      dkd_order_scope.dkd_customer_name_value,
      dkd_order_scope.dkd_courier_name_value,
      coalesce(dkd_message_scope.dkd_message_text, '') as dkd_message_text_value,
      coalesce(dkd_message_scope.dkd_sender_role_key, '') as dkd_sender_role_key_value
    from dkd_order_scope
    left join dkd_message_scope on true
    where dkd_param_event_key = 'dkd_urgent_auto_message'
      and dkd_order_scope.dkd_courier_user_id is not null
  ),
  dkd_all_targets as (
    select * from dkd_target_scope
    union all
    select * from dkd_cancel_extra_scope
    union all
    select * from dkd_auto_extra_scope
  ),
  dkd_token_scope as (
    select
      dkd_all_targets.*,
      dkd_token_row.expo_push_token,
      row_number() over (
        partition by dkd_token_row.expo_push_token
        order by dkd_token_row.updated_at desc nulls last, dkd_token_row.id desc
      ) as dkd_token_rank
    from dkd_all_targets
    join public.dkd_push_tokens dkd_token_row
      on dkd_token_row.user_id = dkd_all_targets.dkd_target_user_id
     and dkd_token_row.is_active = true
     and nullif(trim(coalesce(dkd_token_row.expo_push_token, '')), '') is not null
    where dkd_all_targets.dkd_target_user_id is not null
  )
  select
    dkd_token_scope.dkd_target_user_id,
    dkd_token_scope.expo_push_token,
    case
      when dkd_param_event_key = 'dkd_urgent_order_created' then 'Yeni Acil Kurye Siparişi'
      when dkd_param_event_key = 'dkd_urgent_courier_accepted' then 'Kurye Görevi Kabul Etti'
      when dkd_param_event_key = 'dkd_urgent_order_cancelled' then 'Acil Kurye Siparişi İptal Edildi'
      when dkd_param_event_key = 'dkd_urgent_product_total_sent' then 'Ürün Toplamı Girildi'
      when dkd_param_event_key = 'dkd_urgent_invoice_uploaded' then 'Fatura Görseli Yüklendi'
      when dkd_param_event_key = 'dkd_urgent_items_picked_up' then 'Kurye Yola Çıktı'
      when dkd_param_event_key = 'dkd_urgent_delivery_completed' then 'Acil Kurye Teslim Edildi'
      when dkd_param_event_key = 'dkd_urgent_message_sent' then 'Acil Kurye Mesajı'
      when dkd_param_event_key = 'dkd_urgent_auto_message' then 'Acil Kurye Canlı Güncelleme'
      else 'Acil Kurye'
    end as dkd_title,
    case
      when dkd_param_event_key = 'dkd_urgent_order_created' then concat(dkd_token_scope.dkd_customer_name_value, ' yeni acil kurye siparişi oluşturdu.')
      when dkd_param_event_key = 'dkd_urgent_courier_accepted' then concat(dkd_token_scope.dkd_courier_name_value, ' görevi kabul etti ve taşıma ücretini gönderdi.')
      when dkd_param_event_key = 'dkd_urgent_order_cancelled' then concat(dkd_token_scope.dkd_customer_name_value, ' / Acil Kurye siparişi iptal edildi.')
      when dkd_param_event_key = 'dkd_urgent_product_total_sent' then 'Kurye mağaza bazlı ürün toplamlarını girdi. Onay bekliyor.'
      when dkd_param_event_key = 'dkd_urgent_invoice_uploaded' then 'Kurye faturayı yükledi. Görseli sipariş detayından inceleyebilirsin.'
      when dkd_param_event_key = 'dkd_urgent_items_picked_up' then 'Kurye ürünleri teslim aldı ve sana doğru yola çıktı.'
      when dkd_param_event_key = 'dkd_urgent_delivery_completed' then 'Kurye siparişi teslim etti ve işi tamamladı.'
      when dkd_param_event_key = 'dkd_urgent_message_sent' then left(coalesce(dkd_token_scope.dkd_message_text_value, 'Yeni mesajın var.'), 120)
      when dkd_param_event_key = 'dkd_urgent_auto_message' then left(coalesce(dkd_token_scope.dkd_message_text_value, 'Acil Kurye akışında yeni otomatik güncelleme var.'), 120)
      else 'Acil Kurye akışında yeni güncelleme var.'
    end as dkd_body,
    jsonb_build_object(
      'route', 'courier',
      'targetScreen', 'courier',
      'dkd_event_key', dkd_param_event_key,
      'dkd_urgent_courier_order_id', dkd_token_scope.dkd_order_id,
      'dkd_message_id', dkd_param_message_id,
      'dkd_push_segment', 'urgent_courier'
    ) as dkd_payload,
    concat(
      dkd_param_event_key,
      ':',
      dkd_token_scope.dkd_order_id::text,
      ':',
      coalesce(dkd_param_message_id::text, 'none'),
      ':',
      dkd_token_scope.dkd_target_user_id::text,
      ':',
      md5(dkd_token_scope.expo_push_token)
    ) as dkd_dedupe_key
  from dkd_token_scope
  where dkd_token_scope.dkd_token_rank = 1;
$dkd_push_targets$;

revoke all on function public.dkd_urgent_courier_set_item_totals_dkd(uuid, jsonb) from public;
revoke all on function public.dkd_urgent_courier_pickup_items_dkd(uuid) from public;
revoke all on function public.dkd_urgent_courier_complete_delivery_dkd(uuid) from public;
revoke all on function public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid) from public;

grant execute on function public.dkd_urgent_courier_order_json_dkd(uuid) to authenticated, service_role;
grant execute on function public.dkd_urgent_courier_set_product_total_dkd(uuid, numeric) to authenticated;
grant execute on function public.dkd_urgent_courier_set_item_totals_dkd(uuid, jsonb) to authenticated;
grant execute on function public.dkd_urgent_courier_customer_cancel_order_dkd(uuid) to authenticated;
grant execute on function public.dkd_urgent_courier_send_message_dkd(uuid, text) to authenticated;
grant execute on function public.dkd_urgent_courier_pickup_items_dkd(uuid) to authenticated;
grant execute on function public.dkd_urgent_courier_complete_delivery_dkd(uuid) to authenticated;
grant execute on function public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid) to authenticated, service_role;

grant select, insert, update on public.dkd_urgent_courier_push_audit to service_role;

commit;
