begin;

create table if not exists public.dkd_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  avatar_emoji text,
  wallet_tl numeric(12,2) not null default 0,
  courier_status text not null default 'none',
  courier_score integer not null default 0,
  courier_completed_jobs integer not null default 0,
  courier_wallet_tl numeric(12,2) not null default 0,
  courier_total_earned_tl numeric(12,2) not null default 0,
  courier_vehicle_type text,
  courier_city text,
  courier_zone text,
  courier_profile_meta jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table if exists public.dkd_profiles
  add column if not exists nickname text,
  add column if not exists avatar_emoji text,
  add column if not exists wallet_tl numeric(12,2) not null default 0,
  add column if not exists courier_status text not null default 'none',
  add column if not exists courier_score integer not null default 0,
  add column if not exists courier_completed_jobs integer not null default 0,
  add column if not exists courier_wallet_tl numeric(12,2) not null default 0,
  add column if not exists courier_total_earned_tl numeric(12,2) not null default 0,
  add column if not exists courier_vehicle_type text,
  add column if not exists courier_city text,
  add column if not exists courier_zone text,
  add column if not exists courier_profile_meta jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.dkd_cargo_shipments (
  id bigint generated by default as identity primary key,
  customer_user_id uuid not null references auth.users(id) on delete cascade,
  customer_first_name text not null default '',
  customer_last_name text not null default '',
  customer_national_id text not null default '',
  customer_phone_text text not null default '+90',
  pickup_address_text text not null default '',
  delivery_address_text text not null default '',
  delivery_note text,
  package_content_text text not null default '',
  package_image_url text,
  package_weight_kg numeric(10,2) not null default 1,
  status text not null default 'open',
  courier_job_id bigint,
  assigned_courier_user_id uuid references auth.users(id) on delete set null,
  assigned_courier_plate_no text,
  assigned_courier_vehicle_type text,
  courier_eta_min integer,
  pickup_lat numeric,
  pickup_lng numeric,
  dropoff_lat numeric,
  dropoff_lng numeric,
  courier_fee_tl numeric(12,2) not null default 0,
  customer_charge_tl numeric(12,2) not null default 0,
  payment_status text not null default 'pending_cash',
  paid_at timestamptz,
  accepted_at timestamptz,
  picked_up_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.dkd_cargo_shipments
  add column if not exists customer_phone_text text not null default '+90',
  add column if not exists delivery_address_text text not null default '',
  add column if not exists delivery_note text,
  add column if not exists dropoff_lat numeric,
  add column if not exists dropoff_lng numeric,
  add column if not exists courier_fee_tl numeric(12,2) not null default 0,
  add column if not exists customer_charge_tl numeric(12,2) not null default 0,
  add column if not exists payment_status text not null default 'pending_cash',
  add column if not exists paid_at timestamptz;

create table if not exists public.dkd_courier_jobs (
  id bigint generated by default as identity primary key,
  title text,
  pickup text,
  dropoff text,
  reward_score integer not null default 12,
  distance_km numeric not null default 1.0,
  eta_min integer not null default 15,
  job_type text not null default 'cargo',
  is_active boolean not null default true,
  status text not null default 'open',
  assigned_user_id uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  completed_at timestamptz,
  pickup_status text not null default 'pending',
  picked_up_at timestamptz,
  merchant_name text,
  product_title text,
  delivery_note text,
  delivery_address_text text,
  order_id bigint,
  business_id uuid,
  product_id bigint,
  customer_user_id uuid,
  pickup_lat numeric,
  pickup_lng numeric,
  dropoff_lat numeric,
  dropoff_lng numeric,
  fee_tl numeric(12,2) not null default 0,
  customer_charge_tl numeric(12,2) not null default 0,
  cargo_shipment_id bigint,
  cargo_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.dkd_courier_jobs
  add column if not exists pickup_status text not null default 'pending',
  add column if not exists picked_up_at timestamptz,
  add column if not exists merchant_name text,
  add column if not exists product_title text,
  add column if not exists delivery_note text,
  add column if not exists delivery_address_text text,
  add column if not exists order_id bigint,
  add column if not exists business_id uuid,
  add column if not exists product_id bigint,
  add column if not exists customer_user_id uuid,
  add column if not exists pickup_lat numeric,
  add column if not exists pickup_lng numeric,
  add column if not exists dropoff_lat numeric,
  add column if not exists dropoff_lng numeric,
  add column if not exists fee_tl numeric(12,2) not null default 0,
  add column if not exists customer_charge_tl numeric(12,2) not null default 0,
  add column if not exists cargo_shipment_id bigint,
  add column if not exists cargo_meta jsonb not null default '{}'::jsonb;

create index if not exists dkd_web_cargo_shipments_customer_idx
  on public.dkd_cargo_shipments(customer_user_id, created_at desc);

create index if not exists dkd_web_courier_jobs_status_idx
  on public.dkd_courier_jobs(status, created_at desc);

create index if not exists dkd_web_courier_jobs_assigned_idx
  on public.dkd_courier_jobs(assigned_user_id, created_at desc);

grant select, insert, update on public.dkd_cargo_shipments to authenticated;
grant select, insert, update on public.dkd_courier_jobs to authenticated;
grant select, insert, update on public.dkd_profiles to authenticated;

create or replace function public.dkd_web_cargo_customer_charge_dkd(
  dkd_param_courier_fee_tl numeric default null
)
returns numeric
language sql
immutable
as $$
  select round(greatest(coalesce(dkd_param_courier_fee_tl, 0), 0) * 1.22, 2);
$$;

create or replace function public.dkd_web_cargo_fee_from_weight_dkd(
  dkd_param_weight_kg numeric default null
)
returns numeric
language sql
immutable
as $$
  select greatest(50, round(45 + (greatest(coalesce(dkd_param_weight_kg, 1), 0.1) * 10), 2));
$$;

drop function if exists public.dkd_web_courier_operation_snapshot_dkd();
create function public.dkd_web_courier_operation_snapshot_dkd()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_profile_json_value jsonb := '{}'::jsonb;
  dkd_jobs_json_value jsonb := '[]'::jsonb;
  dkd_shipments_json_value jsonb := '[]'::jsonb;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id_value)
  on conflict (user_id) do nothing;

  select to_jsonb(dkd_profile_row)
  into dkd_profile_json_value
  from public.dkd_profiles dkd_profile_row
  where dkd_profile_row.user_id = dkd_user_id_value;

  select coalesce(jsonb_agg(to_jsonb(dkd_job_row) order by dkd_job_row.created_at desc), '[]'::jsonb)
  into dkd_jobs_json_value
  from public.dkd_courier_jobs dkd_job_row
  where coalesce(dkd_job_row.is_active, true) is true
    and (
      dkd_job_row.assigned_user_id = dkd_user_id_value
      or (
        dkd_job_row.assigned_user_id is null
        and coalesce(dkd_job_row.status, 'open') in ('open', 'ready', 'published')
      )
    );

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'id', dkd_shipment_row.id,
      'customer_user_id', dkd_shipment_row.customer_user_id,
      'customer_first_name', dkd_shipment_row.customer_first_name,
      'customer_last_name', dkd_shipment_row.customer_last_name,
      'customer_full_name', trim(concat(dkd_shipment_row.customer_first_name, ' ', dkd_shipment_row.customer_last_name)),
      'customer_phone_text', dkd_shipment_row.customer_phone_text,
      'pickup_address_text', dkd_shipment_row.pickup_address_text,
      'delivery_address_text', dkd_shipment_row.delivery_address_text,
      'delivery_note', dkd_shipment_row.delivery_note,
      'package_content_text', dkd_shipment_row.package_content_text,
      'package_image_url', dkd_shipment_row.package_image_url,
      'package_weight_kg', dkd_shipment_row.package_weight_kg,
      'status', dkd_shipment_row.status,
      'courier_job_id', dkd_shipment_row.courier_job_id,
      'courier_fee_tl', dkd_shipment_row.courier_fee_tl,
      'customer_charge_tl', dkd_shipment_row.customer_charge_tl,
      'payment_status', dkd_shipment_row.payment_status,
      'created_at', dkd_shipment_row.created_at,
      'accepted_at', dkd_shipment_row.accepted_at,
      'picked_up_at', dkd_shipment_row.picked_up_at,
      'completed_at', dkd_shipment_row.completed_at,
      'assigned_courier_user_id', dkd_shipment_row.assigned_courier_user_id,
      'courier_display_name', coalesce(nullif(trim(coalesce(dkd_profile_row.nickname, '')), ''), case when dkd_shipment_row.assigned_courier_user_id is null then '' else concat('Kurye ', substr(dkd_shipment_row.assigned_courier_user_id::text, 1, 6)) end),
      'courier_plate_no', coalesce(nullif(trim(coalesce(dkd_shipment_row.assigned_courier_plate_no, '')), ''), nullif(trim(coalesce(dkd_profile_row.courier_profile_meta->>'plate_no', '')), '')),
      'courier_vehicle_type', coalesce(nullif(trim(coalesce(dkd_shipment_row.assigned_courier_vehicle_type, '')), ''), nullif(trim(coalesce(dkd_profile_row.courier_vehicle_type, '')), '')),
      'courier_eta_min', dkd_shipment_row.courier_eta_min
    ) order by dkd_shipment_row.created_at desc
  ), '[]'::jsonb)
  into dkd_shipments_json_value
  from public.dkd_cargo_shipments dkd_shipment_row
  left join public.dkd_profiles dkd_profile_row
    on dkd_profile_row.user_id = dkd_shipment_row.assigned_courier_user_id
  where dkd_shipment_row.customer_user_id = dkd_user_id_value;

  return jsonb_build_object(
    'ok', true,
    'profile', coalesce(dkd_profile_json_value, '{}'::jsonb),
    'jobs', coalesce(dkd_jobs_json_value, '[]'::jsonb),
    'shipments', coalesce(dkd_shipments_json_value, '[]'::jsonb),
    'server_time', now()
  );
end;
$$;

drop function if exists public.dkd_web_cargo_create_dkd(text, text, text, text, text, text, text, numeric, text);
create function public.dkd_web_cargo_create_dkd(
  dkd_param_customer_first_name text default null,
  dkd_param_customer_last_name text default null,
  dkd_param_customer_phone_text text default null,
  dkd_param_pickup_address_text text default null,
  dkd_param_delivery_address_text text default null,
  dkd_param_package_content_text text default null,
  dkd_param_package_image_url text default null,
  dkd_param_package_weight_kg numeric default 1,
  dkd_param_delivery_note_text text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_first_name_value text := coalesce(nullif(trim(coalesce(dkd_param_customer_first_name, '')), ''), 'Gönderici');
  dkd_last_name_value text := coalesce(nullif(trim(coalesce(dkd_param_customer_last_name, '')), ''), 'Müşteri');
  dkd_phone_digits_value text := regexp_replace(coalesce(dkd_param_customer_phone_text, ''), '\D', '', 'g');
  dkd_phone_local_value text := '';
  dkd_phone_value text := '+90';
  dkd_pickup_address_value text := trim(coalesce(dkd_param_pickup_address_text, ''));
  dkd_delivery_address_value text := trim(coalesce(dkd_param_delivery_address_text, ''));
  dkd_package_content_value text := trim(coalesce(dkd_param_package_content_text, ''));
  dkd_weight_value numeric(10,2) := greatest(coalesce(dkd_param_package_weight_kg, 1), 0.1);
  dkd_courier_fee_value numeric(12,2) := 0;
  dkd_customer_charge_value numeric(12,2) := 0;
  dkd_eta_min_value integer := 18;
  dkd_shipment_id_value bigint;
  dkd_job_id_value bigint;
  dkd_full_name_value text;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;

  if length(dkd_pickup_address_value) < 8 then
    raise exception 'pickup_address_required';
  end if;

  if length(dkd_delivery_address_value) < 8 then
    raise exception 'delivery_address_required';
  end if;

  if length(dkd_package_content_value) < 2 then
    raise exception 'package_content_required';
  end if;

  dkd_phone_local_value := case
    when dkd_phone_digits_value like '90%' then substr(dkd_phone_digits_value, 3)
    else regexp_replace(dkd_phone_digits_value, '^0+', '')
  end;
  dkd_phone_local_value := substr(coalesce(dkd_phone_local_value, ''), 1, 10);

  if char_length(dkd_phone_local_value) = 10 and left(dkd_phone_local_value, 1) = '5' then
    dkd_phone_value := '+90' || dkd_phone_local_value;
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id_value)
  on conflict (user_id) do nothing;

  dkd_courier_fee_value := public.dkd_web_cargo_fee_from_weight_dkd(dkd_weight_value);
  dkd_customer_charge_value := public.dkd_web_cargo_customer_charge_dkd(dkd_courier_fee_value);
  dkd_eta_min_value := greatest(12, least(55, ceil(14 + (dkd_weight_value * 4))::integer));
  dkd_full_name_value := trim(concat(dkd_first_name_value, ' ', dkd_last_name_value));

  insert into public.dkd_cargo_shipments (
    customer_user_id,
    customer_first_name,
    customer_last_name,
    customer_national_id,
    customer_phone_text,
    pickup_address_text,
    delivery_address_text,
    delivery_note,
    package_content_text,
    package_image_url,
    package_weight_kg,
    status,
    pickup_lat,
    pickup_lng,
    dropoff_lat,
    dropoff_lng,
    courier_fee_tl,
    customer_charge_tl,
    payment_status,
    paid_at
  ) values (
    dkd_user_id_value,
    dkd_first_name_value,
    dkd_last_name_value,
    '',
    dkd_phone_value,
    dkd_pickup_address_value,
    dkd_delivery_address_value,
    nullif(trim(coalesce(dkd_param_delivery_note_text, '')), ''),
    dkd_package_content_value,
    nullif(trim(coalesce(dkd_param_package_image_url, '')), ''),
    dkd_weight_value,
    'open',
    39.92077,
    32.85411,
    39.92553,
    32.86628,
    dkd_courier_fee_value,
    dkd_customer_charge_value,
    'pending_cash',
    null
  ) returning id into dkd_shipment_id_value;

  insert into public.dkd_courier_jobs (
    title,
    pickup,
    dropoff,
    reward_score,
    distance_km,
    eta_min,
    job_type,
    is_active,
    status,
    pickup_status,
    merchant_name,
    product_title,
    delivery_note,
    delivery_address_text,
    customer_user_id,
    pickup_lat,
    pickup_lng,
    dropoff_lat,
    dropoff_lng,
    fee_tl,
    customer_charge_tl,
    cargo_shipment_id,
    cargo_meta
  ) values (
    concat('Kargo • ', dkd_full_name_value),
    dkd_pickup_address_value,
    dkd_delivery_address_value,
    greatest(14, ceil(dkd_weight_value * 8)::integer),
    2.4,
    dkd_eta_min_value,
    'cargo',
    true,
    'open',
    'pending',
    'Kurye-Kargo Operasyon Merkezi',
    dkd_package_content_value,
    coalesce(nullif(trim(coalesce(dkd_param_delivery_note_text, '')), ''), concat('Gönderici • ', dkd_full_name_value)),
    dkd_delivery_address_value,
    dkd_user_id_value,
    39.92077,
    32.85411,
    39.92553,
    32.86628,
    dkd_courier_fee_value,
    dkd_customer_charge_value,
    dkd_shipment_id_value,
    jsonb_build_object(
      'created_from', 'web_market',
      'customer_first_name', dkd_first_name_value,
      'customer_last_name', dkd_last_name_value,
      'customer_phone_text', dkd_phone_value,
      'package_weight_kg', dkd_weight_value,
      'package_image_url', nullif(trim(coalesce(dkd_param_package_image_url, '')), ''),
      'delivery_note', nullif(trim(coalesce(dkd_param_delivery_note_text, '')), ''),
      'cargo_customer_charge_tl', dkd_customer_charge_value,
      'cargo_courier_fee_tl', dkd_courier_fee_value,
      'payment_method', 'cash_on_delivery'
    )
  ) returning id into dkd_job_id_value;

  update public.dkd_cargo_shipments
  set courier_job_id = dkd_job_id_value,
      updated_at = now()
  where id = dkd_shipment_id_value;

  return jsonb_build_object(
    'ok', true,
    'cargo_shipment_id', dkd_shipment_id_value,
    'courier_job_id', dkd_job_id_value,
    'fee_tl', dkd_courier_fee_value,
    'customer_charge_tl', dkd_customer_charge_value,
    'payment_status', 'pending_cash'
  );
end;
$$;

drop function if exists public.dkd_web_courier_job_accept_dkd(bigint);
create function public.dkd_web_courier_job_accept_dkd(
  dkd_param_job_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_job_id_value bigint := null;
  dkd_cargo_shipment_id_value bigint := null;
  dkd_order_id_value bigint := null;
  dkd_plate_value text := '';
  dkd_vehicle_value text := '';
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id_value)
  on conflict (user_id) do nothing;

  select coalesce(nullif(trim(coalesce(dkd_profile_row.courier_profile_meta->>'plate_no', '')), ''), ''),
         coalesce(nullif(trim(coalesce(dkd_profile_row.courier_vehicle_type, '')), ''), nullif(trim(coalesce(dkd_profile_row.courier_profile_meta->>'vehicle_type', '')), ''), 'moto')
  into dkd_plate_value, dkd_vehicle_value
  from public.dkd_profiles dkd_profile_row
  where dkd_profile_row.user_id = dkd_user_id_value;

  update public.dkd_courier_jobs
  set assigned_user_id = dkd_user_id_value,
      status = 'accepted',
      accepted_at = coalesce(accepted_at, now()),
      pickup_status = case when coalesce(pickup_status, 'pending') = 'pending' then 'accepted' else pickup_status end,
      updated_at = now()
  where public.dkd_courier_jobs.id = dkd_param_job_id
    and (public.dkd_courier_jobs.assigned_user_id is null or public.dkd_courier_jobs.assigned_user_id = dkd_user_id_value)
    and coalesce(public.dkd_courier_jobs.status, 'open') in ('open', 'ready', 'published', 'accepted')
  returning public.dkd_courier_jobs.id, public.dkd_courier_jobs.cargo_shipment_id, public.dkd_courier_jobs.order_id
  into dkd_job_id_value, dkd_cargo_shipment_id_value, dkd_order_id_value;

  if dkd_job_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'job_not_available');
  end if;

  if dkd_cargo_shipment_id_value is not null then
    update public.dkd_cargo_shipments
    set status = 'accepted',
        assigned_courier_user_id = dkd_user_id_value,
        assigned_courier_plate_no = nullif(dkd_plate_value, ''),
        assigned_courier_vehicle_type = nullif(dkd_vehicle_value, ''),
        accepted_at = coalesce(accepted_at, now()),
        courier_eta_min = coalesce(courier_eta_min, 18),
        updated_at = now()
    where id = dkd_cargo_shipment_id_value;
  end if;

  return jsonb_build_object('ok', true, 'job_id', dkd_job_id_value, 'cargo_shipment_id', dkd_cargo_shipment_id_value, 'order_id', dkd_order_id_value);
end;
$$;

drop function if exists public.dkd_web_courier_job_picked_up_dkd(bigint);
create function public.dkd_web_courier_job_picked_up_dkd(
  dkd_param_job_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_job_id_value bigint := null;
  dkd_cargo_shipment_id_value bigint := null;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;

  update public.dkd_courier_jobs
  set pickup_status = 'picked_up',
      status = 'picked_up',
      picked_up_at = coalesce(picked_up_at, now()),
      updated_at = now()
  where public.dkd_courier_jobs.id = dkd_param_job_id
    and public.dkd_courier_jobs.assigned_user_id = dkd_user_id_value
    and coalesce(public.dkd_courier_jobs.status, 'accepted') in ('accepted', 'assigned_courier', 'picked_up')
  returning public.dkd_courier_jobs.id, public.dkd_courier_jobs.cargo_shipment_id
  into dkd_job_id_value, dkd_cargo_shipment_id_value;

  if dkd_job_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'job_not_found');
  end if;

  if dkd_cargo_shipment_id_value is not null then
    update public.dkd_cargo_shipments
    set status = 'picked_up',
        picked_up_at = coalesce(picked_up_at, now()),
        updated_at = now()
    where id = dkd_cargo_shipment_id_value;
  end if;

  return jsonb_build_object('ok', true, 'job_id', dkd_job_id_value, 'cargo_shipment_id', dkd_cargo_shipment_id_value);
end;
$$;

drop function if exists public.dkd_web_courier_job_complete_dkd(bigint);
create function public.dkd_web_courier_job_complete_dkd(
  dkd_param_job_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_job_id_value bigint := null;
  dkd_cargo_shipment_id_value bigint := null;
  dkd_fee_value numeric(12,2) := 0;
  dkd_reward_score_value integer := 0;
  dkd_wallet_after_value numeric(12,2) := 0;
begin
  if dkd_user_id_value is null then
    raise exception 'auth_required';
  end if;

  update public.dkd_courier_jobs
  set status = 'completed',
      pickup_status = 'delivered',
      completed_at = coalesce(completed_at, now()),
      is_active = false,
      updated_at = now()
  where public.dkd_courier_jobs.id = dkd_param_job_id
    and public.dkd_courier_jobs.assigned_user_id = dkd_user_id_value
    and coalesce(public.dkd_courier_jobs.status, 'accepted') <> 'completed'
  returning public.dkd_courier_jobs.id,
            public.dkd_courier_jobs.cargo_shipment_id,
            coalesce(public.dkd_courier_jobs.fee_tl, 0),
            coalesce(public.dkd_courier_jobs.reward_score, 0)
  into dkd_job_id_value, dkd_cargo_shipment_id_value, dkd_fee_value, dkd_reward_score_value;

  if dkd_job_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'job_not_found');
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id_value)
  on conflict (user_id) do nothing;

  update public.dkd_profiles
  set courier_status = case when coalesce(courier_status, 'none') = 'none' then 'approved' else courier_status end,
      courier_score = coalesce(courier_score, 0) + greatest(coalesce(dkd_reward_score_value, 0), 0),
      courier_completed_jobs = coalesce(courier_completed_jobs, 0) + 1,
      courier_wallet_tl = coalesce(courier_wallet_tl, 0) + greatest(coalesce(dkd_fee_value, 0), 0),
      courier_total_earned_tl = coalesce(courier_total_earned_tl, 0) + greatest(coalesce(dkd_fee_value, 0), 0),
      updated_at = now()
  where public.dkd_profiles.user_id = dkd_user_id_value
  returning public.dkd_profiles.courier_wallet_tl into dkd_wallet_after_value;

  if dkd_cargo_shipment_id_value is not null then
    update public.dkd_cargo_shipments
    set status = 'completed',
        completed_at = coalesce(completed_at, now()),
        courier_fee_tl = case when coalesce(courier_fee_tl, 0) > 0 then courier_fee_tl else dkd_fee_value end,
        updated_at = now()
    where id = dkd_cargo_shipment_id_value;
  end if;

  return jsonb_build_object(
    'ok', true,
    'job_id', dkd_job_id_value,
    'cargo_shipment_id', dkd_cargo_shipment_id_value,
    'fee_tl', dkd_fee_value,
    'courier_wallet_tl', dkd_wallet_after_value
  );
end;
$$;

grant execute on function public.dkd_web_courier_operation_snapshot_dkd() to authenticated;
grant execute on function public.dkd_web_cargo_create_dkd(text, text, text, text, text, text, text, numeric, text) to authenticated;
grant execute on function public.dkd_web_courier_job_accept_dkd(bigint) to authenticated;
grant execute on function public.dkd_web_courier_job_picked_up_dkd(bigint) to authenticated;
grant execute on function public.dkd_web_courier_job_complete_dkd(bigint) to authenticated;

commit;
