begin;

create extension if not exists pgcrypto;

create table if not exists public.dkd_support_customer_message_push_audit (
  dkd_id bigint generated by default as identity primary key,
  dkd_thread_id uuid null,
  dkd_message_id uuid null,
  dkd_source_user_id uuid null,
  dkd_target_count integer not null default 0,
  dkd_sent_count integer not null default 0,
  dkd_failed_count integer not null default 0,
  dkd_send_status text not null default 'pending',
  dkd_send_error text null,
  dkd_created_at timestamptz not null default timezone('utc', now())
);

create index if not exists dkd_support_customer_message_push_audit_thread_idx
  on public.dkd_support_customer_message_push_audit(dkd_thread_id, dkd_created_at desc);

create index if not exists dkd_support_customer_message_push_audit_source_user_idx
  on public.dkd_support_customer_message_push_audit(dkd_source_user_id, dkd_created_at desc);

alter table public.dkd_support_customer_message_push_audit enable row level security;

drop policy if exists dkd_support_customer_message_push_audit_admin_select on public.dkd_support_customer_message_push_audit;
create policy dkd_support_customer_message_push_audit_admin_select
  on public.dkd_support_customer_message_push_audit
  for select
  to authenticated
  using (coalesce(public.dkd_is_admin(), false));

grant select on table public.dkd_support_customer_message_push_audit to authenticated;
grant select, insert, update, delete on table public.dkd_support_customer_message_push_audit to service_role;
grant usage, select on sequence public.dkd_support_customer_message_push_audit_dkd_id_seq to service_role;

grant select on table public.dkd_admin_memberships to service_role;
grant select, update on table public.dkd_push_tokens to service_role;
grant select on table public.dkd_support_threads to service_role;
grant select on table public.dkd_support_messages to service_role;

update public.dkd_support_threads
set dkd_status_title = 'DKDai Yanıtladı'
where dkd_status_title in ('Gemini yanıtladı', 'DKDai yanıt verdi', 'dkd_gemini_answered', 'dkd_ai_answered');

update public.dkd_support_threads
set dkd_ai_last_issue_text = 'DKDai Yanıtladı'
where dkd_ai_last_issue_text in ('Gemini yanıtladı', 'DKDai yanıt verdi', 'dkd_gemini_answered', 'dkd_ai_answered');

commit;
