-- DKD Lootonia notification recovery
-- Amaç: GitHub APK / Edge Function deploy sonrası bozulan sipariş havuzu bildirimlerini tekrar çalışır hale getirmek.
-- Güvenli kapsam:
-- 1) Push token tablosunda expo_push_token / token kolon uyumluluğunu sağlar.
-- 2) dkd_upsert_push_token RPC fonksiyonunu APK/standalone/dev-client fark etmeyecek şekilde yeniden kurar.
-- 3) dkd_courier_job_push_target_tokens RPC fonksiyonunu eski/yeni token şemasını okuyacak şekilde yeniden kurar.
-- 4) Audit tekrar denemelerini engelleyen eski pending/failed durumunu temizlemeye gerek kalmadan yeni Edge Function retry yapabilir.

begin;

create table if not exists public.dkd_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  expo_push_token text,
  token text,
  platform text,
  app_mode text,
  device_name text,
  is_active boolean not null default true,
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.dkd_push_tokens add column if not exists expo_push_token text;
alter table public.dkd_push_tokens add column if not exists token text;
alter table public.dkd_push_tokens add column if not exists platform text;
alter table public.dkd_push_tokens add column if not exists app_mode text;
alter table public.dkd_push_tokens add column if not exists device_name text;
alter table public.dkd_push_tokens add column if not exists is_active boolean not null default true;
alter table public.dkd_push_tokens add column if not exists last_seen_at timestamptz not null default timezone('utc', now());
alter table public.dkd_push_tokens add column if not exists created_at timestamptz not null default timezone('utc', now());
alter table public.dkd_push_tokens add column if not exists updated_at timestamptz not null default timezone('utc', now());

update public.dkd_push_tokens
   set expo_push_token = coalesce(nullif(trim(expo_push_token), ''), nullif(trim(token), '')),
       token = coalesce(nullif(trim(token), ''), nullif(trim(expo_push_token), '')),
       is_active = coalesce(is_active, true),
       updated_at = timezone('utc', now())
 where nullif(trim(coalesce(expo_push_token, '')), '') is null
    or nullif(trim(coalesce(token, '')), '') is null;

create index if not exists dkd_push_tokens_user_idx on public.dkd_push_tokens(user_id);
create index if not exists dkd_push_tokens_active_idx on public.dkd_push_tokens(is_active);
create unique index if not exists dkd_push_tokens_expo_push_token_unique_idx
  on public.dkd_push_tokens(expo_push_token)
  where expo_push_token is not null;
create unique index if not exists dkd_push_tokens_token_unique_idx
  on public.dkd_push_tokens(token)
  where token is not null;

alter table public.dkd_push_tokens enable row level security;

do $$
begin
  create policy "own push tokens select" on public.dkd_push_tokens
    for select using (auth.uid() = user_id);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "own push tokens insert" on public.dkd_push_tokens
    for insert with check (auth.uid() = user_id);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "own push tokens update" on public.dkd_push_tokens
    for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
exception when duplicate_object then null;
end $$;

create table if not exists public.dkd_courier_push_audit (
  id bigint generated by default as identity primary key,
  job_id bigint not null,
  job_status text not null,
  job_type text null,
  user_id uuid null,
  expo_push_token text not null,
  dkd_push_segment text not null default 'courier_licensed',
  send_status text not null default 'pending',
  send_error text null,
  sent_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists dkd_courier_push_audit_job_token_idx
  on public.dkd_courier_push_audit(job_id, job_status, expo_push_token);
create index if not exists dkd_courier_push_audit_created_idx
  on public.dkd_courier_push_audit(created_at desc);
create index if not exists dkd_courier_push_audit_status_idx
  on public.dkd_courier_push_audit(send_status, created_at desc);

drop function if exists public.dkd_upsert_push_token(text, text, text, text);

create or replace function public.dkd_upsert_push_token(
  dkd_param_token text default null,
  dkd_param_platform text default null,
  dkd_param_app_mode text default null,
  dkd_param_device_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_token_value text := nullif(trim(coalesce(dkd_param_token, '')), '');
  dkd_updated_count_value integer := 0;
begin
  if dkd_user_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_auth_required');
  end if;

  if dkd_token_value is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_token_required');
  end if;

  update public.dkd_push_tokens
     set user_id = dkd_user_id_value,
         expo_push_token = dkd_token_value,
         token = dkd_token_value,
         platform = nullif(trim(coalesce(dkd_param_platform, '')), ''),
         app_mode = nullif(trim(coalesce(dkd_param_app_mode, '')), ''),
         device_name = nullif(trim(coalesce(dkd_param_device_name, '')), ''),
         is_active = true,
         last_seen_at = timezone('utc', now()),
         updated_at = timezone('utc', now())
   where expo_push_token = dkd_token_value
      or token = dkd_token_value;

  get diagnostics dkd_updated_count_value = row_count;

  if dkd_updated_count_value = 0 then
    insert into public.dkd_push_tokens (
      user_id,
      expo_push_token,
      token,
      platform,
      app_mode,
      device_name,
      is_active,
      last_seen_at,
      created_at,
      updated_at
    ) values (
      dkd_user_id_value,
      dkd_token_value,
      dkd_token_value,
      nullif(trim(coalesce(dkd_param_platform, '')), ''),
      nullif(trim(coalesce(dkd_param_app_mode, '')), ''),
      nullif(trim(coalesce(dkd_param_device_name, '')), ''),
      true,
      timezone('utc', now()),
      timezone('utc', now()),
      timezone('utc', now())
    );
  end if;

  return jsonb_build_object('ok', true, 'reason', 'dkd_push_token_upserted');
end;
$$;

grant execute on function public.dkd_upsert_push_token(text, text, text, text) to authenticated, service_role;

drop function if exists public.dkd_disable_push_token(text);

create or replace function public.dkd_disable_push_token(dkd_param_token text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_token_value text := nullif(trim(coalesce(dkd_param_token, '')), '');
begin
  if dkd_user_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_auth_required');
  end if;

  if dkd_token_value is null then
    return jsonb_build_object('ok', true, 'reason', 'dkd_token_empty');
  end if;

  update public.dkd_push_tokens
     set is_active = false,
         updated_at = timezone('utc', now())
   where user_id = dkd_user_id_value
     and (expo_push_token = dkd_token_value or token = dkd_token_value);

  return jsonb_build_object('ok', true, 'reason', 'dkd_push_token_disabled');
end;
$$;

grant execute on function public.dkd_disable_push_token(text) to authenticated, service_role;

drop function if exists public.dkd_courier_job_push_target_tokens();

create or replace function public.dkd_courier_job_push_target_tokens()
returns table(
  user_id uuid,
  expo_push_token text,
  dkd_push_segment text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with dkd_base_tokens as (
    select
      dkd_token_alias.user_id,
      coalesce(
        nullif(trim(coalesce(dkd_token_alias.expo_push_token, '')), ''),
        nullif(trim(coalesce(dkd_token_alias.token, '')), '')
      ) as expo_push_token,
      coalesce(dkd_profile_alias.courier_status, 'none') as courier_status,
      dkd_token_alias.updated_at,
      dkd_token_alias.id
    from public.dkd_push_tokens dkd_token_alias
    left join public.dkd_profiles dkd_profile_alias
      on dkd_profile_alias.user_id = dkd_token_alias.user_id
    where coalesce(dkd_token_alias.is_active, true) = true
  ),
  dkd_ranked_tokens as (
    select
      dkd_base_tokens.user_id,
      dkd_base_tokens.expo_push_token,
      case
        when lower(coalesce(dkd_base_tokens.courier_status, '')) in ('approved', 'active') then 'courier_licensed'
        else 'courier_invite'
      end as dkd_push_segment,
      row_number() over (
        partition by dkd_base_tokens.expo_push_token
        order by
          case when lower(coalesce(dkd_base_tokens.courier_status, '')) in ('approved', 'active') then 0 else 1 end,
          dkd_base_tokens.updated_at desc nulls last,
          dkd_base_tokens.id desc
      ) as dkd_row_rank
    from dkd_base_tokens
    where nullif(trim(coalesce(dkd_base_tokens.expo_push_token, '')), '') is not null
  )
  select
    dkd_ranked_tokens.user_id,
    dkd_ranked_tokens.expo_push_token,
    dkd_ranked_tokens.dkd_push_segment
  from dkd_ranked_tokens
  where dkd_ranked_tokens.dkd_row_rank = 1
  order by dkd_ranked_tokens.dkd_push_segment, dkd_ranked_tokens.expo_push_token;
end;
$$;

revoke all on function public.dkd_courier_job_push_target_tokens() from public;
grant execute on function public.dkd_courier_job_push_target_tokens() to authenticated, service_role;

-- Kırık denemelerden kalan pending/failed audit satırları yeni function tarafından retry edilebilir.
-- Buna rağmen son 24 saatteki pending kayıtları açıkça failed_retry_ready yaparak karışıklığı azaltıyoruz.
update public.dkd_courier_push_audit
   set send_status = 'failed',
       send_error = coalesce(send_error, 'dkd_recovery_retry_ready')
 where send_status = 'pending'
   and created_at > timezone('utc', now()) - interval '24 hours';

commit;
