begin;

create or replace function public.dkd_market_table_column_cast_type_dkd(
  dkd_param_table_name text,
  dkd_param_column_name text
)
returns text
language sql
stable
security definer
set search_path = public
as $dkd_column_cast$
  select
    case
      when dkd_column_table.udt_name = 'uuid' then 'uuid'
      when dkd_column_table.udt_name = 'int8' then 'bigint'
      when dkd_column_table.udt_name = 'int4' then 'integer'
      when dkd_column_table.udt_name = 'int2' then 'smallint'
      when dkd_column_table.udt_name = 'numeric' then 'numeric'
      when dkd_column_table.udt_name = 'float8' then 'double precision'
      when dkd_column_table.udt_name = 'float4' then 'real'
      when dkd_column_table.udt_name = 'bool' then 'boolean'
      when dkd_column_table.udt_name = 'text' then 'text'
      when dkd_column_table.udt_name = 'varchar' then 'text'
      when dkd_column_table.udt_name = 'jsonb' then 'jsonb'
      when dkd_column_table.udt_name = 'json' then 'json'
      when dkd_column_table.udt_name = 'timestamptz' then 'timestamp with time zone'
      when dkd_column_table.udt_name = 'timestamp' then 'timestamp without time zone'
      when dkd_column_table.data_type = 'USER-DEFINED' then format('%I.%I', dkd_column_table.udt_schema, dkd_column_table.udt_name)
      else dkd_column_table.data_type
    end
  from information_schema.columns as dkd_column_table
  where dkd_column_table.table_schema = 'public'
    and dkd_column_table.table_name = dkd_param_table_name
    and dkd_column_table.column_name = dkd_param_column_name
  limit 1;
$dkd_column_cast$;

revoke all on function public.dkd_market_table_column_cast_type_dkd(text, text) from public;
grant execute on function public.dkd_market_table_column_cast_type_dkd(text, text) to authenticated;
grant execute on function public.dkd_market_table_column_cast_type_dkd(text, text) to service_role;

alter table if exists public.dkd_business_product_orders
  add column if not exists unit_price_tl numeric not null default 0,
  add column if not exists total_price_tl numeric not null default 0,
  add column if not exists payment_method text not null default 'token',
  add column if not exists payment_status text not null default 'paid';

create index if not exists dkd_business_product_orders_payment_method_idx
  on public.dkd_business_product_orders(payment_method, created_at desc);

do $dkd_legacy_bootstrap$
declare
  dkd_product_id_cast_type_value text;
begin
  dkd_product_id_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_products', 'id');

  if dkd_product_id_cast_type_value = 'uuid' then
    create table if not exists public.dkd_business_product_legacy_keys (
      product_id uuid primary key references public.dkd_business_products(id) on delete cascade,
      legacy_id bigint generated by default as identity unique,
      created_at timestamptz not null default now()
    );

    insert into public.dkd_business_product_legacy_keys (product_id)
    select dkd_business_product_table.id
    from public.dkd_business_products as dkd_business_product_table
    left join public.dkd_business_product_legacy_keys as dkd_legacy_key_table
      on dkd_legacy_key_table.product_id = dkd_business_product_table.id
    where dkd_legacy_key_table.product_id is null;
  end if;
end;
$dkd_legacy_bootstrap$;

create or replace function public.dkd_business_product_order_cash_on_delivery_dkd(
  dkd_param_product_key text,
  dkd_param_quantity integer default 1,
  dkd_param_delivery_address_text text default null,
  dkd_param_delivery_note text default null,
  dkd_param_delivery_lat numeric default null,
  dkd_param_delivery_lng numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $dkd_cash_order$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_quantity_value integer := greatest(coalesce(dkd_param_quantity, 1), 1);
  dkd_product_key_value text := nullif(trim(coalesce(dkd_param_product_key, '')), '');
  dkd_product_id_cast_type_value text;
  dkd_product_meta_cast_type_value text;
  dkd_product_identity_value text;
  dkd_product_payload_value jsonb := '{}'::jsonb;
  dkd_business_payload_value jsonb := '{}'::jsonb;
  dkd_business_id_value text;
  dkd_unit_price_tl_value numeric := 0;
  dkd_total_price_tl_value numeric := 0;
  dkd_delivery_address_text_value text := nullif(trim(coalesce(dkd_param_delivery_address_text, '')), '');
  dkd_delivery_note_text_value text := nullif(trim(coalesce(dkd_param_delivery_note, '')), '');
  dkd_order_payload_value jsonb;
  dkd_order_id_text_value text := null;
  dkd_insert_column_values text[] := array[]::text[];
  dkd_insert_expression_values text[] := array[]::text[];
  dkd_column_cast_type_value text;
  dkd_insert_sql_value text;
begin
  if dkd_user_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  if to_regclass('public.dkd_business_products') is null then
    return jsonb_build_object('ok', false, 'reason', 'product_table_missing');
  end if;

  if to_regclass('public.dkd_business_product_orders') is null then
    return jsonb_build_object('ok', false, 'reason', 'order_table_missing');
  end if;

  if dkd_product_key_value is null then
    return jsonb_build_object('ok', false, 'reason', 'product_not_found');
  end if;

  dkd_product_id_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_products', 'id');
  dkd_product_meta_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_products', 'meta');

  execute 'select dkd_business_product_table.id::text from public.dkd_business_products as dkd_business_product_table where dkd_business_product_table.id::text = $1 limit 1'
    using dkd_product_key_value
    into dkd_product_identity_value;

  if dkd_product_identity_value is null
     and dkd_product_key_value ~ '^[0-9]+$'
     and dkd_product_id_cast_type_value = 'uuid'
     and to_regclass('public.dkd_business_product_legacy_keys') is not null then
    select dkd_legacy_key_table.product_id::text
      into dkd_product_identity_value
    from public.dkd_business_product_legacy_keys as dkd_legacy_key_table
    where dkd_legacy_key_table.legacy_id = dkd_product_key_value::bigint
    limit 1;
  end if;

  if dkd_product_identity_value is null and dkd_product_meta_cast_type_value is not null then
    execute
      'select dkd_business_product_table.id::text
         from public.dkd_business_products as dkd_business_product_table
        where lower(coalesce(dkd_business_product_table.meta->>''product_key'', '''')) = lower($1)
           or lower(coalesce(dkd_business_product_table.meta->>''token'', '''')) = lower($1)
           or lower(coalesce(dkd_business_product_table.meta->>''slug'', '''')) = lower($1)
        order by dkd_business_product_table.id::text desc
        limit 1'
      using dkd_product_key_value
      into dkd_product_identity_value;
  end if;

  if dkd_product_identity_value is null then
    return jsonb_build_object('ok', false, 'reason', 'product_not_found', 'product_key', dkd_product_key_value);
  end if;

  execute
    'select to_jsonb(dkd_selected_product_value)
       from (
         select *
         from public.dkd_business_products as dkd_business_product_table
         where dkd_business_product_table.id::text = $1
         for update
       ) as dkd_selected_product_value'
    using dkd_product_identity_value
    into dkd_product_payload_value;

  if dkd_product_payload_value is null or dkd_product_payload_value = '{}'::jsonb then
    return jsonb_build_object('ok', false, 'reason', 'product_not_found', 'product_key', dkd_product_key_value);
  end if;

  if coalesce((dkd_product_payload_value->>'is_active')::boolean, true) is not true then
    return jsonb_build_object('ok', false, 'reason', 'product_inactive');
  end if;

  if coalesce(nullif(dkd_product_payload_value->>'stock', '')::integer, 0) < dkd_quantity_value then
    return jsonb_build_object('ok', false, 'reason', 'out_of_stock');
  end if;

  if dkd_delivery_address_text_value is null then
    return jsonb_build_object('ok', false, 'reason', 'delivery_address_required');
  end if;

  dkd_business_id_value := nullif(dkd_product_payload_value->>'business_id', '');

  if dkd_business_id_value is not null and to_regclass('public.dkd_businesses') is not null then
    execute
      'select to_jsonb(dkd_selected_business_value)
         from (
           select *
           from public.dkd_businesses as dkd_business_table
           where dkd_business_table.id::text = $1
           limit 1
         ) as dkd_selected_business_value'
      using dkd_business_id_value
      into dkd_business_payload_value;
  end if;

  dkd_unit_price_tl_value := round(
    greatest(
      coalesce(
        nullif(dkd_product_payload_value->>'price_cash', '')::numeric,
        nullif(dkd_product_payload_value->>'price_token', '')::numeric,
        0
      ),
      0
    ),
    2
  );
  dkd_total_price_tl_value := round(dkd_unit_price_tl_value * dkd_quantity_value, 2);

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id_value)
  on conflict (user_id) do nothing;

  if public.dkd_market_table_column_cast_type_dkd('dkd_business_products', 'updated_at') is not null then
    execute
      'update public.dkd_business_products
          set stock = greatest(coalesce(stock, 0) - $2, 0),
              updated_at = now()
        where id::text = $1'
      using dkd_product_identity_value, dkd_quantity_value;
  else
    execute
      'update public.dkd_business_products
          set stock = greatest(coalesce(stock, 0) - $2, 0)
        where id::text = $1'
      using dkd_product_identity_value, dkd_quantity_value;
  end if;

  dkd_order_payload_value := jsonb_strip_nulls(jsonb_build_object(
    'product_id', dkd_product_identity_value,
    'business_id', dkd_business_id_value,
    'buyer_user_id', dkd_user_id_value::text,
    'user_id', dkd_user_id_value::text,
    'quantity', dkd_quantity_value,
    'unit_price_token', 0,
    'total_price_token', 0,
    'token_spent', 0,
    'unit_price_tl', dkd_unit_price_tl_value,
    'total_price_tl', dkd_total_price_tl_value,
    'payment_method', 'cash_on_delivery',
    'payment_status', 'pending_cash',
    'status', 'cash_on_delivery',
    'currency_code', 'TRY',
    'snapshot', jsonb_strip_nulls(jsonb_build_object(
      'product_title', dkd_product_payload_value->>'title',
      'product_category', dkd_product_payload_value->>'category',
      'business_name', coalesce(dkd_business_payload_value->>'name', 'İşletme'),
      'image_url', dkd_product_payload_value->>'image_url',
      'unit_price_tl', dkd_unit_price_tl_value,
      'total_price_tl', dkd_total_price_tl_value,
      'payment_method', 'cash_on_delivery',
      'payment_status', 'pending_cash',
      'delivery_address_text', dkd_delivery_address_text_value,
      'delivery_note_text', dkd_delivery_note_text_value,
      'delivery_location', case
        when dkd_param_delivery_lat is null or dkd_param_delivery_lng is null then null
        else jsonb_build_object('lat', dkd_param_delivery_lat, 'lng', dkd_param_delivery_lng)
      end
    )),
    'delivery_address_text', dkd_delivery_address_text_value,
    'delivery_note_text', dkd_delivery_note_text_value,
    'delivery_note', dkd_delivery_note_text_value,
    'delivery_lat', dkd_param_delivery_lat,
    'delivery_lng', dkd_param_delivery_lng
  ));

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'product_id');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('product_id');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''product_id'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'business_id');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('business_id');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''business_id'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'buyer_user_id');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('buyer_user_id');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''buyer_user_id'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'user_id');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('user_id');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''user_id'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'quantity');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('quantity');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''quantity'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'unit_price_token');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('unit_price_token');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''unit_price_token'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'total_price_token');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('total_price_token');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''total_price_token'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'token_spent');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('token_spent');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''token_spent'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'unit_price_tl');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('unit_price_tl');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''unit_price_tl'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'total_price_tl');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('total_price_tl');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''total_price_tl'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'payment_method');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('payment_method');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''payment_method'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'payment_status');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('payment_status');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''payment_status'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'status');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('status');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''status'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'currency_code');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('currency_code');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''currency_code'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'snapshot');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('snapshot');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->''snapshot'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'delivery_address_text');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('delivery_address_text');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''delivery_address_text'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'delivery_note_text');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('delivery_note_text');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''delivery_note_text'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'delivery_note');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('delivery_note');
    dkd_insert_expression_values := dkd_insert_expression_values || format('($1->>''delivery_note'')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'delivery_lat');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('delivery_lat');
    dkd_insert_expression_values := dkd_insert_expression_values || format('nullif($1->>''delivery_lat'', '''')::%s', dkd_column_cast_type_value);
  end if;

  dkd_column_cast_type_value := public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'delivery_lng');
  if dkd_column_cast_type_value is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('delivery_lng');
    dkd_insert_expression_values := dkd_insert_expression_values || format('nullif($1->>''delivery_lng'', '''')::%s', dkd_column_cast_type_value);
  end if;

  if public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'created_at') is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('created_at');
    dkd_insert_expression_values := dkd_insert_expression_values || 'now()';
  end if;

  if public.dkd_market_table_column_cast_type_dkd('dkd_business_product_orders', 'updated_at') is not null then
    dkd_insert_column_values := dkd_insert_column_values || quote_ident('updated_at');
    dkd_insert_expression_values := dkd_insert_expression_values || 'now()';
  end if;

  if array_length(dkd_insert_column_values, 1) is null then
    return jsonb_build_object('ok', false, 'reason', 'order_columns_missing');
  end if;

  dkd_insert_sql_value := format(
    'insert into public.dkd_business_product_orders (%s) values (%s) returning id::text',
    array_to_string(dkd_insert_column_values, ', '),
    array_to_string(dkd_insert_expression_values, ', ')
  );

  execute dkd_insert_sql_value
    using dkd_order_payload_value
    into dkd_order_id_text_value;

  return jsonb_build_object(
    'ok', true,
    'order_id', dkd_order_id_text_value,
    'product_id', dkd_product_identity_value,
    'product_key', dkd_product_key_value,
    'product_name', coalesce(dkd_product_payload_value->>'title', 'Ürün'),
    'business_name', coalesce(dkd_business_payload_value->>'name', 'İşletme'),
    'unit_price_tl', dkd_unit_price_tl_value,
    'total_price_tl', dkd_total_price_tl_value,
    'quantity', dkd_quantity_value,
    'currency_code', 'TRY',
    'payment_method', 'cash_on_delivery',
    'payment_status', 'pending_cash',
    'status', 'cash_on_delivery',
    'reward_label', coalesce(dkd_business_payload_value->>'name', 'İşletme') || ' • ' || coalesce(dkd_product_payload_value->>'title', 'Ürün') || ' kapıda nakit ödeme ile sipariş edildi.'
  );
end;
$dkd_cash_order$;

revoke all on function public.dkd_business_product_order_cash_on_delivery_dkd(text, integer, text, text, numeric, numeric) from public;
grant execute on function public.dkd_business_product_order_cash_on_delivery_dkd(text, integer, text, text, numeric, numeric) to authenticated;

commit;
