-- Lootonia v0.2 market + sosyal anahtar düzeltmesi
-- 1) Token Market invalid_kind / invalid_reward_kind onarımı
-- 2) Aynı kartı tekrar ilana çıkarınca duplicate key hatasını engelleme

begin;

create table if not exists public.dkd_market_reward_types (
  id bigint generated by default as identity primary key,
  reward_kind text not null unique,
  title text not null,
  subtitle text,
  resource_target text not null,
  icon_name text not null default 'cube-outline',
  accent_key text not null default 'cyan',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dkd_market_reward_types add column if not exists subtitle text;
alter table public.dkd_market_reward_types add column if not exists resource_target text;
alter table public.dkd_market_reward_types add column if not exists icon_name text not null default 'cube-outline';
alter table public.dkd_market_reward_types add column if not exists accent_key text not null default 'cyan';
alter table public.dkd_market_reward_types add column if not exists is_active boolean not null default true;
alter table public.dkd_market_reward_types add column if not exists updated_at timestamptz not null default now();

insert into public.dkd_market_reward_types (
  reward_kind,
  title,
  subtitle,
  resource_target,
  icon_name,
  accent_key,
  is_active,
  updated_at
)
values
  ('shard', 'Shard', 'Craft ve upgrade kaynağı', 'shards', 'diamond-stone', 'cyan', true, now()),
  ('ticket', 'Boss Bileti', 'Boss giriş hakkı', 'boss_tickets', 'ticket-confirmation-outline', 'purple', true, now()),
  ('energy', 'Enerji', 'Harita ve drop akışı', 'energy', 'lightning-bolt-outline', 'gold', true, now()),
  ('token', 'Token', 'Anlık token ödülü', 'token', 'cash-multiple', 'gold', true, now()),
  ('xp', 'XP', 'Seviye ilerleme puanı', 'xp', 'star-four-points-outline', 'cyan', true, now())
on conflict (reward_kind) do update
set
  title = excluded.title,
  subtitle = excluded.subtitle,
  resource_target = excluded.resource_target,
  icon_name = excluded.icon_name,
  accent_key = excluded.accent_key,
  is_active = excluded.is_active,
  updated_at = now();

create table if not exists public.dkd_market_shop_defs (
  id bigint generated by default as identity primary key,
  pack_key text not null unique,
  title text not null,
  subtitle text,
  description text,
  badge_label text,
  icon_name text not null default 'cube-outline',
  accent_key text not null default 'cyan',
  price_token integer not null default 0,
  reward_kind text not null default 'energy',
  reward_amount integer not null default 1,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dkd_market_shop_defs add column if not exists subtitle text;
alter table public.dkd_market_shop_defs add column if not exists description text;
alter table public.dkd_market_shop_defs add column if not exists badge_label text;
alter table public.dkd_market_shop_defs add column if not exists icon_name text not null default 'cube-outline';
alter table public.dkd_market_shop_defs add column if not exists accent_key text not null default 'cyan';
alter table public.dkd_market_shop_defs add column if not exists price_token integer not null default 0;
alter table public.dkd_market_shop_defs add column if not exists reward_kind text not null default 'energy';
alter table public.dkd_market_shop_defs add column if not exists reward_amount integer not null default 1;
alter table public.dkd_market_shop_defs add column if not exists sort_order integer not null default 100;
alter table public.dkd_market_shop_defs add column if not exists is_active boolean not null default true;
alter table public.dkd_market_shop_defs add column if not exists updated_at timestamptz not null default now();

update public.dkd_market_shop_defs
set reward_kind = case
  when lower(coalesce(reward_kind, '')) in ('shards', 'shard', 'craft', 'upgrade') then 'shard'
  when lower(coalesce(reward_kind, '')) in ('ticket', 'tickets', 'boss_ticket', 'boss_tickets', 'bilet') then 'ticket'
  when lower(coalesce(reward_kind, '')) in ('energy', 'enerji') then 'energy'
  else lower(coalesce(reward_kind, 'energy'))
end,
updated_at = now();

insert into public.dkd_market_shop_defs (
  pack_key,
  title,
  subtitle,
  description,
  badge_label,
  icon_name,
  accent_key,
  price_token,
  reward_kind,
  reward_amount,
  sort_order,
  is_active,
  updated_at
)
values
  ('shard_40', '40 Shard', 'Craft ve kart yükseltme stoğu', 'Özellikle marketten aldığın kartları hızlı güçlendirmek için ideal.', 'Craft', 'diamond-stone', 'cyan', 160, 'shard', 40, 10, true, now()),
  ('ticket_1', '1 Boss Bileti', 'Baskına direkt giriş hakkı', 'Haritadaki boss alanına yeniden hazır girmek için tekli paket.', 'Raid', 'ticket-confirmation-outline', 'purple', 360, 'ticket', 1, 20, true, now()),
  ('energy_5', '5 Enerji', 'Anlık kısa akış takviyesi', 'Harita ve sandık turuna hızla geri dönmek için hızlı enerji yüklemesi.', 'Hızlı', 'lightning-bolt-outline', 'gold', 120, 'energy', 5, 30, true, now()),
  ('energy_10', '10 Enerji', 'Uzun rota için güçlü stok', 'Özellikle yoğun drop turu ve görev akışında daha uzun oynamak için.', 'Pro', 'battery-charging-medium', 'gold', 220, 'energy', 10, 40, true, now())
on conflict (pack_key) do update
set
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  badge_label = excluded.badge_label,
  icon_name = excluded.icon_name,
  accent_key = excluded.accent_key,
  price_token = excluded.price_token,
  reward_kind = excluded.reward_kind,
  reward_amount = excluded.reward_amount,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

drop function if exists public.dkd_market_token_shop_buy(text);
create or replace function public.dkd_market_token_shop_buy(dkd_param_kind text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid;
  dkd_pack public.dkd_market_shop_defs;
  dkd_reward_type public.dkd_market_reward_types;
  dkd_kind_token text := lower(coalesce(trim(dkd_param_kind), ''));
  dkd_token integer := 0;
  dkd_shards integer := 0;
  dkd_tickets integer := 0;
  dkd_energy integer := 0;
  dkd_energy_max integer := 20;
  dkd_energy_updated_at timestamptz := now();
  dkd_xp integer := 0;
  dkd_reward_target text := '';
  dkd_reward_shards integer := 0;
  dkd_reward_tickets integer := 0;
  dkd_reward_energy integer := 0;
  dkd_reward_token integer := 0;
  dkd_reward_xp integer := 0;
  dkd_reward_label text := '';
begin
  dkd_user_id := auth.uid();
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  select *
  into dkd_pack
  from public.dkd_market_shop_defs
  where (
      lower(coalesce(pack_key, '')) = dkd_kind_token
      or id::text = dkd_kind_token
    )
    and coalesce(is_active, false) = true
  order by case when lower(coalesce(pack_key, '')) = dkd_kind_token then 0 else 1 end, id asc
  limit 1;

  if dkd_pack.id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_kind');
  end if;

  select *
  into dkd_reward_type
  from public.dkd_market_reward_types
  where reward_kind = lower(coalesce(dkd_pack.reward_kind, ''))
    and coalesce(is_active, false) = true
  limit 1;

  dkd_reward_target := lower(coalesce(dkd_reward_type.resource_target, ''));

  if dkd_reward_target = '' then
    dkd_reward_target := case lower(coalesce(dkd_pack.reward_kind, ''))
      when 'shard' then 'shards'
      when 'ticket' then 'boss_tickets'
      when 'energy' then 'energy'
      when 'token' then 'token'
      when 'xp' then 'xp'
      else ''
    end;
  end if;

  if dkd_reward_target = 'shards' then
    dkd_reward_shards := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_shards::text || ' shard';
  elsif dkd_reward_target = 'boss_tickets' then
    dkd_reward_tickets := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_tickets::text || ' boss bileti';
  elsif dkd_reward_target = 'energy' then
    dkd_reward_energy := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_energy::text || ' enerji';
  elsif dkd_reward_target = 'token' then
    dkd_reward_token := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_token::text || ' token';
  elsif dkd_reward_target = 'xp' then
    dkd_reward_xp := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_xp::text || ' XP';
  else
    return jsonb_build_object('ok', false, 'reason', 'invalid_resource_target');
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id)
  on conflict (user_id) do nothing;

  select
    coalesce(token, 0),
    coalesce(shards, 0),
    coalesce(boss_tickets, 0),
    coalesce(energy, 0),
    greatest(1, coalesce(energy_max, 20)),
    coalesce(energy_updated_at, now()),
    coalesce(xp, 0)
  into
    dkd_token,
    dkd_shards,
    dkd_tickets,
    dkd_energy,
    dkd_energy_max,
    dkd_energy_updated_at,
    dkd_xp
  from public.dkd_profiles
  where user_id = dkd_user_id
  for update;

  if dkd_token < coalesce(dkd_pack.price_token, 0) then
    return jsonb_build_object('ok', false, 'reason', 'not_enough_token');
  end if;

  if dkd_reward_energy > 0 and dkd_energy >= dkd_energy_max then
    return jsonb_build_object('ok', false, 'reason', 'energy_full');
  end if;

  update public.dkd_profiles
  set
    token = coalesce(token, 0) - coalesce(dkd_pack.price_token, 0) + dkd_reward_token,
    shards = coalesce(shards, 0) + dkd_reward_shards,
    boss_tickets = coalesce(boss_tickets, 0) + dkd_reward_tickets,
    energy = least(greatest(1, coalesce(energy_max, 20)), coalesce(energy, 0) + dkd_reward_energy),
    xp = coalesce(xp, 0) + dkd_reward_xp,
    energy_updated_at = case when dkd_reward_energy > 0 then now() else coalesce(energy_updated_at, now()) end,
    updated_at = now()
  where user_id = dkd_user_id
  returning
    coalesce(token, 0),
    coalesce(shards, 0),
    coalesce(boss_tickets, 0),
    coalesce(energy, 0),
    greatest(1, coalesce(energy_max, 20)),
    coalesce(energy_updated_at, now()),
    coalesce(xp, 0)
  into
    dkd_token,
    dkd_shards,
    dkd_tickets,
    dkd_energy,
    dkd_energy_max,
    dkd_energy_updated_at,
    dkd_xp;

  return jsonb_build_object(
    'ok', true,
    'kind', dkd_pack.pack_key,
    'reward_kind', dkd_pack.reward_kind,
    'reward_amount', dkd_pack.reward_amount,
    'reward_label', dkd_reward_label,
    'spent_token', dkd_pack.price_token,
    'reward_shards', dkd_reward_shards,
    'reward_tickets', dkd_reward_tickets,
    'reward_energy', dkd_reward_energy,
    'reward_token', dkd_reward_token,
    'reward_xp', dkd_reward_xp,
    'token', dkd_token,
    'shards', dkd_shards,
    'boss_tickets', dkd_tickets,
    'energy', dkd_energy,
    'energy_max', dkd_energy_max,
    'energy_updated_at', dkd_energy_updated_at,
    'xp', dkd_xp
  );
end;
$$;

revoke all on function public.dkd_market_token_shop_buy(text) from public;
grant execute on function public.dkd_market_token_shop_buy(text) to authenticated, service_role;

drop function if exists public.dkd_market_list_card(text, integer);
drop function if exists public.dkd_market_list_card(uuid, integer);
drop function if exists public.dkd_market_list_card(bigint, integer);

create or replace function public.dkd_market_list_card(
  dkd_param_user_card_id bigint,
  dkd_param_price_token integer
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid;
  dkd_card_def_id public.dkd_user_cards.card_def_id%TYPE;
  dkd_listing_id bigint;
  dkd_safe_price_token integer;
  dkd_safe_fee_token integer;
  dkd_has_card_def_column boolean := false;
begin
  dkd_user_id := auth.uid();

  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  dkd_safe_price_token := greatest(coalesce(dkd_param_price_token, 0), 1);
  dkd_safe_fee_token := greatest(floor(dkd_safe_price_token * 0.10), 0)::integer;

  select dkd_user_card_table.card_def_id
  into dkd_card_def_id
  from public.dkd_user_cards dkd_user_card_table
  where dkd_user_card_table.id = dkd_param_user_card_id
    and dkd_user_card_table.user_id = dkd_user_id
  limit 1;

  if dkd_card_def_id is null then
    raise exception 'card_not_owned';
  end if;

  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dkd_market_listings'
      and column_name = 'card_def_id'
  )
  into dkd_has_card_def_column;

  select dkd_market_listing_table.id
  into dkd_listing_id
  from public.dkd_market_listings dkd_market_listing_table
  where dkd_market_listing_table.user_card_id = dkd_param_user_card_id
  order by dkd_market_listing_table.id desc
  limit 1;

  if dkd_listing_id is not null then
    if dkd_has_card_def_column then
      execute '
        update public.dkd_market_listings
        set seller_id = $1,
            card_def_id = $2,
            price_token = $3,
            fee_token = $4,
            status = ''active'',
            buyer_id = null,
            sold_at = null,
            cancelled_at = null,
            updated_at = now()
        where id = $5'
      using dkd_user_id, dkd_card_def_id, dkd_safe_price_token, dkd_safe_fee_token, dkd_listing_id;
    else
      update public.dkd_market_listings
      set
        seller_id = dkd_user_id,
        price_token = dkd_safe_price_token,
        fee_token = dkd_safe_fee_token,
        status = 'active',
        buyer_id = null,
        sold_at = null,
        cancelled_at = null,
        updated_at = now()
      where id = dkd_listing_id;
    end if;

    return dkd_listing_id;
  end if;

  if dkd_has_card_def_column then
    execute '
      insert into public.dkd_market_listings
        (seller_id, user_card_id, card_def_id, price_token, fee_token, status)
      values
        ($1, $2, $3, $4, $5, ''active'')
      returning id'
    into dkd_listing_id
    using dkd_user_id, dkd_param_user_card_id, dkd_card_def_id, dkd_safe_price_token, dkd_safe_fee_token;
  else
    insert into public.dkd_market_listings
      (seller_id, user_card_id, price_token, fee_token, status)
    values
      (dkd_user_id, dkd_param_user_card_id, dkd_safe_price_token, dkd_safe_fee_token, 'active')
    returning id into dkd_listing_id;
  end if;

  return dkd_listing_id;
end;
$$;

revoke all on function public.dkd_market_list_card(bigint, integer) from public;
grant execute on function public.dkd_market_list_card(bigint, integer) to authenticated, service_role;

commit;
