-- Lootonia courier push targeting repair
-- Amaç:
-- 1) İşletme + kargo sipariş bildirimlerini sadece kurye lisansı aktif kullanıcılara gerçek sipariş bildirimi olarak göndermek
-- 2) Kurye lisansı olmayan aktif push kullanıcılarına tanıtım bildirimi göndermek
-- 3) Bildirim tekrarlarını denetlemek için audit tablosunu eklemek

create table if not exists public.dkd_courier_push_audit (
  id bigint generated by default as identity primary key,
  job_id bigint not null,
  job_status text not null,
  job_type text null,
  user_id uuid null,
  expo_push_token text not null,
  dkd_push_segment text not null default 'courier_licensed',
  send_status text not null default 'pending',
  send_error text null,
  sent_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists dkd_courier_push_audit_job_token_idx
  on public.dkd_courier_push_audit(job_id, job_status, expo_push_token);

create index if not exists dkd_courier_push_audit_created_idx
  on public.dkd_courier_push_audit(created_at desc);

create or replace function public.dkd_courier_job_push_target_tokens()
returns table(
  user_id uuid,
  expo_push_token text,
  dkd_push_segment text
)
language sql
security definer
set search_path = public
as $$
  with dkd_base_tokens as (
    select
      dkd_token_alias.user_id,
      trim(coalesce(dkd_token_alias.expo_push_token, '')) as expo_push_token,
      coalesce(dkd_profile_alias.courier_status, 'none') as courier_status,
      dkd_token_alias.updated_at,
      dkd_token_alias.id
    from public.dkd_push_tokens dkd_token_alias
    left join public.dkd_profiles dkd_profile_alias
      on dkd_profile_alias.user_id = dkd_token_alias.user_id
    where dkd_token_alias.is_active = true
      and nullif(trim(coalesce(dkd_token_alias.expo_push_token, '')), '') is not null
  ),
  dkd_ranked_tokens as (
    select
      dkd_base_tokens.user_id,
      dkd_base_tokens.expo_push_token,
      case
        when lower(dkd_base_tokens.courier_status) in ('approved', 'active') then 'courier_licensed'
        else 'courier_invite'
      end as dkd_push_segment,
      row_number() over (
        partition by dkd_base_tokens.expo_push_token
        order by
          case when lower(dkd_base_tokens.courier_status) in ('approved', 'active') then 0 else 1 end,
          dkd_base_tokens.updated_at desc nulls last,
          dkd_base_tokens.id desc
      ) as dkd_row_rank
    from dkd_base_tokens
  )
  select
    dkd_ranked_tokens.user_id,
    dkd_ranked_tokens.expo_push_token,
    dkd_ranked_tokens.dkd_push_segment
  from dkd_ranked_tokens
  where dkd_ranked_tokens.dkd_row_rank = 1
  order by dkd_ranked_tokens.dkd_push_segment, dkd_ranked_tokens.expo_push_token;
$$;

revoke all on function public.dkd_courier_job_push_target_tokens() from public;
grant execute on function public.dkd_courier_job_push_target_tokens() to authenticated, service_role;
