import { resolveUnifiedWalletTl, formatWalletTlCompact } from '../../services/walletService';
export default function buildHomeProps({
  mapRef,
  region,
  markerDrops,
  activeDropId,
  handleMapMarkerPress,
  loc,
  trDropType,
  clamp,
  profile,
  energyUI,
  tokenScale,
  formatInt,
  hiddenBossCountToday,
  nextBossReturnText,
  locationError,
  retryLocation,
  recenterToCurrentLocation,
  visibleDrops,
  dockPreview,
  isNear,
  getDropVisual,
  getDropDistanceState,
  etaTextFromDistance,
  openDirections,
  activeTab,
  handleBottomNavChange,
  openDropList,
  openActionMenu,
}) {
  return {
    mapRef,
    region,
    markerDrops: markerDrops || [],
    activeDropId,
    currentLocation: loc || null,
    onMarkerPress: handleMapMarkerPress,
    trDropType,
    clamp,
    profile,
    energyUI,
    tokenScale,
    tokenText: formatInt(Number(profile?.token ?? 0)),
    walletText: formatWalletTlCompact(resolveUnifiedWalletTl(profile || {})),
    hiddenBossCountToday,
    nextBossReturnText,
    locationError,
    retryLocation,
    recenterToCurrentLocation,
    visibleDrops: visibleDrops || [],
    dockPreview: dockPreview || null,
    isNear,
    getDropVisual,
    getDropDistanceState,
    etaTextFromDistance,
    openDirections,
    activeTab,
    onTabChange: handleBottomNavChange,
    onOpenDropList: openDropList,
    onOpenActionMenu: openActionMenu,
    welcomeCardVisible: false,
    tutorialMissionVisible: false,
    onDismissWelcomeCard: () => {},
    onOpenTasksFromGuide: () => handleBottomNavChange?.('tasks'),
  };
}
