-- 002_cards_loot_chests_market_base.sql
-- Lootonia core content schema: cards, loot, chests, market base

create extension if not exists pgcrypto;

create table if not exists public.dkd_card_defs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  series text not null default 'GENERAL',
  rarity text not null default 'common',
  theme text not null default 'core',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.dkd_card_defs add column if not exists name text;
alter table public.dkd_card_defs add column if not exists series text not null default 'GENERAL';
alter table public.dkd_card_defs add column if not exists rarity text not null default 'common';
alter table public.dkd_card_defs add column if not exists theme text not null default 'core';
alter table public.dkd_card_defs add column if not exists is_active boolean not null default true;
alter table public.dkd_card_defs add column if not exists created_at timestamptz not null default now();

alter table public.dkd_card_defs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_card_defs'
      and policyname = 'dkd_card_defs_select_all'
  ) then
    create policy dkd_card_defs_select_all
    on public.dkd_card_defs
    for select
    to authenticated
    using (true);
  end if;
end $$;

create table if not exists public.dkd_loot_entries (
  id bigint generated by default as identity primary key,
  drop_type text not null default 'all',
  rarity text not null default 'common',
  weight numeric not null default 1,
  card_def_id uuid not null references public.dkd_card_defs(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.dkd_loot_entries add column if not exists drop_type text not null default 'all';
alter table public.dkd_loot_entries add column if not exists rarity text not null default 'common';
alter table public.dkd_loot_entries add column if not exists weight numeric not null default 1;
alter table public.dkd_loot_entries add column if not exists card_def_id uuid;
alter table public.dkd_loot_entries add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.dkd_loot_entries'::regclass
      and conname = 'dkd_loot_entries_card_def_id_fkey'
  ) then
    alter table public.dkd_loot_entries
      add constraint dkd_loot_entries_card_def_id_fkey
      foreign key (card_def_id)
      references public.dkd_card_defs(id)
      on delete cascade;
  end if;
end $$;

alter table public.dkd_loot_entries enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_loot_entries'
      and policyname = 'dkd_loot_entries_select_all'
  ) then
    create policy dkd_loot_entries_select_all
    on public.dkd_loot_entries
    for select
    to authenticated
    using (true);
  end if;
end $$;

create table if not exists public.dkd_user_cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  card_def_id uuid not null references public.dkd_card_defs(id) on delete restrict,
  source text not null default 'chest',
  created_at timestamptz not null default now()
);

alter table public.dkd_user_cards add column if not exists user_id uuid;
alter table public.dkd_user_cards add column if not exists card_def_id uuid;
alter table public.dkd_user_cards add column if not exists source text not null default 'chest';
alter table public.dkd_user_cards add column if not exists created_at timestamptz not null default now();

create index if not exists idx_dkd_user_cards_user_id on public.dkd_user_cards(user_id);
create index if not exists idx_dkd_user_cards_card_def_id on public.dkd_user_cards(card_def_id);

alter table public.dkd_user_cards enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_user_cards'
      and policyname = 'dkd_user_cards_select_own'
  ) then
    create policy dkd_user_cards_select_own
    on public.dkd_user_cards
    for select
    to authenticated
    using (auth.uid() = user_id or public.dkd_is_admin());
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_user_cards'
      and policyname = 'dkd_user_cards_insert_own'
  ) then
    create policy dkd_user_cards_insert_own
    on public.dkd_user_cards
    for insert
    to authenticated
    with check (auth.uid() = user_id or public.dkd_is_admin());
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_user_cards'
      and policyname = 'dkd_user_cards_update_own'
  ) then
    create policy dkd_user_cards_update_own
    on public.dkd_user_cards
    for update
    to authenticated
    using (auth.uid() = user_id or public.dkd_is_admin())
    with check (auth.uid() = user_id or public.dkd_is_admin());
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_user_cards'
      and policyname = 'dkd_user_cards_delete_own'
  ) then
    create policy dkd_user_cards_delete_own
    on public.dkd_user_cards
    for delete
    to authenticated
    using (auth.uid() = user_id or public.dkd_is_admin());
  end if;
end $$;

create table if not exists public.dkd_chest_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  drop_id uuid null references public.dkd_drops(id) on delete set null,
  card_def_id uuid null references public.dkd_card_defs(id) on delete set null,
  gained_token integer not null default 0,
  gained_shards integer not null default 0,
  gained_energy integer not null default 0,
  gained_boss_tickets integer not null default 0,
  drop_type text not null default 'map',
  created_at timestamptz not null default now()
);

alter table public.dkd_chest_logs add column if not exists user_id uuid;
alter table public.dkd_chest_logs add column if not exists drop_id uuid;
alter table public.dkd_chest_logs add column if not exists card_def_id uuid;
alter table public.dkd_chest_logs add column if not exists gained_token integer not null default 0;
alter table public.dkd_chest_logs add column if not exists gained_shards integer not null default 0;
alter table public.dkd_chest_logs add column if not exists gained_energy integer not null default 0;
alter table public.dkd_chest_logs add column if not exists gained_boss_tickets integer not null default 0;
alter table public.dkd_chest_logs add column if not exists drop_type text not null default 'map';
alter table public.dkd_chest_logs add column if not exists created_at timestamptz not null default now();

create index if not exists idx_dkd_chest_logs_user_id on public.dkd_chest_logs(user_id);
create index if not exists idx_dkd_chest_logs_created_at on public.dkd_chest_logs(created_at);

alter table public.dkd_chest_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_chest_logs'
      and policyname = 'dkd_chest_logs_select_own'
  ) then
    create policy dkd_chest_logs_select_own
    on public.dkd_chest_logs
    for select
    to authenticated
    using (auth.uid() = user_id or public.dkd_is_admin());
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_chest_logs'
      and policyname = 'dkd_chest_logs_insert_own'
  ) then
    create policy dkd_chest_logs_insert_own
    on public.dkd_chest_logs
    for insert
    to authenticated
    with check (auth.uid() = user_id or public.dkd_is_admin());
  end if;
end $$;

drop view if exists public.dkd_chest_history;
create view public.dkd_chest_history as
select
  dkd_alias_l.id,
  dkd_alias_l.user_id,
  dkd_alias_l.drop_id,
  dkd_alias_l.card_def_id,
  dkd_alias_l.gained_token,
  dkd_alias_l.gained_shards,
  dkd_alias_l.gained_energy,
  dkd_alias_l.gained_boss_tickets,
  dkd_alias_l.drop_type,
  dkd_alias_l.created_at
from public.dkd_chest_logs dkd_alias_l;

grant select on public.dkd_chest_history to authenticated;

create table if not exists public.dkd_market_listings (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references auth.users(id) on delete cascade,
  user_card_id bigint not null references public.dkd_user_cards(id) on delete cascade,
  card_def_id uuid not null references public.dkd_card_defs(id) on delete restrict,
  price_token integer not null,
  status text not null default 'active',
  buyer_id uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dkd_market_listings add column if not exists seller_id uuid;
alter table public.dkd_market_listings add column if not exists user_card_id bigint;
alter table public.dkd_market_listings add column if not exists card_def_id uuid;
alter table public.dkd_market_listings add column if not exists price_token integer;
alter table public.dkd_market_listings add column if not exists status text not null default 'active';
alter table public.dkd_market_listings add column if not exists buyer_id uuid;
alter table public.dkd_market_listings add column if not exists created_at timestamptz not null default now();
alter table public.dkd_market_listings add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_dkd_market_listings_status on public.dkd_market_listings(status);
create index if not exists idx_dkd_market_listings_seller_id on public.dkd_market_listings(seller_id);
create unique index if not exists idx_dkd_market_active_user_card
on public.dkd_market_listings(user_card_id)
where status = 'active';

drop trigger if exists dkd_market_listings_touch_updated_at on public.dkd_market_listings;
create trigger dkd_market_listings_touch_updated_at
before update on public.dkd_market_listings
for each row
execute function public.dkd_touch_updated_at();

alter table public.dkd_market_listings enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_market_listings'
      and policyname = 'dkd_market_listings_select_visible'
  ) then
    create policy dkd_market_listings_select_visible
    on public.dkd_market_listings
    for select
    to authenticated
    using (
      status = 'active'
      or auth.uid() = seller_id
      or auth.uid() = buyer_id
      or public.dkd_is_admin()
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_market_listings'
      and policyname = 'dkd_market_listings_insert_own'
  ) then
    create policy dkd_market_listings_insert_own
    on public.dkd_market_listings
    for insert
    to authenticated
    with check (auth.uid() = seller_id or public.dkd_is_admin());
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_market_listings'
      and policyname = 'dkd_market_listings_update_own'
  ) then
    create policy dkd_market_listings_update_own
    on public.dkd_market_listings
    for update
    to authenticated
    using (auth.uid() = seller_id or public.dkd_is_admin())
    with check (auth.uid() = seller_id or public.dkd_is_admin());
  end if;
end $$;

drop view if exists public.dkd_market_listings_view;
create view public.dkd_market_listings_view as
select
  m.id,
  m.seller_id,
  m.user_card_id,
  m.card_def_id,
  m.price_token,
  m.status,
  m.buyer_id,
  m.created_at,
  dkd_alias_c.name as card_name,
  dkd_alias_c.series as card_series,
  dkd_alias_c.rarity as card_rarity,
  dkd_alias_c.theme as card_theme
from public.dkd_market_listings m
join public.dkd_card_defs dkd_alias_c on dkd_alias_c.id = m.card_def_id;

grant select on public.dkd_market_listings_view to authenticated;

create or replace function public.dkd_issue_drop_code(dkd_param_drop_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_code text;
  dkd_var_expires_at timestamptz;
begin
  if not public.dkd_is_admin() then
    raise exception 'admin_required';
  end if;

  dkd_var_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
  dkd_var_expires_at := now() + interval '12 hours';

  update public.dkd_drops
  set
    current_code = dkd_var_code,
    current_code_expires_at = dkd_var_expires_at,
    updated_at = now()
  where id = dkd_param_drop_id;

  if not found then
    raise exception 'drop_not_found';
  end if;

  return jsonb_build_object(
    'ok', true,
    'drop_id', dkd_param_drop_id,
    'code', dkd_var_code,
    'expires_at', dkd_var_expires_at
  );
end;
$$;

revoke all on function public.dkd_issue_drop_code(uuid) from public;
grant execute on function public.dkd_issue_drop_code(uuid) to authenticated;
