-- 006_rpc_admin_and_courier.sql
-- Lootonia admin kullanici ve kurye gorev RPC'leri

create table if not exists public.dkd_courier_jobs (
  id bigint generated by default as identity primary key,
  title text,
  pickup text,
  dropoff text,
  reward_score integer not null default 12,
  distance_km numeric not null default 1.0,
  eta_min integer not null default 15,
  job_type text not null default 'food',
  is_active boolean not null default true,
  status text not null default 'open',
  assigned_user_id uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dkd_courier_jobs add column if not exists title text;
alter table public.dkd_courier_jobs add column if not exists pickup text;
alter table public.dkd_courier_jobs add column if not exists dropoff text;
alter table public.dkd_courier_jobs add column if not exists reward_score integer not null default 12;
alter table public.dkd_courier_jobs add column if not exists distance_km numeric not null default 1.0;
alter table public.dkd_courier_jobs add column if not exists eta_min integer not null default 15;
alter table public.dkd_courier_jobs add column if not exists job_type text not null default 'food';
alter table public.dkd_courier_jobs add column if not exists is_active boolean not null default true;
alter table public.dkd_courier_jobs add column if not exists status text not null default 'open';
alter table public.dkd_courier_jobs add column if not exists assigned_user_id uuid references auth.users(id) on delete set null;
alter table public.dkd_courier_jobs add column if not exists accepted_at timestamptz;
alter table public.dkd_courier_jobs add column if not exists completed_at timestamptz;
alter table public.dkd_courier_jobs add column if not exists created_at timestamptz not null default now();
alter table public.dkd_courier_jobs add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_dkd_courier_jobs_status on public.dkd_courier_jobs(status);
create index if not exists idx_dkd_courier_jobs_active on public.dkd_courier_jobs(is_active);
create index if not exists idx_dkd_courier_jobs_assigned_user on public.dkd_courier_jobs(assigned_user_id);

drop trigger if exists dkd_courier_jobs_touch_updated_at on public.dkd_courier_jobs;
create trigger dkd_courier_jobs_touch_updated_at
before update on public.dkd_courier_jobs
for each row
execute function public.dkd_touch_updated_at();

create or replace function public.dkd_admin_profiles_list(
  dkd_param_query text default '',
  dkd_param_limit integer default 60
)
returns table (
  user_id uuid,
  email text,
  nickname text,
  avatar_emoji text,
  token integer,
  shards integer,
  boss_tickets integer,
  energy integer,
  energy_max integer,
  xp integer,
  level integer,
  rank_key text,
  courier_status text,
  courier_score integer,
  courier_completed_jobs integer,
  task_state jsonb,
  boss_state jsonb,
  weekly_task_state jsonb,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_var_query text := lower(coalesce(trim(dkd_param_query), ''));
  dkd_var_limit integer := greatest(1, least(coalesce(dkd_param_limit, 60), 200));
begin
  if not public.dkd_is_admin() then
    raise exception 'admin_required';
  end if;

  return query
  select
    dkd_alias_u.id as user_id,
    dkd_alias_u.email::text as email,
    coalesce(dkd_alias_p.nickname, '') as nickname,
    coalesce(dkd_alias_p.avatar_emoji, '⚡') as avatar_emoji,
    coalesce(dkd_alias_p.token, 0) as token,
    coalesce(dkd_alias_p.shards, 0) as shards,
    coalesce(dkd_alias_p.boss_tickets, 0) as boss_tickets,
    coalesce(dkd_alias_p.energy, 100) as energy,
    coalesce(dkd_alias_p.energy_max, 100) as energy_max,
    coalesce(dkd_alias_p.xp, 0) as xp,
    coalesce(dkd_alias_p.level, 1) as level,
    coalesce(dkd_alias_p.rank_key, 'rookie') as rank_key,
    coalesce(dkd_alias_p.courier_status, 'none') as courier_status,
    coalesce(dkd_alias_p.courier_score, 0) as courier_score,
    coalesce(dkd_alias_p.courier_completed_jobs, 0) as courier_completed_jobs,
    coalesce(dkd_alias_p.task_state, '{}'::jsonb) as task_state,
    coalesce(dkd_alias_p.boss_state, '{}'::jsonb) as boss_state,
    coalesce(dkd_alias_p.weekly_task_state, '{}'::jsonb) as weekly_task_state,
    coalesce(dkd_alias_p.created_at, dkd_alias_u.created_at) as created_at,
    coalesce(dkd_alias_p.updated_at, dkd_alias_u.updated_at) as updated_at
  from auth.users dkd_alias_u
  left join public.dkd_profiles dkd_alias_p
    on dkd_alias_p.user_id = dkd_alias_u.id
  where
    dkd_var_query = ''
    or lower(coalesce(dkd_alias_u.email::text, '')) like '%' || dkd_var_query || '%'
    or lower(coalesce(dkd_alias_p.nickname, '')) like '%' || dkd_var_query || '%'
    or dkd_alias_u.id::text like '%' || dkd_var_query || '%'
  order by coalesce(dkd_alias_p.updated_at, dkd_alias_u.updated_at) desc nulls last, dkd_alias_u.created_at desc
  limit dkd_var_limit;
end;
$$;

revoke all on function public.dkd_admin_profiles_list(text, integer) from public;
grant execute on function public.dkd_admin_profiles_list(text, integer) to authenticated;

create or replace function public.dkd_admin_profile_update(
  dkd_param_user_id uuid,
  dkd_param_nickname text default null,
  dkd_param_avatar_emoji text default null,
  dkd_param_token integer default null,
  dkd_param_shards integer default null,
  dkd_param_boss_tickets integer default null,
  dkd_param_energy integer default null,
  dkd_param_energy_max integer default null,
  dkd_param_xp integer default null,
  dkd_param_level integer default null,
  dkd_param_rank_key text default null,
  dkd_param_courier_status text default null,
  dkd_param_courier_score integer default null,
  dkd_param_courier_completed_jobs integer default null,
  dkd_param_task_state jsonb default null,
  dkd_param_boss_state jsonb default null,
  dkd_param_weekly_task_state jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_var_exists boolean := false;
  dkd_var_row public.dkd_profiles%rowtype;
begin
  if not public.dkd_is_admin() then
    raise exception 'admin_required';
  end if;

  if dkd_param_user_id is null then
    raise exception 'user_required';
  end if;

  select exists(select 1 from auth.users where id = dkd_param_user_id)
  into dkd_var_exists;

  if not dkd_var_exists then
    raise exception 'user_not_found';
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_param_user_id)
  on conflict (user_id) do nothing;

  update public.dkd_profiles
  set
    nickname = coalesce(dkd_param_nickname, nickname),
    avatar_emoji = coalesce(nullif(trim(coalesce(dkd_param_avatar_emoji, '')), ''), avatar_emoji),
    token = coalesce(dkd_param_token, token),
    shards = coalesce(dkd_param_shards, shards),
    boss_tickets = coalesce(dkd_param_boss_tickets, boss_tickets),
    energy = least(
      coalesce(dkd_param_energy_max, energy_max),
      greatest(coalesce(dkd_param_energy, energy), 0)
    ),
    energy_max = greatest(coalesce(dkd_param_energy_max, energy_max), 1),
    xp = greatest(coalesce(dkd_param_xp, xp), 0),
    level = greatest(coalesce(dkd_param_level, level), 1),
    rank_key = coalesce(nullif(trim(coalesce(dkd_param_rank_key, '')), ''), rank_key),
    courier_status = coalesce(nullif(trim(coalesce(dkd_param_courier_status, '')), ''), courier_status),
    courier_score = greatest(coalesce(dkd_param_courier_score, courier_score), 0),
    courier_completed_jobs = greatest(coalesce(dkd_param_courier_completed_jobs, courier_completed_jobs), 0),
    task_state = coalesce(dkd_param_task_state, task_state),
    boss_state = coalesce(dkd_param_boss_state, boss_state),
    weekly_task_state = coalesce(dkd_param_weekly_task_state, weekly_task_state),
    updated_at = now()
  where user_id = dkd_param_user_id
  returning *
  into dkd_var_row;

  return jsonb_build_object(
    'ok', true,
    'user_id', dkd_var_row.user_id,
    'level', dkd_var_row.level,
    'xp', dkd_var_row.xp,
    'rank_key', dkd_var_row.rank_key,
    'courier_status', dkd_var_row.courier_status,
    'courier_score', dkd_var_row.courier_score,
    'courier_completed_jobs', dkd_var_row.courier_completed_jobs
  );
end;
$$;

revoke all on function public.dkd_admin_profile_update(uuid, text, text, integer, integer, integer, integer, integer, integer, integer, text, text, integer, integer, jsonb, jsonb, jsonb) from public;
grant execute on function public.dkd_admin_profile_update(uuid, text, text, integer, integer, integer, integer, integer, integer, integer, text, text, integer, integer, jsonb, jsonb, jsonb) to authenticated;

create or replace function public.dkd_admin_courier_jobs_list()
returns table (
  id bigint,
  title text,
  pickup text,
  dropoff text,
  reward_score integer,
  distance_km numeric,
  eta_min integer,
  job_type text,
  is_active boolean,
  status text,
  assigned_user_id uuid,
  accepted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.dkd_is_admin() then
    raise exception 'admin_required';
  end if;

  return query
  select
    j.id,
    j.title,
    j.pickup,
    j.dropoff,
    coalesce(j.reward_score, 0),
    coalesce(j.distance_km, 0),
    coalesce(j.eta_min, 0),
    coalesce(j.job_type, 'food'),
    coalesce(j.is_active, true),
    coalesce(j.status, 'open'),
    j.assigned_user_id,
    j.accepted_at,
    j.completed_at,
    j.created_at,
    j.updated_at
  from public.dkd_courier_jobs j
  order by j.id desc;
end;
$$;

revoke all on function public.dkd_admin_courier_jobs_list() from public;
grant execute on function public.dkd_admin_courier_jobs_list() to authenticated;

create or replace function public.dkd_admin_courier_job_upsert(
  dkd_param_id bigint default null,
  dkd_param_title text default null,
  dkd_param_pickup text default null,
  dkd_param_dropoff text default null,
  dkd_param_reward_score integer default null,
  dkd_param_distance_km numeric default null,
  dkd_param_eta_min integer default null,
  dkd_param_job_type text default null,
  dkd_param_is_active boolean default true
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_id bigint;
begin
  if not public.dkd_is_admin() then
    raise exception 'admin_required';
  end if;

  if coalesce(nullif(trim(coalesce(dkd_param_title, '')), ''), '') = '' then
    raise exception 'title_required';
  end if;

  if dkd_param_id is null then
    insert into public.dkd_courier_jobs (
      title,
      pickup,
      dropoff,
      reward_score,
      distance_km,
      eta_min,
      job_type,
      is_active,
      status
    )
    values (
      trim(dkd_param_title),
      nullif(trim(coalesce(dkd_param_pickup, '')), ''),
      nullif(trim(coalesce(dkd_param_dropoff, '')), ''),
      greatest(coalesce(dkd_param_reward_score, 12), 0),
      greatest(coalesce(dkd_param_distance_km, 1), 0),
      greatest(coalesce(dkd_param_eta_min, 15), 0),
      coalesce(nullif(trim(coalesce(dkd_param_job_type, '')), ''), 'food'),
      coalesce(dkd_param_is_active, true),
      'open'
    )
    returning id into dkd_var_id;
  else
    update public.dkd_courier_jobs
    set
      title = trim(dkd_param_title),
      pickup = nullif(trim(coalesce(dkd_param_pickup, '')), ''),
      dropoff = nullif(trim(coalesce(dkd_param_dropoff, '')), ''),
      reward_score = greatest(coalesce(dkd_param_reward_score, reward_score), 0),
      distance_km = greatest(coalesce(dkd_param_distance_km, distance_km), 0),
      eta_min = greatest(coalesce(dkd_param_eta_min, eta_min), 0),
      job_type = coalesce(nullif(trim(coalesce(dkd_param_job_type, '')), ''), job_type),
      is_active = coalesce(dkd_param_is_active, is_active),
      updated_at = now()
    where id = dkd_param_id
    returning id into dkd_var_id;

    if dkd_var_id is null then
      raise exception 'job_not_found';
    end if;
  end if;

  return dkd_var_id;
end;
$$;

revoke all on function public.dkd_admin_courier_job_upsert(bigint, text, text, text, integer, numeric, integer, text, boolean) from public;
grant execute on function public.dkd_admin_courier_job_upsert(bigint, text, text, text, integer, numeric, integer, text, boolean) to authenticated;

create or replace function public.dkd_admin_courier_job_delete(dkd_param_job_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.dkd_is_admin() then
    raise exception 'admin_required';
  end if;

  delete from public.dkd_courier_jobs
  where id = dkd_param_job_id;

  if not found then
    raise exception 'job_not_found';
  end if;

  return dkd_param_job_id;
end;
$$;

revoke all on function public.dkd_admin_courier_job_delete(bigint) from public;
grant execute on function public.dkd_admin_courier_job_delete(bigint) to authenticated;

create or replace function public.dkd_courier_jobs_for_me()
returns table (
  id bigint,
  title text,
  pickup text,
  dropoff text,
  reward_score integer,
  distance_km numeric,
  eta_min integer,
  job_type text,
  is_active boolean,
  status text,
  assigned_user_id uuid,
  accepted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_user_id uuid;
  dkd_var_courier_status text;
begin
  dkd_var_user_id := auth.uid();
  if dkd_var_user_id is null then
    raise exception 'auth_required';
  end if;

  select coalesce(courier_status, 'none')
  into dkd_var_courier_status
  from public.dkd_profiles
  where user_id = dkd_var_user_id
  limit 1;

  if coalesce(dkd_var_courier_status, 'none') <> 'approved' then
    return;
  end if;

  return query
  select
    j.id,
    j.title,
    j.pickup,
    j.dropoff,
    coalesce(j.reward_score, 0),
    coalesce(j.distance_km, 0),
    coalesce(j.eta_min, 0),
    coalesce(j.job_type, 'food'),
    coalesce(j.is_active, true),
    coalesce(j.status, 'open'),
    j.assigned_user_id,
    j.accepted_at,
    j.completed_at,
    j.created_at,
    j.updated_at
  from public.dkd_courier_jobs j
  where coalesce(j.is_active, true) = true
    and (
      coalesce(j.status, 'open') = 'open'
      or j.assigned_user_id = dkd_var_user_id
    )
  order by
    case
      when j.assigned_user_id = dkd_var_user_id and coalesce(j.status, 'open') = 'accepted' then 0
      when coalesce(j.status, 'open') = 'open' then 1
      when j.assigned_user_id = dkd_var_user_id and coalesce(j.status, 'open') = 'completed' then 2
      else 3
    end,
    j.created_at desc;
end;
$$;

revoke all on function public.dkd_courier_jobs_for_me() from public;
grant execute on function public.dkd_courier_jobs_for_me() to authenticated;

create or replace function public.dkd_courier_job_accept(dkd_param_job_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_user_id uuid;
  dkd_var_courier_status text;
  dkd_var_status text;
  dkd_var_assigned_user_id uuid;
begin
  dkd_var_user_id := auth.uid();
  if dkd_var_user_id is null then
    raise exception 'auth_required';
  end if;

  select coalesce(courier_status, 'none')
  into dkd_var_courier_status
  from public.dkd_profiles
  where user_id = dkd_var_user_id
  limit 1;

  if coalesce(dkd_var_courier_status, 'none') <> 'approved' then
    raise exception 'courier_not_approved';
  end if;

  select status, assigned_user_id
  into dkd_var_status, dkd_var_assigned_user_id
  from public.dkd_courier_jobs
  where id = dkd_param_job_id
    and coalesce(is_active, true) = true
  for update;

  if dkd_var_status is null then
    raise exception 'job_not_found';
  end if;

  if dkd_var_status = 'completed' then
    raise exception 'job_completed';
  end if;

  if dkd_var_status = 'accepted' and dkd_var_assigned_user_id = dkd_var_user_id then
    return jsonb_build_object('ok', true, 'status', 'accepted', 'job_id', dkd_param_job_id);
  end if;

  if dkd_var_status = 'accepted' and dkd_var_assigned_user_id is distinct from dkd_var_user_id then
    raise exception 'job_already_taken';
  end if;

  update public.dkd_courier_jobs
  set
    status = 'accepted',
    assigned_user_id = dkd_var_user_id,
    accepted_at = now(),
    updated_at = now()
  where id = dkd_param_job_id;

  return jsonb_build_object('ok', true, 'status', 'accepted', 'job_id', dkd_param_job_id);
end;
$$;

revoke all on function public.dkd_courier_job_accept(bigint) from public;
grant execute on function public.dkd_courier_job_accept(bigint) to authenticated;

create or replace function public.dkd_courier_job_complete(dkd_param_job_id bigint)
returns table (
  courier_score integer,
  courier_completed_jobs integer,
  token integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_user_id uuid;
  dkd_var_reward_score integer;
  dkd_var_status text;
  dkd_var_assigned_user_id uuid;
  dkd_var_token_reward integer;
begin
  dkd_var_user_id := auth.uid();
  if dkd_var_user_id is null then
    raise exception 'auth_required';
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_var_user_id)
  on conflict (user_id) do nothing;

  select
    coalesce(reward_score, 0),
    coalesce(status, 'open'),
    assigned_user_id
  into
    dkd_var_reward_score,
    dkd_var_status,
    dkd_var_assigned_user_id
  from public.dkd_courier_jobs
  where id = dkd_param_job_id
    and coalesce(is_active, true) = true
  for update;

  if dkd_var_assigned_user_id is null then
    raise exception 'job_not_found';
  end if;

  if dkd_var_assigned_user_id <> dkd_var_user_id then
    raise exception 'job_not_owned';
  end if;

  if dkd_var_status = 'completed' then
    return query
    select
      coalesce(dkd_alias_p.courier_score, 0),
      coalesce(dkd_alias_p.courier_completed_jobs, 0),
      coalesce(dkd_alias_p.token, 0)
    from public.dkd_profiles dkd_alias_p
    where dkd_alias_p.user_id = dkd_var_user_id
    limit 1;
    return;
  end if;

  if dkd_var_status <> 'accepted' then
    raise exception 'job_not_accepted';
  end if;

  dkd_var_token_reward := greatest(dkd_var_reward_score * 4, 10);

  update public.dkd_courier_jobs
  set
    status = 'completed',
    completed_at = now(),
    updated_at = now()
  where id = dkd_param_job_id;

  update public.dkd_profiles
  set
    courier_score = coalesce(courier_score, 0) + dkd_var_reward_score,
    courier_completed_jobs = coalesce(courier_completed_jobs, 0) + 1,
    token = coalesce(token, 0) + dkd_var_token_reward,
    updated_at = now()
  where user_id = dkd_var_user_id;

  return query
  select
    coalesce(dkd_alias_p.courier_score, 0),
    coalesce(dkd_alias_p.courier_completed_jobs, 0),
    coalesce(dkd_alias_p.token, 0)
  from public.dkd_profiles dkd_alias_p
  where dkd_alias_p.user_id = dkd_var_user_id
  limit 1;
end;
$$;

revoke all on function public.dkd_courier_job_complete(bigint) from public;
grant execute on function public.dkd_courier_job_complete(bigint) to authenticated;
