begin;

create table if not exists public.dkd_announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  sender_label text not null default 'DrabornEagle',
  starts_at timestamptz not null default now(),
  expires_at timestamptz null,
  is_active boolean not null default true,
  created_by uuid null,
  created_at timestamptz not null default now()
);

create index if not exists idx_dkd_announcements_active
  on public.dkd_announcements (is_active, starts_at desc);

create index if not exists idx_dkd_announcements_expires
  on public.dkd_announcements (expires_at);

create or replace function public.dkd_admin_broadcast_create(
  dkd_param_title text,
  dkd_param_body text,
  dkd_param_sender_label text default 'DrabornEagle',
  dkd_param_minutes integer default 120
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_user_id uuid;
  dkd_var_id bigint;
  dkd_var_minutes integer;
begin
  dkd_var_user_id := auth.uid();
  if dkd_var_user_id is null then
    raise exception 'auth_required';
  end if;

  if coalesce(public.dkd_is_admin(), false) is not true then
    raise exception 'admin_required';
  end if;

  if char_length(trim(coalesce(dkd_param_title, ''))) < 3 then
    raise exception 'title_too_short';
  end if;

  if char_length(trim(coalesce(dkd_param_body, ''))) < 6 then
    raise exception 'body_too_short';
  end if;

  dkd_var_minutes := greatest(5, least(coalesce(dkd_param_minutes, 120), 10080));

  insert into public.dkd_announcements (
    title,
    body,
    sender_label,
    starts_at,
    expires_at,
    is_active,
    created_by,
    created_at
  ) values (
    trim(dkd_param_title),
    trim(dkd_param_body),
    coalesce(nullif(trim(dkd_param_sender_label), ''), 'DrabornEagle'),
    now(),
    now() + make_interval(mins => dkd_var_minutes),
    true,
    dkd_var_user_id,
    now()
  )
  returning id into dkd_var_id;

  return dkd_var_id;
end;
$$;

revoke all on function public.dkd_admin_broadcast_create(text, text, text, integer) from public;
grant execute on function public.dkd_admin_broadcast_create(text, text, text, integer) to authenticated;

create or replace function public.dkd_get_active_announcements(
  dkd_param_limit integer default 5
)
returns table (
  id bigint,
  title text,
  body text,
  sender_label text,
  created_at timestamptz,
  starts_at timestamptz,
  expires_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select dkd_alias_a.id,
         dkd_alias_a.title,
         dkd_alias_a.body,
         dkd_alias_a.sender_label,
         dkd_alias_a.created_at,
         dkd_alias_a.starts_at,
         dkd_alias_a.expires_at
  from public.dkd_announcements dkd_alias_a
  where dkd_alias_a.is_active = true
    and dkd_alias_a.starts_at <= now()
    and (dkd_alias_a.expires_at is null or dkd_alias_a.expires_at > now())
  order by dkd_alias_a.id desc
  limit greatest(1, least(coalesce(dkd_param_limit, 5), 50));
$$;

revoke all on function public.dkd_get_active_announcements(integer) from public;
grant execute on function public.dkd_get_active_announcements(integer) to authenticated;

commit;
