create extension if not exists pgcrypto;

create table if not exists public.dkd_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  expo_push_token text not null unique,
  platform text,
  app_mode text,
  device_name text,
  is_active boolean not null default true,
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists dkd_push_tokens_user_idx on public.dkd_push_tokens(user_id);
create index if not exists dkd_push_tokens_active_idx on public.dkd_push_tokens(is_active);

alter table public.dkd_push_tokens enable row level security;

do $$ begin
  create policy "own push tokens select" on public.dkd_push_tokens
    for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "own push tokens insert" on public.dkd_push_tokens
    for insert with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "own push tokens update" on public.dkd_push_tokens
    for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "own push tokens delete" on public.dkd_push_tokens
    for delete using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.dkd_admin_broadcasts (
  id bigint generated by default as identity primary key,
  sender_name text not null default 'DrabornEagle',
  title text not null,
  body text not null,
  sent_by uuid not null,
  delivery_mode text not null default 'expo_push',
  status text not null default 'pending',
  total_targets integer not null default 0,
  total_sent integer not null default 0,
  total_failed integer not null default 0,
  last_error text,
  created_at timestamptz not null default timezone('utc', now()),
  sent_at timestamptz
);

alter table public.dkd_admin_broadcasts enable row level security;

do $$ begin
  create policy "admin broadcast deny direct" on public.dkd_admin_broadcasts
    for all using (false) with check (false);
exception when duplicate_object then null; end $$;

create or replace function public.dkd_upsert_push_token(
  dkd_param_token text,
  dkd_param_platform text default null,
  dkd_param_app_mode text default null,
  dkd_param_device_name text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_uid uuid := auth.uid();
  dkd_var_token text := nullif(trim(coalesce(dkd_param_token, '')), '');
begin
  if dkd_var_uid is null then
    raise exception 'auth_required';
  end if;
  if dkd_var_token is null then
    raise exception 'token_required';
  end if;

  insert into public.dkd_push_tokens (user_id, expo_push_token, platform, app_mode, device_name, is_active, last_seen_at, updated_at)
  values (dkd_var_uid, dkd_var_token, nullif(trim(coalesce(dkd_param_platform, '')), ''), nullif(trim(coalesce(dkd_param_app_mode, '')), ''), nullif(trim(coalesce(dkd_param_device_name, '')), ''), true, timezone('utc', now()), timezone('utc', now()))
  on conflict (expo_push_token)
  do update set
    user_id = excluded.user_id,
    platform = excluded.platform,
    app_mode = excluded.app_mode,
    device_name = excluded.device_name,
    is_active = true,
    last_seen_at = timezone('utc', now()),
    updated_at = timezone('utc', now());
end;
$$;

grant execute on function public.dkd_upsert_push_token(text, text, text, text) to authenticated;

create or replace function public.dkd_disable_push_token(dkd_param_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_uid uuid := auth.uid();
begin
  if dkd_var_uid is null then
    raise exception 'auth_required';
  end if;

  update public.dkd_push_tokens
     set is_active = false,
         updated_at = timezone('utc', now())
   where user_id = dkd_var_uid
     and expo_push_token = trim(coalesce(dkd_param_token, ''));
end;
$$;

grant execute on function public.dkd_disable_push_token(text) to authenticated;

create or replace function public.dkd_admin_queue_broadcast(
  dkd_param_title text,
  dkd_param_body text,
  dkd_param_sender_name text default 'DrabornEagle'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_uid uuid := auth.uid();
  dkd_var_id bigint;
begin
  if dkd_var_uid is null then
    raise exception 'auth_required';
  end if;
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'admin_required';
  end if;
  if nullif(trim(coalesce(dkd_param_title, '')), '') is null then
    raise exception 'title_required';
  end if;
  if nullif(trim(coalesce(dkd_param_body, '')), '') is null then
    raise exception 'body_required';
  end if;

  insert into public.dkd_admin_broadcasts(sender_name, title, body, sent_by)
  values (
    coalesce(nullif(trim(coalesce(dkd_param_sender_name, '')), ''), 'DrabornEagle'),
    trim(dkd_param_title),
    trim(dkd_param_body),
    dkd_var_uid
  )
  returning id into dkd_var_id;

  return dkd_var_id;
end;
$$;

grant execute on function public.dkd_admin_queue_broadcast(text, text, text) to authenticated;

create or replace function public.dkd_admin_list_active_push_tokens()
returns table(expo_push_token text)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'auth_required';
  end if;
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'admin_required';
  end if;

  return query
  select dkd_alias_t.expo_push_token
    from public.dkd_push_tokens dkd_alias_t
   where dkd_alias_t.is_active = true
     and dkd_alias_t.expo_push_token is not null
   order by dkd_alias_t.id desc;
end;
$$;

grant execute on function public.dkd_admin_list_active_push_tokens() to authenticated;

create or replace function public.dkd_admin_complete_broadcast(
  dkd_param_broadcast_id bigint,
  dkd_param_total_targets integer,
  dkd_param_total_sent integer,
  dkd_param_total_failed integer,
  dkd_param_last_error text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'auth_required';
  end if;
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'admin_required';
  end if;

  update public.dkd_admin_broadcasts
     set total_targets = greatest(0, coalesce(dkd_param_total_targets, 0)),
         total_sent = greatest(0, coalesce(dkd_param_total_sent, 0)),
         total_failed = greatest(0, coalesce(dkd_param_total_failed, 0)),
         status = case when coalesce(dkd_param_total_failed, 0) > 0 then 'partial' else 'sent' end,
         sent_at = timezone('utc', now()),
         last_error = nullif(trim(coalesce(dkd_param_last_error, '')), '')
   where id = dkd_param_broadcast_id;
end;
$$;

grant execute on function public.dkd_admin_complete_broadcast(bigint, integer, integer, integer, text) to authenticated;
