-- Lootonia Social Core 4
-- Ally_ID + arkadaşlık + direkt mesaj sistemi

create sequence if not exists public.dkd_ally_id_seq start with 100001 increment by 1;

alter table public.dkd_profiles add column if not exists ally_id bigint;
alter table public.dkd_profiles add column if not exists social_status text not null default 'online';
alter table public.dkd_profiles add column if not exists social_last_seen_at timestamptz not null default now();

update public.dkd_profiles
set ally_id = nextval('public.dkd_ally_id_seq')
where ally_id is null;

select setval(
  'public.dkd_ally_id_seq',
  greatest(100001, coalesce((select max(ally_id) from public.dkd_profiles), 100001)),
  true
);

alter table public.dkd_profiles alter column ally_id set default nextval('public.dkd_ally_id_seq');
create unique index if not exists idx_dkd_profiles_ally_id on public.dkd_profiles(ally_id);
create index if not exists idx_dkd_profiles_nickname_lower on public.dkd_profiles((lower(coalesce(nickname, ''))));
create index if not exists idx_dkd_profiles_social_last_seen on public.dkd_profiles(social_last_seen_at desc);

create table if not exists public.dkd_friend_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.dkd_profiles(user_id) on delete cascade,
  addressee_id uuid not null references public.dkd_profiles(user_id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint dkd_friend_requests_not_self check (requester_id <> addressee_id),
  constraint dkd_friend_requests_status check (status in ('pending', 'accepted', 'rejected', 'canceled'))
);

create index if not exists idx_dkd_friend_requests_requester on public.dkd_friend_requests(requester_id, created_at desc);
create index if not exists idx_dkd_friend_requests_addressee on public.dkd_friend_requests(addressee_id, created_at desc);
create unique index if not exists uq_dkd_friend_requests_pending_pair on public.dkd_friend_requests(requester_id, addressee_id) where status = 'pending';

create table if not exists public.dkd_friendships (
  id bigint generated by default as identity primary key,
  user_low uuid not null references public.dkd_profiles(user_id) on delete cascade,
  user_high uuid not null references public.dkd_profiles(user_id) on delete cascade,
  created_by uuid references public.dkd_profiles(user_id) on delete set null,
  created_at timestamptz not null default now(),
  constraint dkd_friendships_order check (user_low <> user_high)
);

create unique index if not exists uq_dkd_friendships_pair on public.dkd_friendships(user_low, user_high);
create index if not exists idx_dkd_friendships_user_low on public.dkd_friendships(user_low, created_at desc);
create index if not exists idx_dkd_friendships_user_high on public.dkd_friendships(user_high, created_at desc);

create table if not exists public.dkd_dm_threads (
  id uuid primary key default gen_random_uuid(),
  friendship_id bigint not null unique references public.dkd_friendships(id) on delete cascade,
  last_message_text text,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_dkd_dm_threads_last_message_at on public.dkd_dm_threads(last_message_at desc nulls last);

drop trigger if exists trg_dkd_dm_threads_updated_at on public.dkd_dm_threads;
create trigger trg_dkd_dm_threads_updated_at
before update on public.dkd_dm_threads
for each row
execute function public.dkd_touch_updated_at();

create table if not exists public.dkd_dm_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.dkd_dm_threads(id) on delete cascade,
  sender_id uuid not null references public.dkd_profiles(user_id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  seen_at timestamptz,
  constraint dkd_dm_messages_body_len check (char_length(trim(body)) between 1 and 600)
);

create index if not exists idx_dkd_dm_messages_thread_created on public.dkd_dm_messages(thread_id, created_at desc);
create index if not exists idx_dkd_dm_messages_seen on public.dkd_dm_messages(thread_id, seen_at);

alter table public.dkd_friend_requests enable row level security;
alter table public.dkd_friendships enable row level security;
alter table public.dkd_dm_threads enable row level security;
alter table public.dkd_dm_messages enable row level security;

drop policy if exists dkd_friend_requests_select_own on public.dkd_friend_requests;
create policy dkd_friend_requests_select_own
on public.dkd_friend_requests
for select to authenticated
using (auth.uid() = requester_id or auth.uid() = addressee_id);

drop policy if exists dkd_friendships_select_own on public.dkd_friendships;
create policy dkd_friendships_select_own
on public.dkd_friendships
for select to authenticated
using (auth.uid() = user_low or auth.uid() = user_high);

drop policy if exists dkd_dm_threads_select_own on public.dkd_dm_threads;
create policy dkd_dm_threads_select_own
on public.dkd_dm_threads
for select to authenticated
using (
  exists (
    select 1
    from public.dkd_friendships dkd_alias_f
    where dkd_alias_f.id = friendship_id
      and (dkd_alias_f.user_low = auth.uid() or dkd_alias_f.user_high = auth.uid())
  )
);

drop policy if exists dkd_dm_messages_select_own on public.dkd_dm_messages;
create policy dkd_dm_messages_select_own
on public.dkd_dm_messages
for select to authenticated
using (
  exists (
    select 1
    from public.dkd_dm_threads dkd_alias_t
    join public.dkd_friendships dkd_alias_f on dkd_alias_f.id = dkd_alias_t.friendship_id
    where dkd_alias_t.id = thread_id
      and (dkd_alias_f.user_low = auth.uid() or dkd_alias_f.user_high = auth.uid())
  )
);

create or replace function public.dkd_social_touch_presence()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return;
  end if;

  insert into public.dkd_profiles (user_id)
  values (auth.uid())
  on conflict (user_id) do update
    set social_last_seen_at = now();

  update public.dkd_profiles
  set social_last_seen_at = now(),
      social_status = 'online'
  where user_id = auth.uid();
end;
$$;

revoke all on function public.dkd_social_touch_presence() from public;
grant execute on function public.dkd_social_touch_presence() to authenticated;

create or replace function public.dkd_social_search_profiles(dkd_param_query text, dkd_param_limit integer default 12)
returns table (
  user_id uuid,
  ally_id bigint,
  nickname text,
  avatar_emoji text,
  level integer,
  rank_key text,
  is_friend boolean,
  pending_sent boolean,
  pending_received boolean,
  request_id bigint
)
language sql
security definer
set search_path = public
stable
as $$
  with me as (
    select auth.uid() as user_id,
           regexp_replace(coalesce(trim(dkd_param_query), ''), '[^0-9]', '', 'g') as digits,
           lower(coalesce(trim(dkd_param_query), '')) as q
  )
  select
    dkd_alias_p.user_id,
    dkd_alias_p.ally_id,
    coalesce(nullif(trim(dkd_alias_p.nickname), ''), 'Oyuncu') as nickname,
    coalesce(nullif(trim(dkd_alias_p.avatar_emoji), ''), '🦅') as avatar_emoji,
    coalesce(dkd_alias_p.level, 1) as level,
    coalesce(dkd_alias_p.rank_key, 'rookie') as rank_key,
    exists (
      select 1
      from public.dkd_friendships dkd_alias_f
      where (dkd_alias_f.user_low = dkd_alias_p.user_id and dkd_alias_f.user_high = (select user_id from me))
         or (dkd_alias_f.user_high = dkd_alias_p.user_id and dkd_alias_f.user_low = (select user_id from me))
    ) as is_friend,
    exists (
      select 1
      from public.dkd_friend_requests dkd_alias_r
      where dkd_alias_r.requester_id = (select user_id from me)
        and dkd_alias_r.addressee_id = dkd_alias_p.user_id
        and dkd_alias_r.status = 'pending'
    ) as pending_sent,
    exists (
      select 1
      from public.dkd_friend_requests dkd_alias_r
      where dkd_alias_r.requester_id = dkd_alias_p.user_id
        and dkd_alias_r.addressee_id = (select user_id from me)
        and dkd_alias_r.status = 'pending'
    ) as pending_received,
    (
      select dkd_alias_r.id
      from public.dkd_friend_requests dkd_alias_r
      where dkd_alias_r.requester_id = dkd_alias_p.user_id
        and dkd_alias_r.addressee_id = (select user_id from me)
        and dkd_alias_r.status = 'pending'
      order by dkd_alias_r.created_at desc
      limit 1
    ) as request_id
  from public.dkd_profiles dkd_alias_p
  cross join me
  where me.user_id is not null
    and dkd_alias_p.user_id <> me.user_id
    and coalesce(trim(dkd_param_query), '') <> ''
    and (
      (me.digits <> '' and dkd_alias_p.ally_id::text = me.digits)
      or lower(coalesce(dkd_alias_p.nickname, '')) like ('%' || me.q || '%')
    )
  order by
    case when me.digits <> '' and dkd_alias_p.ally_id::text = me.digits then 0 else 1 end,
    case when lower(coalesce(dkd_alias_p.nickname, '')) = me.q then 0 else 1 end,
    dkd_alias_p.level desc,
    dkd_alias_p.updated_at desc
  limit greatest(1, least(coalesce(dkd_param_limit, 12), 20));
$$;

revoke all on function public.dkd_social_search_profiles(text, integer) from public;
grant execute on function public.dkd_social_search_profiles(text, integer) to authenticated;

create or replace function public.dkd_social_send_friend_request(dkd_param_target_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_target uuid := dkd_param_target_user_id;
  dkd_low uuid;
  dkd_high uuid;
  dkd_friendship_id bigint;
  dkd_request_id bigint;
begin
  if dkd_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  insert into public.dkd_profiles (user_id) values (dkd_user_id) on conflict (user_id) do nothing;
  insert into public.dkd_profiles (user_id) values (dkd_target) on conflict (user_id) do nothing;

  if dkd_target is null then
    return jsonb_build_object('ok', false, 'reason', 'target_not_found');
  end if;

  if dkd_target = dkd_user_id then
    return jsonb_build_object('ok', false, 'reason', 'cannot_friend_self');
  end if;

  dkd_low := case when dkd_user_id::text < dkd_target::text then dkd_user_id else dkd_target end;
  dkd_high := case when dkd_user_id::text < dkd_target::text then dkd_target else dkd_user_id end;

  select dkd_alias_f.id into dkd_friendship_id
  from public.dkd_friendships dkd_alias_f
  where dkd_alias_f.user_low = dkd_low and dkd_alias_f.user_high = dkd_high
  limit 1;

  if dkd_friendship_id is not null then
    return jsonb_build_object('ok', false, 'reason', 'friend_exists');
  end if;

  select dkd_alias_r.id into dkd_request_id
  from public.dkd_friend_requests dkd_alias_r
  where dkd_alias_r.requester_id = dkd_target
    and dkd_alias_r.addressee_id = dkd_user_id
    and dkd_alias_r.status = 'pending'
  order by dkd_alias_r.created_at desc
  limit 1;

  if dkd_request_id is not null then
    perform public.dkd_social_respond_friend_request(dkd_request_id, 'accept');
    return jsonb_build_object('ok', true, 'reason', 'accepted_existing');
  end if;

  select dkd_alias_r.id into dkd_request_id
  from public.dkd_friend_requests dkd_alias_r
  where dkd_alias_r.requester_id = dkd_user_id
    and dkd_alias_r.addressee_id = dkd_target
    and dkd_alias_r.status = 'pending'
  order by dkd_alias_r.created_at desc
  limit 1;

  if dkd_request_id is not null then
    return jsonb_build_object('ok', false, 'reason', 'request_exists');
  end if;

  insert into public.dkd_friend_requests (requester_id, addressee_id, status)
  values (dkd_user_id, dkd_target, 'pending');

  return jsonb_build_object('ok', true, 'reason', 'request_sent');
end;
$$;

revoke all on function public.dkd_social_send_friend_request(uuid) from public;
grant execute on function public.dkd_social_send_friend_request(uuid) to authenticated;

create or replace function public.dkd_social_respond_friend_request(dkd_param_request_id bigint, dkd_param_action text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_request public.dkd_friend_requests%rowtype;
  dkd_low uuid;
  dkd_high uuid;
  dkd_friendship_id bigint;
  dkd_thread_id uuid;
  dkd_action text := lower(coalesce(trim(dkd_param_action), 'accept'));
begin
  if dkd_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  select * into dkd_request
  from public.dkd_friend_requests
  where id = dkd_param_request_id
  limit 1;

  if dkd_request.id is null then
    return jsonb_build_object('ok', false, 'reason', 'request_not_found');
  end if;

  if dkd_request.addressee_id <> dkd_user_id then
    return jsonb_build_object('ok', false, 'reason', 'not_request_target');
  end if;

  if dkd_request.status <> 'pending' then
    return jsonb_build_object('ok', false, 'reason', 'request_closed');
  end if;

  if dkd_action not in ('accept', 'reject') then
    return jsonb_build_object('ok', false, 'reason', 'invalid_action');
  end if;

  update public.dkd_friend_requests
  set status = case when dkd_action = 'accept' then 'accepted' else 'rejected' end,
      responded_at = now()
  where id = dkd_request.id;

  if dkd_action = 'reject' then
    return jsonb_build_object('ok', true, 'reason', 'rejected');
  end if;

  dkd_low := case when dkd_request.requester_id::text < dkd_request.addressee_id::text then dkd_request.requester_id else dkd_request.addressee_id end;
  dkd_high := case when dkd_request.requester_id::text < dkd_request.addressee_id::text then dkd_request.addressee_id else dkd_request.requester_id end;

  insert into public.dkd_friendships (user_low, user_high, created_by)
  values (dkd_low, dkd_high, dkd_user_id)
  on conflict (user_low, user_high) do nothing;

  select id into dkd_friendship_id
  from public.dkd_friendships
  where user_low = dkd_low and user_high = dkd_high
  limit 1;

  insert into public.dkd_dm_threads (friendship_id, last_message_text, last_message_at)
  values (dkd_friendship_id, null, null)
  on conflict (friendship_id) do nothing;

  select id into dkd_thread_id
  from public.dkd_dm_threads
  where friendship_id = dkd_friendship_id
  limit 1;

  update public.dkd_friend_requests
  set status = 'canceled', responded_at = now()
  where requester_id = dkd_request.addressee_id
    and addressee_id = dkd_request.requester_id
    and status = 'pending';

  return jsonb_build_object('ok', true, 'reason', 'accepted', 'thread_id', dkd_thread_id);
end;
$$;

revoke all on function public.dkd_social_respond_friend_request(bigint, text) from public;
grant execute on function public.dkd_social_respond_friend_request(bigint, text) to authenticated;

create or replace function public.dkd_social_remove_friend(dkd_param_friend_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_low uuid;
  dkd_high uuid;
begin
  if dkd_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  if dkd_param_friend_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'target_not_found');
  end if;

  dkd_low := case when dkd_user_id::text < dkd_param_friend_user_id::text then dkd_user_id else dkd_param_friend_user_id end;
  dkd_high := case when dkd_user_id::text < dkd_param_friend_user_id::text then dkd_param_friend_user_id else dkd_user_id end;

  delete from public.dkd_friendships
  where user_low = dkd_low and user_high = dkd_high;

  update public.dkd_friend_requests
  set status = 'canceled', responded_at = now()
  where status = 'pending'
    and (
      (requester_id = dkd_user_id and addressee_id = dkd_param_friend_user_id)
      or (requester_id = dkd_param_friend_user_id and addressee_id = dkd_user_id)
    );

  return jsonb_build_object('ok', true, 'reason', 'removed');
end;
$$;

revoke all on function public.dkd_social_remove_friend(uuid) from public;
grant execute on function public.dkd_social_remove_friend(uuid) to authenticated;

create or replace function public.dkd_social_get_or_create_thread(dkd_param_friend_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_low uuid;
  dkd_high uuid;
  dkd_friendship_id bigint;
  dkd_thread_id uuid;
begin
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  dkd_low := case when dkd_user_id::text < dkd_param_friend_user_id::text then dkd_user_id else dkd_param_friend_user_id end;
  dkd_high := case when dkd_user_id::text < dkd_param_friend_user_id::text then dkd_param_friend_user_id else dkd_user_id end;

  select id into dkd_friendship_id
  from public.dkd_friendships
  where user_low = dkd_low and user_high = dkd_high
  limit 1;

  if dkd_friendship_id is null then
    raise exception 'friendship_not_found';
  end if;

  insert into public.dkd_dm_threads (friendship_id)
  values (dkd_friendship_id)
  on conflict (friendship_id) do nothing;

  select id into dkd_thread_id
  from public.dkd_dm_threads
  where friendship_id = dkd_friendship_id
  limit 1;

  return dkd_thread_id;
end;
$$;

revoke all on function public.dkd_social_get_or_create_thread(uuid) from public;
grant execute on function public.dkd_social_get_or_create_thread(uuid) to authenticated;

create or replace function public.dkd_social_thread_messages(dkd_param_thread_id uuid, dkd_param_limit integer default 80)
returns table (
  id bigint,
  sender_id uuid,
  body text,
  created_at timestamptz,
  seen_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_allowed boolean := false;
begin
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  select exists (
    select 1
    from public.dkd_dm_threads dkd_alias_t
    join public.dkd_friendships dkd_alias_f on dkd_alias_f.id = dkd_alias_t.friendship_id
    where dkd_alias_t.id = dkd_param_thread_id
      and (dkd_alias_f.user_low = dkd_user_id or dkd_alias_f.user_high = dkd_user_id)
  ) into dkd_allowed;

  if not dkd_allowed then
    raise exception 'thread_forbidden';
  end if;

  return query
  select m.id, m.sender_id, m.body, m.created_at, m.seen_at
  from public.dkd_dm_messages m
  where m.thread_id = dkd_param_thread_id
  order by m.created_at desc
  limit greatest(10, least(coalesce(dkd_param_limit, 80), 150));
end;
$$;

revoke all on function public.dkd_social_thread_messages(uuid, integer) from public;
grant execute on function public.dkd_social_thread_messages(uuid, integer) to authenticated;

create or replace function public.dkd_social_send_message(dkd_param_thread_id uuid, dkd_param_body text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_allowed boolean := false;
  dkd_text text := trim(coalesce(dkd_param_body, ''));
begin
  if dkd_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  if dkd_text = '' then
    return jsonb_build_object('ok', false, 'reason', 'message_empty');
  end if;

  select exists (
    select 1
    from public.dkd_dm_threads dkd_alias_t
    join public.dkd_friendships dkd_alias_f on dkd_alias_f.id = dkd_alias_t.friendship_id
    where dkd_alias_t.id = dkd_param_thread_id
      and (dkd_alias_f.user_low = dkd_user_id or dkd_alias_f.user_high = dkd_user_id)
  ) into dkd_allowed;

  if not dkd_allowed then
    return jsonb_build_object('ok', false, 'reason', 'thread_forbidden');
  end if;

  insert into public.dkd_dm_messages (thread_id, sender_id, body)
  values (dkd_param_thread_id, dkd_user_id, dkd_text);

  update public.dkd_dm_threads
  set last_message_text = left(dkd_text, 120),
      last_message_at = now(),
      updated_at = now()
  where id = dkd_param_thread_id;

  update public.dkd_profiles
  set social_last_seen_at = now(),
      social_status = 'online'
  where user_id = dkd_user_id;

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.dkd_social_send_message(uuid, text) from public;
grant execute on function public.dkd_social_send_message(uuid, text) to authenticated;

create or replace function public.dkd_social_mark_thread_seen(dkd_param_thread_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_allowed boolean := false;
  dkd_count integer := 0;
begin
  if dkd_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  select exists (
    select 1
    from public.dkd_dm_threads dkd_alias_t
    join public.dkd_friendships dkd_alias_f on dkd_alias_f.id = dkd_alias_t.friendship_id
    where dkd_alias_t.id = dkd_param_thread_id
      and (dkd_alias_f.user_low = dkd_user_id or dkd_alias_f.user_high = dkd_user_id)
  ) into dkd_allowed;

  if not dkd_allowed then
    return jsonb_build_object('ok', false, 'reason', 'thread_forbidden');
  end if;

  update public.dkd_dm_messages
  set seen_at = now()
  where thread_id = dkd_param_thread_id
    and sender_id <> dkd_user_id
    and seen_at is null;

  get diagnostics dkd_count = row_count;

  return jsonb_build_object('ok', true, 'updated', dkd_count);
end;
$$;

revoke all on function public.dkd_social_mark_thread_seen(uuid) from public;
grant execute on function public.dkd_social_mark_thread_seen(uuid) to authenticated;

create or replace function public.dkd_social_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_payload jsonb;
begin
  if dkd_user_id is null then
    return jsonb_build_object(
      'myProfile', null,
      'friends', '[]'::jsonb,
      'incoming', '[]'::jsonb,
      'outgoing', '[]'::jsonb
    );
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id)
  on conflict (user_id) do nothing;

  update public.dkd_profiles
  set social_last_seen_at = now(),
      social_status = 'online'
  where user_id = dkd_user_id;

  with my_profile as (
    select dkd_alias_p.user_id, dkd_alias_p.ally_id, coalesce(nullif(trim(dkd_alias_p.nickname), ''), 'Oyuncu') as nickname, coalesce(nullif(trim(dkd_alias_p.avatar_emoji), ''), '🦅') as avatar_emoji, coalesce(dkd_alias_p.level, 1) as level, coalesce(dkd_alias_p.rank_key, 'rookie') as rank_key
    from public.dkd_profiles dkd_alias_p
    where dkd_alias_p.user_id = dkd_user_id
    limit 1
  ),
  friends as (
    select
      dkd_alias_f.id as friendship_id,
      othedkd_profile_row.user_id,
      other.ally_id,
      coalesce(nullif(trim(other.nickname), ''), 'Oyuncu') as nickname,
      coalesce(nullif(trim(other.avatar_emoji), ''), '🦅') as avatar_emoji,
      coalesce(other.level, 1) as level,
      coalesce(other.rank_key, 'rookie') as rank_key,
      dkd_alias_t.id as thread_id,
      dkd_alias_t.last_message_text,
      dkd_alias_t.last_message_at,
      dkd_alias_f.created_at as friend_since,
      coalesce((
        select count(*)::integer
        from public.dkd_dm_messages m
        where m.thread_id = dkd_alias_t.id
          and m.sender_id <> dkd_user_id
          and m.seen_at is null
      ), 0) as unread_count
    from public.dkd_friendships dkd_alias_f
    join public.dkd_profiles other on othedkd_profile_row.user_id = case when dkd_alias_f.user_low = dkd_user_id then dkd_alias_f.user_high else dkd_alias_f.user_low end
    left join public.dkd_dm_threads dkd_alias_t on dkd_alias_t.friendship_id = dkd_alias_f.id
    where dkd_alias_f.user_low = dkd_user_id or dkd_alias_f.user_high = dkd_user_id
    order by coalesce(dkd_alias_t.last_message_at, dkd_alias_f.created_at) desc, other.nickname asc
  ),
  incoming as (
    select
      dkd_alias_r.id as request_id,
      sendedkd_profile_row.user_id,
      sender.ally_id,
      coalesce(nullif(trim(sender.nickname), ''), 'Oyuncu') as nickname,
      coalesce(nullif(trim(sender.avatar_emoji), ''), '🦅') as avatar_emoji,
      coalesce(sender.level, 1) as level,
      coalesce(sender.rank_key, 'rookie') as rank_key,
      dkd_alias_r.created_at
    from public.dkd_friend_requests dkd_alias_r
    join public.dkd_profiles sender on sendedkd_profile_row.user_id = dkd_alias_r.requester_id
    where dkd_alias_r.addressee_id = dkd_user_id
      and dkd_alias_r.status = 'pending'
    order by dkd_alias_r.created_at desc
  ),
  outgoing as (
    select
      dkd_alias_r.id as request_id,
      receivedkd_profile_row.user_id,
      receiver.ally_id,
      coalesce(nullif(trim(receiver.nickname), ''), 'Oyuncu') as nickname,
      coalesce(nullif(trim(receiver.avatar_emoji), ''), '🦅') as avatar_emoji,
      coalesce(receiver.level, 1) as level,
      coalesce(receiver.rank_key, 'rookie') as rank_key,
      dkd_alias_r.created_at
    from public.dkd_friend_requests dkd_alias_r
    join public.dkd_profiles receiver on receivedkd_profile_row.user_id = dkd_alias_r.addressee_id
    where dkd_alias_r.requester_id = dkd_user_id
      and dkd_alias_r.status = 'pending'
    order by dkd_alias_r.created_at desc
  )
  select jsonb_build_object(
    'myProfile', coalesce((select to_jsonb(my_profile) from my_profile), 'null'::jsonb),
    'friends', coalesce((select jsonb_agg(to_jsonb(friends)) from friends), '[]'::jsonb),
    'incoming', coalesce((select jsonb_agg(to_jsonb(incoming)) from incoming), '[]'::jsonb),
    'outgoing', coalesce((select jsonb_agg(to_jsonb(outgoing)) from outgoing), '[]'::jsonb)
  ) into dkd_payload;

  return coalesce(dkd_payload, jsonb_build_object(
    'myProfile', null,
    'friends', '[]'::jsonb,
    'incoming', '[]'::jsonb,
    'outgoing', '[]'::jsonb
  ));
end;
$$;

revoke all on function public.dkd_social_snapshot() from public;
grant execute on function public.dkd_social_snapshot() to authenticated;
