-- Lootonia Market Komuta + reward type routing + local-friendly pack key hardening

create table if not exists public.dkd_market_reward_types (
  id bigint generated by default as identity primary key,
  reward_kind text not null unique,
  title text not null,
  subtitle text,
  resource_target text not null,
  icon_name text not null default 'cube-outline',
  accent_key text not null default 'cyan',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dkd_market_reward_types_resource_target_check check (resource_target in ('shards','boss_tickets','energy','token','xp'))
);

insert into public.dkd_market_reward_types (
  reward_kind, title, subtitle, resource_target, icon_name, accent_key, is_active
)
values
  ('shard', 'Shard', 'Craft ve upgrade kaynağı', 'shards', 'diamond-stone', 'cyan', true),
  ('ticket', 'Boss Bileti', 'Boss giriş hakkı', 'boss_tickets', 'ticket-confirmation-outline', 'purple', true),
  ('energy', 'Enerji', 'Harita ve drop akışı', 'energy', 'lightning-bolt-outline', 'gold', true),
  ('token', 'Token', 'Anlık token ödülü', 'token', 'cash-multiple', 'gold', true),
  ('xp', 'XP', 'Seviye ilerleme puanı', 'xp', 'star-four-points-outline', 'cyan', true)
on conflict (reward_kind) do update
set
  title = excluded.title,
  subtitle = excluded.subtitle,
  resource_target = excluded.resource_target,
  icon_name = excluded.icon_name,
  accent_key = excluded.accent_key,
  is_active = excluded.is_active,
  updated_at = now();

alter table public.dkd_market_shop_defs add column if not exists reward_kind text;

create or replace function public.dkd_admin_market_reward_type_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_reward_types jsonb;
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  select coalesce(jsonb_agg(to_jsonb(dkd_reward_row) order by dkd_reward_row.id asc), '[]'::jsonb)
  into dkd_reward_types
  from (
    select id, reward_kind, title, subtitle, resource_target, icon_name, accent_key, is_active
    from public.dkd_market_reward_types
    order by id asc
  ) as dkd_reward_row;

  return jsonb_build_object('reward_types', coalesce(dkd_reward_types, '[]'::jsonb));
end;
$$;

revoke all on function public.dkd_admin_market_reward_type_snapshot() from public;
grant execute on function public.dkd_admin_market_reward_type_snapshot() to authenticated;

create or replace function public.dkd_admin_market_reward_type_upsert(
  dkd_param_id bigint,
  dkd_param_reward_kind text,
  dkd_param_title text,
  dkd_param_subtitle text,
  dkd_param_resource_target text,
  dkd_param_icon_name text,
  dkd_param_accent_key text,
  dkd_param_is_active boolean
)
returns public.dkd_market_reward_types
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_row public.dkd_market_reward_types;
  dkd_reward_kind text := lower(coalesce(trim(dkd_param_reward_kind), ''));
  dkd_resource_target text := lower(coalesce(trim(dkd_param_resource_target), ''));
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;
  if dkd_reward_kind = '' then
    raise exception 'reward_kind_required';
  end if;
  if coalesce(trim(dkd_param_title), '') = '' then
    raise exception 'reward_title_required';
  end if;
  if dkd_resource_target not in ('shards','boss_tickets','energy','token','xp') then
    raise exception 'invalid_resource_target';
  end if;

  if dkd_param_id is null then
    insert into public.dkd_market_reward_types (
      reward_kind, title, subtitle, resource_target, icon_name, accent_key, is_active, updated_at
    ) values (
      dkd_reward_kind,
      trim(dkd_param_title),
      nullif(trim(dkd_param_subtitle), ''),
      dkd_resource_target,
      coalesce(nullif(trim(dkd_param_icon_name), ''), 'cube-outline'),
      coalesce(nullif(trim(dkd_param_accent_key), ''), 'cyan'),
      coalesce(dkd_param_is_active, true),
      now()
    )
    returning * into dkd_row;
  else
    update public.dkd_market_reward_types
    set
      reward_kind = dkd_reward_kind,
      title = trim(dkd_param_title),
      subtitle = nullif(trim(dkd_param_subtitle), ''),
      resource_target = dkd_resource_target,
      icon_name = coalesce(nullif(trim(dkd_param_icon_name), ''), 'cube-outline'),
      accent_key = coalesce(nullif(trim(dkd_param_accent_key), ''), 'cyan'),
      is_active = coalesce(dkd_param_is_active, true),
      updated_at = now()
    where id = dkd_param_id
    returning * into dkd_row;
  end if;

  return dkd_row;
end;
$$;

revoke all on function public.dkd_admin_market_reward_type_upsert(bigint, text, text, text, text, text, text, boolean) from public;
grant execute on function public.dkd_admin_market_reward_type_upsert(bigint, text, text, text, text, text, text, boolean) to authenticated;

create or replace function public.dkd_admin_market_reward_type_delete(dkd_param_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  delete from public.dkd_market_reward_types where id = dkd_param_id;
  return jsonb_build_object('ok', true, 'id', dkd_param_id);
end;
$$;

revoke all on function public.dkd_admin_market_reward_type_delete(bigint) from public;
grant execute on function public.dkd_admin_market_reward_type_delete(bigint) to authenticated;

create or replace function public.dkd_admin_market_command_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_ui jsonb;
  dkd_packs jsonb;
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  select to_jsonb(dkd_row)
  into dkd_ui
  from (
    select hero_kicker, hero_title, hero_subtitle, logic_title, logic_body
    from public.dkd_market_ui_config where id = 1
  ) as dkd_row;

  select coalesce(jsonb_agg(to_jsonb(dkd_pack) order by dkd_pack.sort_order asc, dkd_pack.id asc), '[]'::jsonb)
  into dkd_packs
  from (
    select id, pack_key, title, subtitle, description, badge_label, icon_name, accent_key, price_token, reward_kind, reward_amount, sort_order, is_active
    from public.dkd_market_shop_defs
    order by sort_order asc, id asc
  ) as dkd_pack;

  return jsonb_build_object('ui', coalesce(dkd_ui, '{}'::jsonb), 'packs', coalesce(dkd_packs, '[]'::jsonb));
end;
$$;

revoke all on function public.dkd_admin_market_command_snapshot() from public;
grant execute on function public.dkd_admin_market_command_snapshot() to authenticated;

create or replace function public.dkd_admin_market_shop_upsert(
  dkd_param_id bigint,
  dkd_param_pack_key text,
  dkd_param_title text,
  dkd_param_subtitle text,
  dkd_param_description text,
  dkd_param_badge_label text,
  dkd_param_icon_name text,
  dkd_param_accent_key text,
  dkd_param_price_token integer,
  dkd_param_reward_kind text,
  dkd_param_reward_amount integer,
  dkd_param_sort_order integer,
  dkd_param_is_active boolean
)
returns public.dkd_market_shop_defs
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_row public.dkd_market_shop_defs;
  dkd_reward_kind text := lower(coalesce(trim(dkd_param_reward_kind), ''));
  dkd_pack_key text := lower(coalesce(trim(dkd_param_pack_key), ''));
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;
  if dkd_pack_key = '' then
    raise exception 'pack_key_required';
  end if;
  if coalesce(trim(dkd_param_title), '') = '' then
    raise exception 'title_required';
  end if;
  if not exists (
    select 1 from public.dkd_market_reward_types
    where reward_kind = dkd_reward_kind and is_active = true
  ) then
    raise exception 'invalid_reward_kind';
  end if;

  if dkd_param_id is null then
    insert into public.dkd_market_shop_defs (
      pack_key, title, subtitle, description, badge_label, icon_name, accent_key, price_token, reward_kind, reward_amount, sort_order, is_active, updated_at
    ) values (
      dkd_pack_key,
      trim(dkd_param_title),
      nullif(trim(dkd_param_subtitle), ''),
      nullif(trim(dkd_param_description), ''),
      nullif(trim(dkd_param_badge_label), ''),
      coalesce(nullif(trim(dkd_param_icon_name), ''), 'cube-outline'),
      coalesce(nullif(trim(dkd_param_accent_key), ''), 'cyan'),
      greatest(coalesce(dkd_param_price_token, 0), 0),
      dkd_reward_kind,
      greatest(coalesce(dkd_param_reward_amount, 1), 1),
      coalesce(dkd_param_sort_order, 100),
      coalesce(dkd_param_is_active, true),
      now()
    )
    returning * into dkd_row;
  else
    update public.dkd_market_shop_defs
    set
      pack_key = dkd_pack_key,
      title = trim(dkd_param_title),
      subtitle = nullif(trim(dkd_param_subtitle), ''),
      description = nullif(trim(dkd_param_description), ''),
      badge_label = nullif(trim(dkd_param_badge_label), ''),
      icon_name = coalesce(nullif(trim(dkd_param_icon_name), ''), 'cube-outline'),
      accent_key = coalesce(nullif(trim(dkd_param_accent_key), ''), 'cyan'),
      price_token = greatest(coalesce(dkd_param_price_token, 0), 0),
      reward_kind = dkd_reward_kind,
      reward_amount = greatest(coalesce(dkd_param_reward_amount, 1), 1),
      sort_order = coalesce(dkd_param_sort_order, 100),
      is_active = coalesce(dkd_param_is_active, true),
      updated_at = now()
    where id = dkd_param_id
    returning * into dkd_row;
  end if;

  return dkd_row;
end;
$$;

revoke all on function public.dkd_admin_market_shop_upsert(bigint, text, text, text, text, text, text, text, integer, text, integer, integer, boolean) from public;
grant execute on function public.dkd_admin_market_shop_upsert(bigint, text, text, text, text, text, text, text, integer, text, integer, integer, boolean) to authenticated;

create or replace function public.dkd_market_token_shop_buy(dkd_param_kind text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid;
  dkd_pack public.dkd_market_shop_defs;
  dkd_reward_type public.dkd_market_reward_types;
  dkd_token integer := 0;
  dkd_shards integer := 0;
  dkd_tickets integer := 0;
  dkd_energy integer := 0;
  dkd_energy_max integer := 20;
  dkd_energy_updated_at timestamptz := now();
  dkd_xp integer := 0;
  dkd_reward_shards integer := 0;
  dkd_reward_tickets integer := 0;
  dkd_reward_energy integer := 0;
  dkd_reward_token integer := 0;
  dkd_reward_xp integer := 0;
  dkd_reward_label text := '';
begin
  dkd_user_id := auth.uid();
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  select *
  into dkd_pack
  from public.dkd_market_shop_defs
  where lower(coalesce(pack_key, '')) = lower(coalesce(trim(dkd_param_kind), ''))
    and is_active = true
  limit 1;

  if dkd_pack.id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_kind');
  end if;

  select *
  into dkd_reward_type
  from public.dkd_market_reward_types
  where reward_kind = lower(coalesce(dkd_pack.reward_kind, ''))
    and is_active = true
  limit 1;

  if dkd_reward_type.id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_reward_kind');
  end if;

  if dkd_reward_type.resource_target = 'shards' then
    dkd_reward_shards := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_shards::text || ' shard';
  elsif dkd_reward_type.resource_target = 'boss_tickets' then
    dkd_reward_tickets := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_tickets::text || ' boss bileti';
  elsif dkd_reward_type.resource_target = 'energy' then
    dkd_reward_energy := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_energy::text || ' enerji';
  elsif dkd_reward_type.resource_target = 'token' then
    dkd_reward_token := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_token::text || ' token';
  elsif dkd_reward_type.resource_target = 'xp' then
    dkd_reward_xp := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
    dkd_reward_label := '+' || dkd_reward_xp::text || ' XP';
  else
    return jsonb_build_object('ok', false, 'reason', 'invalid_resource_target');
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id)
  on conflict (user_id) do nothing;

  select
    coalesce(token, 0),
    coalesce(shards, 0),
    coalesce(boss_tickets, 0),
    coalesce(energy, 0),
    greatest(1, coalesce(energy_max, 20)),
    coalesce(energy_updated_at, now()),
    coalesce(xp, 0)
  into
    dkd_token,
    dkd_shards,
    dkd_tickets,
    dkd_energy,
    dkd_energy_max,
    dkd_energy_updated_at,
    dkd_xp
  from public.dkd_profiles
  where user_id = dkd_user_id
  for update;

  if dkd_token < coalesce(dkd_pack.price_token, 0) then
    return jsonb_build_object('ok', false, 'reason', 'not_enough_token');
  end if;

  if dkd_reward_energy > 0 and dkd_energy >= dkd_energy_max then
    return jsonb_build_object('ok', false, 'reason', 'energy_full');
  end if;

  update public.dkd_profiles
  set
    token = coalesce(token, 0) - coalesce(dkd_pack.price_token, 0) + dkd_reward_token,
    shards = coalesce(shards, 0) + dkd_reward_shards,
    boss_tickets = coalesce(boss_tickets, 0) + dkd_reward_tickets,
    energy = least(greatest(1, coalesce(energy_max, 20)), coalesce(energy, 0) + dkd_reward_energy),
    xp = coalesce(xp, 0) + dkd_reward_xp,
    energy_updated_at = case when dkd_reward_energy > 0 then now() else coalesce(energy_updated_at, now()) end,
    updated_at = now()
  where user_id = dkd_user_id
  returning
    coalesce(token, 0),
    coalesce(shards, 0),
    coalesce(boss_tickets, 0),
    coalesce(energy, 0),
    greatest(1, coalesce(energy_max, 20)),
    coalesce(energy_updated_at, now()),
    coalesce(xp, 0)
  into
    dkd_token,
    dkd_shards,
    dkd_tickets,
    dkd_energy,
    dkd_energy_max,
    dkd_energy_updated_at,
    dkd_xp;

  return jsonb_build_object(
    'ok', true,
    'kind', dkd_pack.pack_key,
    'reward_kind', dkd_pack.reward_kind,
    'reward_amount', dkd_pack.reward_amount,
    'reward_label', dkd_reward_label,
    'spent_token', dkd_pack.price_token,
    'reward_shards', dkd_reward_shards,
    'reward_tickets', dkd_reward_tickets,
    'reward_energy', dkd_reward_energy,
    'reward_token', dkd_reward_token,
    'reward_xp', dkd_reward_xp,
    'token', dkd_token,
    'shards', dkd_shards,
    'boss_tickets', dkd_tickets,
    'energy', dkd_energy,
    'energy_max', dkd_energy_max,
    'energy_updated_at', dkd_energy_updated_at,
    'xp', dkd_xp
  );
end;
$$;

revoke all on function public.dkd_market_token_shop_buy(text) from public;
grant execute on function public.dkd_market_token_shop_buy(text) to authenticated;
