-- Lootonia DKD Acil Kurye server-side olay bildirimleri SAFE RERUN
-- Tarih: 2026-04-26
-- Amaç: invalid exception condition hatasını düzelterek server-side Acil Kurye olay bildirimlerini güvenli kurmak.
-- Genel işletme/kargo bildirim hattına dokunmaz; veri silmez.

begin;

-- SAFE RERUN: eski trigger/fonksiyon tanımları varsa temizle, veriye dokunma.
do $$
begin
  if to_regclass('public.dkd_urgent_courier_orders') is not null then
    execute 'drop trigger if exists dkd_urgent_courier_order_event_push_trigger on public.dkd_urgent_courier_orders';
  end if;
  if to_regclass('public.dkd_urgent_courier_messages') is not null then
    execute 'drop trigger if exists dkd_urgent_courier_message_event_push_trigger on public.dkd_urgent_courier_messages';
  end if;
  if to_regclass('public.dkd_urgent_courier_order_items') is not null then
    execute 'drop trigger if exists dkd_urgent_courier_item_price_event_push_trigger on public.dkd_urgent_courier_order_items';
  end if;
end $$;

drop function if exists public.dkd_urgent_courier_test_latest_event_push_dkd(text);
drop function if exists public.dkd_urgent_courier_item_price_event_trigger_dkd();
drop function if exists public.dkd_urgent_courier_message_event_trigger_dkd();
drop function if exists public.dkd_urgent_courier_order_event_trigger_dkd();
drop function if exists public.dkd_urgent_courier_emit_event_push_dkd(uuid, text, uuid, text);
drop function if exists public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid);

-- pg_net Supabase Database Webhook altyapısıdır. Yetki yoksa sorguyu düşürmeden devam eder;
-- bu durumda audit kaydı oluşur ama push gönderimi için extension'ın açık olması gerekir.
do $$
begin
  create extension if not exists pg_net;
exception
  when others then
    null;
end $$;

create or replace function public.dkd_safe_uuid_from_text_dkd(dkd_param_text text)
returns uuid
language plpgsql
immutable
as $$
declare
  dkd_clean_text_value text := nullif(trim(coalesce(dkd_param_text, '')), '');
begin
  if dkd_clean_text_value is null then
    return null;
  end if;
  return dkd_clean_text_value::uuid;
exception
  when invalid_text_representation then
    return null;
end;
$$;

create or replace function public.dkd_safe_numeric_from_text_dkd(dkd_param_text text, dkd_param_fallback numeric default 0)
returns numeric
language plpgsql
immutable
as $$
declare
  dkd_clean_text_value text := nullif(trim(coalesce(dkd_param_text, '')), '');
begin
  if dkd_clean_text_value is null then
    return coalesce(dkd_param_fallback, 0);
  end if;
  return dkd_clean_text_value::numeric;
exception
  when invalid_text_representation then
    return coalesce(dkd_param_fallback, 0);
end;
$$;

create or replace function public.dkd_text_contains_any_dkd(
  dkd_param_text text,
  dkd_param_terms text[]
)
returns boolean
language plpgsql
immutable
as $$
declare
  dkd_text_value text := lower(coalesce(dkd_param_text, ''));
  dkd_term_value text;
begin
  foreach dkd_term_value in array coalesce(dkd_param_terms, array[]::text[]) loop
    if dkd_term_value is not null and position(lower(dkd_term_value) in dkd_text_value) > 0 then
      return true;
    end if;
  end loop;
  return false;
end;
$$;

create table if not exists public.dkd_urgent_courier_push_audit (
  dkd_audit_id bigint generated by default as identity primary key,
  dkd_dedupe_key text not null,
  dkd_event_key text not null,
  dkd_order_id uuid not null,
  dkd_message_id uuid null,
  dkd_target_user_id uuid null,
  expo_push_token text not null,
  dkd_title text not null,
  dkd_body text not null,
  dkd_payload jsonb not null default '{}'::jsonb,
  dkd_send_status text not null default 'pending',
  dkd_send_error text null,
  dkd_created_at timestamptz not null default timezone('utc', now()),
  dkd_sent_at timestamptz null
);

alter table public.dkd_urgent_courier_push_audit enable row level security;
create unique index if not exists dkd_urgent_courier_push_audit_dedupe_unique
  on public.dkd_urgent_courier_push_audit(dkd_dedupe_key);
create index if not exists dkd_urgent_courier_push_audit_order_event_idx
  on public.dkd_urgent_courier_push_audit(dkd_order_id, dkd_event_key, dkd_created_at desc);
create index if not exists dkd_urgent_courier_push_audit_status_idx
  on public.dkd_urgent_courier_push_audit(dkd_send_status, dkd_created_at desc);

grant select, insert, update on public.dkd_urgent_courier_push_audit to service_role;

-- Mevcut fonksiyon varsa güvenli şekilde yeniden kuruyoruz. Bu sürüm sadece direct customer/courier hedeflerini kullanır.
drop function if exists public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid);

create or replace function public.dkd_urgent_courier_push_targets_dkd(
  dkd_param_order_id uuid,
  dkd_param_event_key text,
  dkd_param_message_id uuid default null
)
returns table(
  dkd_target_user_id uuid,
  expo_push_token text,
  dkd_title text,
  dkd_body text,
  dkd_payload jsonb,
  dkd_dedupe_key text
)
language sql
security definer
set search_path = public
as $dkd_push_targets$
  with dkd_order_scope as (
    select
      dkd_order_row.dkd_order_id,
      dkd_order_row.dkd_customer_user_id,
      dkd_order_row.dkd_courier_user_id,
      to_jsonb(dkd_order_row) as dkd_order_json_value,
      coalesce(nullif(trim(to_jsonb(dkd_order_row) ->> 'dkd_customer_full_name'), ''), nullif(trim(to_jsonb(dkd_order_row) ->> 'dkd_customer_name'), ''), 'Müşteri') as dkd_customer_name_value,
      'Kurye'::text as dkd_courier_name_value,
      public.dkd_safe_numeric_from_text_dkd(coalesce(to_jsonb(dkd_order_row) ->> 'dkd_courier_fee_tl', to_jsonb(dkd_order_row) ->> 'courier_fee_tl', '0'), 0) as dkd_courier_fee_value,
      public.dkd_safe_numeric_from_text_dkd(coalesce(to_jsonb(dkd_order_row) ->> 'dkd_product_total_tl', to_jsonb(dkd_order_row) ->> 'product_total_tl', '0'), 0) as dkd_product_total_value
    from public.dkd_urgent_courier_orders dkd_order_row
    where dkd_order_row.dkd_order_id = dkd_param_order_id
  ),
  dkd_message_scope as (
    select
      dkd_message_row.dkd_message_id,
      public.dkd_safe_uuid_from_text_dkd(to_jsonb(dkd_message_row) ->> 'dkd_sender_user_id') as dkd_sender_user_id,
      lower(coalesce(to_jsonb(dkd_message_row) ->> 'dkd_sender_role_key', to_jsonb(dkd_message_row) ->> 'sender_role', '')) as dkd_sender_role_key,
      coalesce(to_jsonb(dkd_message_row) ->> 'dkd_message_text', to_jsonb(dkd_message_row) ->> 'message_text', to_jsonb(dkd_message_row) ->> 'text', 'Yeni mesajın var.') as dkd_message_text
    from public.dkd_urgent_courier_messages dkd_message_row
    where dkd_message_row.dkd_message_id = dkd_param_message_id
  ),
  dkd_message_text_scope as (
    select
      coalesce(nullif(trim(dkd_message_scope.dkd_message_text), ''), 'Yeni mesajın var.') as dkd_message_text_value,
      coalesce(dkd_message_scope.dkd_sender_role_key, '') as dkd_sender_role_key_value,
      dkd_message_scope.dkd_sender_user_id
    from dkd_message_scope
    union all
    select 'Yeni mesajın var.'::text, ''::text, null::uuid
    where not exists (select 1 from dkd_message_scope)
  ),
  dkd_direct_target_scope as (
    select dkd_order_scope.dkd_customer_user_id as dkd_target_user_id, 'dkd_customer'::text as dkd_target_role_key
    from dkd_order_scope
    where dkd_param_event_key in (
      'dkd_urgent_courier_accepted',
      'dkd_urgent_product_total_sent',
      'dkd_urgent_invoice_uploaded',
      'dkd_urgent_items_picked_up',
      'dkd_urgent_delivery_completed'
    )
    union all
    select dkd_order_scope.dkd_courier_user_id as dkd_target_user_id, 'dkd_courier'::text as dkd_target_role_key
    from dkd_order_scope
    where dkd_param_event_key in (
      'dkd_urgent_order_cancelled',
      'dkd_urgent_fee_approved',
      'dkd_urgent_product_total_approved'
    )
      and dkd_order_scope.dkd_courier_user_id is not null
    union all
    select dkd_order_scope.dkd_customer_user_id as dkd_target_user_id, 'dkd_customer'::text as dkd_target_role_key
    from dkd_order_scope
    where dkd_param_event_key in ('dkd_urgent_chat_opened', 'dkd_urgent_auto_message')
    union all
    select dkd_order_scope.dkd_courier_user_id as dkd_target_user_id, 'dkd_courier'::text as dkd_target_role_key
    from dkd_order_scope
    where dkd_param_event_key in ('dkd_urgent_chat_opened', 'dkd_urgent_auto_message')
      and dkd_order_scope.dkd_courier_user_id is not null
    union all
    select dkd_order_scope.dkd_courier_user_id as dkd_target_user_id, 'dkd_courier'::text as dkd_target_role_key
    from dkd_order_scope
    cross join dkd_message_text_scope
    where dkd_param_event_key = 'dkd_urgent_message_sent'
      and dkd_order_scope.dkd_courier_user_id is not null
      and (
        dkd_message_text_scope.dkd_sender_role_key_value in ('dkd_customer', 'customer', 'musteri', 'müşteri')
        or dkd_message_text_scope.dkd_sender_user_id = dkd_order_scope.dkd_customer_user_id
      )
    union all
    select dkd_order_scope.dkd_customer_user_id as dkd_target_user_id, 'dkd_customer'::text as dkd_target_role_key
    from dkd_order_scope
    cross join dkd_message_text_scope
    where dkd_param_event_key = 'dkd_urgent_message_sent'
      and (
        dkd_message_text_scope.dkd_sender_role_key_value in ('dkd_courier', 'courier', 'kurye')
        or dkd_message_text_scope.dkd_sender_user_id = dkd_order_scope.dkd_courier_user_id
      )
  ),
  dkd_token_scope as (
    select
      dkd_direct_target_scope.dkd_target_user_id,
      dkd_direct_target_scope.dkd_target_role_key,
      dkd_token_row.expo_push_token,
      row_number() over (
        partition by dkd_token_row.expo_push_token
        order by dkd_token_row.updated_at desc nulls last, dkd_token_row.id desc
      ) as dkd_token_rank
    from dkd_direct_target_scope
    join public.dkd_push_tokens dkd_token_row
      on dkd_token_row.user_id = dkd_direct_target_scope.dkd_target_user_id
     and dkd_token_row.is_active = true
     and nullif(trim(coalesce(dkd_token_row.expo_push_token, '')), '') is not null
    where dkd_direct_target_scope.dkd_target_user_id is not null
  )
  select
    dkd_token_scope.dkd_target_user_id,
    dkd_token_scope.expo_push_token,
    case
      when dkd_param_event_key = 'dkd_urgent_courier_accepted' then 'Kurye Görevi Kabul Etti'
      when dkd_param_event_key = 'dkd_urgent_order_cancelled' then 'Acil Kurye Siparişi İptal Edildi'
      when dkd_param_event_key = 'dkd_urgent_fee_approved' then 'Taşıma Ücreti Onaylandı'
      when dkd_param_event_key = 'dkd_urgent_chat_opened' then 'Acil Kurye Sohbeti Açıldı'
      when dkd_param_event_key = 'dkd_urgent_product_total_sent' then 'Mağaza Ürün Fiyatları Girildi'
      when dkd_param_event_key = 'dkd_urgent_product_total_approved' then 'Ürün Toplamı Onaylandı'
      when dkd_param_event_key = 'dkd_urgent_invoice_uploaded' then 'Fatura Yüklendi'
      when dkd_param_event_key = 'dkd_urgent_items_picked_up' then 'Kurye Ürünleri Aldı'
      when dkd_param_event_key = 'dkd_urgent_delivery_completed' then 'Sipariş Teslim Edildi'
      when dkd_param_event_key = 'dkd_urgent_message_sent' and dkd_token_scope.dkd_target_role_key = 'dkd_courier' then 'Müşteriden Yeni Mesaj'
      when dkd_param_event_key = 'dkd_urgent_message_sent' and dkd_token_scope.dkd_target_role_key = 'dkd_customer' then 'Kuryeden Yeni Mesaj'
      when dkd_param_event_key = 'dkd_urgent_auto_message' then 'Acil Kurye Canlı Güncelleme'
      else 'Acil Kurye'
    end as dkd_title,
    case
      when dkd_param_event_key = 'dkd_urgent_courier_accepted' then concat('Kurye görevi kabul etti ve ', round(dkd_order_scope.dkd_courier_fee_value, 2)::text, ' TL taşıma ücreti teklif etti. Onay bekliyor.')
      when dkd_param_event_key = 'dkd_urgent_order_cancelled' then concat(dkd_order_scope.dkd_customer_name_value, ' Acil Kurye siparişini iptal etti. Bu görev kapatıldı.')
      when dkd_param_event_key = 'dkd_urgent_fee_approved' then concat('Müşteri ', round(dkd_order_scope.dkd_courier_fee_value, 2)::text, ' TL taşıma ücretini onayladı. Alışverişe başlayabilirsin.')
      when dkd_param_event_key = 'dkd_urgent_chat_opened' then 'Acil Kurye canlı sohbeti açıldı. Müşteri ve kurye artık bu sipariş üzerinden mesajlaşabilir.'
      when dkd_param_event_key = 'dkd_urgent_product_total_sent' then concat('Kurye mağaza bazlı ürün fiyatlarını girdi. Genel ürün toplamı: ', round(dkd_order_scope.dkd_product_total_value, 2)::text, ' TL. Müşteri onayı bekleniyor.')
      when dkd_param_event_key = 'dkd_urgent_product_total_approved' then concat('Müşteri ', round(dkd_order_scope.dkd_product_total_value, 2)::text, ' TL ürün toplamını onayladı. Ürünleri satın alabilirsin.')
      when dkd_param_event_key = 'dkd_urgent_invoice_uploaded' then 'Kurye faturayı yükledi. Fatura görselini sipariş detayından kontrol edebilirsin.'
      when dkd_param_event_key = 'dkd_urgent_items_picked_up' then 'Kurye ürünleri teslim aldı ve teslimat adresine doğru yola çıktı.'
      when dkd_param_event_key = 'dkd_urgent_delivery_completed' then 'Kurye siparişi teslim etti. Acil Kurye siparişin tamamlandı.'
      when dkd_param_event_key = 'dkd_urgent_message_sent' and dkd_token_scope.dkd_target_role_key = 'dkd_courier' then concat('Müşteri mesaj gönderdi: ', left(dkd_message_text_scope.dkd_message_text_value, 120))
      when dkd_param_event_key = 'dkd_urgent_message_sent' and dkd_token_scope.dkd_target_role_key = 'dkd_customer' then concat('Kurye mesaj gönderdi: ', left(dkd_message_text_scope.dkd_message_text_value, 120))
      when dkd_param_event_key = 'dkd_urgent_auto_message' then left(dkd_message_text_scope.dkd_message_text_value, 140)
      else 'Acil Kurye akışında yeni güncelleme var.'
    end as dkd_body,
    jsonb_build_object(
      'route', 'courier',
      'targetScreen', 'courier',
      'dkd_event_key', dkd_param_event_key,
      'dkd_urgent_courier_order_id', dkd_order_scope.dkd_order_id,
      'dkd_message_id', dkd_param_message_id,
      'dkd_push_segment', 'urgent_courier_server_event'
    ) as dkd_payload,
    concat(
      dkd_param_event_key,
      ':',
      dkd_order_scope.dkd_order_id::text,
      ':',
      coalesce(dkd_param_message_id::text, 'none'),
      ':',
      dkd_token_scope.dkd_target_user_id::text,
      ':',
      md5(dkd_token_scope.expo_push_token)
    ) as dkd_dedupe_key
  from dkd_token_scope
  cross join dkd_order_scope
  cross join dkd_message_text_scope
  where dkd_token_scope.dkd_token_rank = 1;
$dkd_push_targets$;

revoke all on function public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid) from public;
grant execute on function public.dkd_urgent_courier_push_targets_dkd(uuid, text, uuid) to authenticated, service_role;

create or replace function public.dkd_urgent_courier_emit_event_push_dkd(
  dkd_param_order_id uuid,
  dkd_param_event_key text,
  dkd_param_message_id uuid default null,
  dkd_param_dedupe_suffix text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_target_row record;
  dkd_effective_dedupe_key_value text;
  dkd_queued_count_value integer := 0;
  dkd_skipped_count_value integer := 0;
  dkd_request_id_value bigint;
begin
  if dkd_param_order_id is null or nullif(trim(coalesce(dkd_param_event_key, '')), '') is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_invalid_event_payload');
  end if;

  for dkd_target_row in
    select * from public.dkd_urgent_courier_push_targets_dkd(
      dkd_param_order_id,
      dkd_param_event_key,
      dkd_param_message_id
    )
  loop
    dkd_effective_dedupe_key_value := case when nullif(trim(coalesce(dkd_param_dedupe_suffix, '')), '') is null then dkd_target_row.dkd_dedupe_key else dkd_target_row.dkd_dedupe_key || ':' || nullif(trim(dkd_param_dedupe_suffix), '') end;

    insert into public.dkd_urgent_courier_push_audit (
      dkd_dedupe_key,
      dkd_event_key,
      dkd_order_id,
      dkd_message_id,
      dkd_target_user_id,
      expo_push_token,
      dkd_title,
      dkd_body,
      dkd_payload,
      dkd_send_status
    ) values (
      dkd_effective_dedupe_key_value,
      dkd_param_event_key,
      dkd_param_order_id,
      dkd_param_message_id,
      dkd_target_row.dkd_target_user_id,
      dkd_target_row.expo_push_token,
      dkd_target_row.dkd_title,
      dkd_target_row.dkd_body,
      dkd_target_row.dkd_payload,
      'pending'
    ) on conflict (dkd_dedupe_key) do nothing;

    if not found then
      dkd_skipped_count_value := dkd_skipped_count_value + 1;
      continue;
    end if;

    begin
      select net.http_post(
        url := 'https://exp.host/--/api/v2/push/send',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Accept', 'application/json',
          'Accept-Encoding', 'gzip, deflate'
        ),
        body := jsonb_build_object(
          'to', dkd_target_row.expo_push_token,
          'sound', 'default',
          'title', dkd_target_row.dkd_title,
          'body', dkd_target_row.dkd_body,
          'channelId', 'default',
          'data', dkd_target_row.dkd_payload
        ),
        timeout_milliseconds := 1500
      ) into dkd_request_id_value;

      update public.dkd_urgent_courier_push_audit
         set dkd_send_status = 'queued_pg_net',
             dkd_send_error = null,
             dkd_sent_at = timezone('utc', now())
       where dkd_dedupe_key = dkd_effective_dedupe_key_value;

      dkd_queued_count_value := dkd_queued_count_value + 1;
    exception
      when invalid_schema_name or undefined_function then
        update public.dkd_urgent_courier_push_audit
           set dkd_send_status = 'pg_net_missing',
               dkd_send_error = 'pg_net extension açık değil veya net.http_post kullanılamıyor.'
         where dkd_dedupe_key = dkd_effective_dedupe_key_value;
        dkd_skipped_count_value := dkd_skipped_count_value + 1;
      when others then
        update public.dkd_urgent_courier_push_audit
           set dkd_send_status = 'failed',
               dkd_send_error = sqlerrm
         where dkd_dedupe_key = dkd_effective_dedupe_key_value;
        dkd_skipped_count_value := dkd_skipped_count_value + 1;
    end;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'dkd_event_key', dkd_param_event_key,
    'dkd_order_id', dkd_param_order_id,
    'dkd_queued_count', dkd_queued_count_value,
    'dkd_skipped_count', dkd_skipped_count_value
  );
end;
$$;

revoke all on function public.dkd_urgent_courier_emit_event_push_dkd(uuid, text, uuid, text) from public;
grant execute on function public.dkd_urgent_courier_emit_event_push_dkd(uuid, text, uuid, text) to service_role, authenticated;

create or replace function public.dkd_urgent_courier_order_event_trigger_dkd()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_old_json_value jsonb := coalesce(to_jsonb(old), '{}'::jsonb);
  dkd_new_json_value jsonb := coalesce(to_jsonb(new), '{}'::jsonb);
  dkd_old_status_value text := lower(coalesce(dkd_old_json_value ->> 'dkd_status_key', dkd_old_json_value ->> 'status', ''));
  dkd_new_status_value text := lower(coalesce(dkd_new_json_value ->> 'dkd_status_key', dkd_new_json_value ->> 'status', ''));
  dkd_old_courier_user_id_value uuid := public.dkd_safe_uuid_from_text_dkd(dkd_old_json_value ->> 'dkd_courier_user_id');
  dkd_new_courier_user_id_value uuid := public.dkd_safe_uuid_from_text_dkd(dkd_new_json_value ->> 'dkd_courier_user_id');
  dkd_old_fee_value numeric := public.dkd_safe_numeric_from_text_dkd(coalesce(dkd_old_json_value ->> 'dkd_courier_fee_tl', dkd_old_json_value ->> 'courier_fee_tl', '0'), 0);
  dkd_new_fee_value numeric := public.dkd_safe_numeric_from_text_dkd(coalesce(dkd_new_json_value ->> 'dkd_courier_fee_tl', dkd_new_json_value ->> 'courier_fee_tl', '0'), 0);
  dkd_old_product_total_value numeric := public.dkd_safe_numeric_from_text_dkd(coalesce(dkd_old_json_value ->> 'dkd_product_total_tl', dkd_old_json_value ->> 'product_total_tl', '0'), 0);
  dkd_new_product_total_value numeric := public.dkd_safe_numeric_from_text_dkd(coalesce(dkd_new_json_value ->> 'dkd_product_total_tl', dkd_new_json_value ->> 'product_total_tl', '0'), 0);
  dkd_old_invoice_value text := coalesce(dkd_old_json_value ->> 'dkd_invoice_url', dkd_old_json_value ->> 'invoice_url', dkd_old_json_value ->> 'dkd_invoice_image_url', '');
  dkd_new_invoice_value text := coalesce(dkd_new_json_value ->> 'dkd_invoice_url', dkd_new_json_value ->> 'invoice_url', dkd_new_json_value ->> 'dkd_invoice_image_url', '');
  dkd_status_changed_value boolean := false;
begin
  if tg_op <> 'UPDATE' then
    return new;
  end if;

  dkd_status_changed_value := dkd_new_status_value is distinct from dkd_old_status_value;

  if dkd_old_courier_user_id_value is null and dkd_new_courier_user_id_value is not null then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_courier_accepted', null, null);
  end if;

  if dkd_new_courier_user_id_value is not null and dkd_new_fee_value > 0 and dkd_new_fee_value is distinct from dkd_old_fee_value then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_courier_accepted', null, null);
  end if;

  if dkd_status_changed_value and public.dkd_text_contains_any_dkd(dkd_new_status_value, array['cancel', 'iptal']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_order_cancelled', null, null);
  end if;

  if dkd_status_changed_value and public.dkd_text_contains_any_dkd(dkd_new_status_value, array['fee_approved', 'courier_shopping', 'shopping', 'tasima_onay', 'taşıma_onay', 'transport_approved']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_fee_approved', null, null);
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_chat_opened', null, null);
  end if;

  if dkd_new_product_total_value > 0 and dkd_new_product_total_value is distinct from dkd_old_product_total_value then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_product_total_sent', null, null);
  end if;

  if dkd_status_changed_value and public.dkd_text_contains_any_dkd(dkd_new_status_value, array['product_total_approved', 'product_approved', 'urun_onay', 'ürün_onay']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_product_total_approved', null, null);
  end if;

  if nullif(trim(dkd_new_invoice_value), '') is not null and dkd_new_invoice_value is distinct from dkd_old_invoice_value then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_invoice_uploaded', null, null);
  end if;

  if dkd_status_changed_value and public.dkd_text_contains_any_dkd(dkd_new_status_value, array['invoice_uploaded', 'fatura']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_invoice_uploaded', null, null);
  end if;

  if dkd_status_changed_value and public.dkd_text_contains_any_dkd(dkd_new_status_value, array['items_picked', 'picked_up', 'on_the_way', 'delivery_started', 'yola', 'teslim_aldi', 'teslim_aldı']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_items_picked_up', null, null);
  end if;

  if dkd_status_changed_value and public.dkd_text_contains_any_dkd(dkd_new_status_value, array['delivered', 'completed', 'complete', 'done', 'finished', 'teslim_edildi', 'tamam']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_delivery_completed', null, null);
  end if;

  return new;
end;
$$;

create or replace function public.dkd_urgent_courier_message_event_trigger_dkd()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_message_json_value jsonb := coalesce(to_jsonb(new), '{}'::jsonb);
  dkd_message_text_value text := lower(coalesce(dkd_message_json_value ->> 'dkd_message_text', dkd_message_json_value ->> 'message_text', dkd_message_json_value ->> 'text', ''));
  dkd_sender_role_value text := lower(coalesce(dkd_message_json_value ->> 'dkd_sender_role_key', dkd_message_json_value ->> 'sender_role', ''));
  dkd_sender_user_id_value uuid := public.dkd_safe_uuid_from_text_dkd(dkd_message_json_value ->> 'dkd_sender_user_id');
  dkd_customer_user_id_value uuid;
  dkd_courier_user_id_value uuid;
  dkd_effective_sender_role_value text;
  dkd_is_human_message_value boolean := false;
begin
  select dkd_order_row.dkd_customer_user_id, dkd_order_row.dkd_courier_user_id
    into dkd_customer_user_id_value, dkd_courier_user_id_value
    from public.dkd_urgent_courier_orders dkd_order_row
   where dkd_order_row.dkd_order_id = new.dkd_order_id
   limit 1;

  dkd_effective_sender_role_value := dkd_sender_role_value;
  if dkd_effective_sender_role_value = '' and dkd_sender_user_id_value is not null then
    if dkd_sender_user_id_value = dkd_customer_user_id_value then
      dkd_effective_sender_role_value := 'dkd_customer';
    elsif dkd_sender_user_id_value = dkd_courier_user_id_value then
      dkd_effective_sender_role_value := 'dkd_courier';
    end if;
  end if;

  dkd_is_human_message_value := dkd_effective_sender_role_value in ('dkd_customer', 'customer', 'musteri', 'müşteri', 'dkd_courier', 'courier', 'kurye')
    and not public.dkd_text_contains_any_dkd(dkd_message_text_value, array[
      'market siparişi oluşturuldu',
      'taşıma ücreti teklif etti',
      'taşıma ücreti onaylandı',
      'sohbet aktif',
      'ürün toplam',
      'urun toplam',
      'fatura',
      'yola çıktı',
      'yola cikti',
      'teslim edildi',
      'tamamlandı',
      'tamamlandi'
    ]);

  if dkd_is_human_message_value then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_message_sent', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['taşıma ücreti teklif', 'tasima ucreti teklif', 'courier fee', 'kurye taşıma ücreti teklif']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_courier_accepted', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['taşıma ücreti onay', 'tasima ucreti onay']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_fee_approved', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['sohbet aktif', 'canlı sohbet', 'canli sohbet']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_chat_opened', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['mağaza bazlı', 'magaza bazli', 'ürün toplamları', 'urun toplamlari', 'ürün toplamı müşteriye', 'urun toplami musteriy']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_product_total_sent', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['ürün toplamını onay', 'urun toplamini onay', 'ürün toplamı onay', 'urun toplami onay']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_product_total_approved', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['fatura yük', 'fatura yuk', 'fatura eklendi']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_invoice_uploaded', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['ürünleri teslim aldı', 'urunleri teslim aldi', 'yola çıktı', 'yola cikti', 'teslimat adresine doğru']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_items_picked_up', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['siparişi teslim etti', 'siparisi teslim etti', 'sipariş tamamlandı', 'siparis tamamlandi', 'teslim edildi']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_delivery_completed', new.dkd_message_id, null);
  end if;

  if public.dkd_text_contains_any_dkd(dkd_message_text_value, array['iptal etti', 'iptal edildi', 'cancelled', 'canceled']) then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_order_cancelled', new.dkd_message_id, null);
  end if;

  return new;
end;
$$;

create or replace function public.dkd_urgent_courier_item_price_event_trigger_dkd()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_item_json_value jsonb := coalesce(to_jsonb(new), '{}'::jsonb);
  dkd_product_total_value numeric := public.dkd_safe_numeric_from_text_dkd(coalesce(dkd_item_json_value ->> 'dkd_product_total_tl', dkd_item_json_value ->> 'product_total_tl', '0'), 0);
  dkd_item_id_text_value text := coalesce(dkd_item_json_value ->> 'dkd_item_id', dkd_item_json_value ->> 'id', md5(dkd_item_json_value::text));
begin
  if dkd_product_total_value > 0 then
    perform public.dkd_urgent_courier_emit_event_push_dkd(new.dkd_order_id, 'dkd_urgent_product_total_sent', null, 'store_price_' || coalesce(dkd_item_id_text_value, 'unknown'));
  end if;

  return new;
end;
$$;

do $$
begin
  if to_regclass('public.dkd_urgent_courier_orders') is not null then
    execute 'alter table public.dkd_urgent_courier_orders replica identity full';
    execute 'drop trigger if exists dkd_urgent_courier_order_event_push_trigger on public.dkd_urgent_courier_orders';
    execute 'create trigger dkd_urgent_courier_order_event_push_trigger after update on public.dkd_urgent_courier_orders for each row execute function public.dkd_urgent_courier_order_event_trigger_dkd()';
  end if;

  if to_regclass('public.dkd_urgent_courier_messages') is not null then
    execute 'alter table public.dkd_urgent_courier_messages replica identity full';
    execute 'drop trigger if exists dkd_urgent_courier_message_event_push_trigger on public.dkd_urgent_courier_messages';
    execute 'create trigger dkd_urgent_courier_message_event_push_trigger after insert on public.dkd_urgent_courier_messages for each row execute function public.dkd_urgent_courier_message_event_trigger_dkd()';
  end if;

  if to_regclass('public.dkd_urgent_courier_order_items') is not null then
    execute 'alter table public.dkd_urgent_courier_order_items replica identity full';
    execute 'drop trigger if exists dkd_urgent_courier_item_price_event_push_trigger on public.dkd_urgent_courier_order_items';
    execute 'create trigger dkd_urgent_courier_item_price_event_push_trigger after insert or update on public.dkd_urgent_courier_order_items for each row execute function public.dkd_urgent_courier_item_price_event_trigger_dkd()';
  end if;
end $$;

create or replace function public.dkd_urgent_courier_test_latest_event_push_dkd(dkd_param_event_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_order_id_value uuid;
begin
  select dkd_order_row.dkd_order_id
    into dkd_order_id_value
    from public.dkd_urgent_courier_orders dkd_order_row
   order by coalesce((to_jsonb(dkd_order_row) ->> 'dkd_updated_at')::timestamptz, (to_jsonb(dkd_order_row) ->> 'created_at')::timestamptz, timezone('utc', now())) desc
   limit 1;

  if dkd_order_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_no_urgent_order_found');
  end if;

  return public.dkd_urgent_courier_emit_event_push_dkd(dkd_order_id_value, dkd_param_event_key, null, 'manual_test_' || replace(coalesce(dkd_param_event_key, 'event'), 'dkd_', ''));
exception
  when others then
    return jsonb_build_object('ok', false, 'reason', sqlerrm);
end;
$$;

grant execute on function public.dkd_urgent_courier_test_latest_event_push_dkd(text) to authenticated, service_role;

select
  to_regclass('public.dkd_urgent_courier_orders') is not null as dkd_has_urgent_orders_table,
  to_regclass('public.dkd_urgent_courier_messages') is not null as dkd_has_urgent_messages_table,
  to_regclass('public.dkd_urgent_courier_order_items') is not null as dkd_has_urgent_items_table,
  to_regprocedure('public.dkd_urgent_courier_emit_event_push_dkd(uuid,text,uuid,text)') is not null as dkd_has_server_event_push,
  to_regprocedure('public.dkd_urgent_courier_test_latest_event_push_dkd(text)') is not null as dkd_has_manual_test_rpc;

commit;
