create table if not exists public.dkd_market_ui_config (
  id integer primary key,
  hero_kicker text not null default 'TOKEN MAĞAZASI',
  hero_title text not null default 'Anında al, anında kullan',
  hero_subtitle text not null default 'Token cüzdanınla shard, boss bileti ve enerji satın al. Her paket ne işe yaradığını açık şekilde gösterir.',
  logic_title text not null default 'Paket mantığı',
  logic_body text not null default 'Shard = craft ve upgrade, Bilet = boss girişi, Enerji = daha fazla drop ve sandık akışı.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dkd_market_ui_config_singleton check (id = 1)
);

insert into public.dkd_market_ui_config (
  id,
  hero_kicker,
  hero_title,
  hero_subtitle,
  logic_title,
  logic_body
)
values (
  1,
  'TOKEN MAĞAZASI',
  'Anında al, anında kullan',
  'Token cüzdanınla shard, boss bileti ve enerji satın al. Her paket ne işe yaradığını açık şekilde gösterir.',
  'Paket mantığı',
  'Shard = craft ve upgrade, Bilet = boss girişi, Enerji = daha fazla drop ve sandık akışı.'
)
on conflict (id) do nothing;

create table if not exists public.dkd_market_shop_defs (
  id bigint generated by default as identity primary key,
  pack_key text not null unique,
  title text not null,
  subtitle text,
  description text,
  badge_label text,
  icon_name text not null default 'cube-outline',
  accent_key text not null default 'cyan',
  price_token integer not null default 0 check (price_token >= 0),
  reward_kind text not null check (reward_kind in ('shard', 'ticket', 'energy')),
  reward_amount integer not null default 1 check (reward_amount > 0),
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.dkd_market_shop_defs (
  pack_key,
  title,
  subtitle,
  description,
  badge_label,
  icon_name,
  accent_key,
  price_token,
  reward_kind,
  reward_amount,
  sort_order,
  is_active
)
values
  (
    'shard_40',
    '40 Shard',
    'Craft ve kart yükseltme stoğu',
    'Özellikle marketten aldığın kartları hızlı güçlendirmek için ideal.',
    'Craft',
    'diamond-stone',
    'cyan',
    160,
    'shard',
    40,
    10,
    true
  ),
  (
    'ticket_1',
    '1 Boss Bileti',
    'Baskına direkt giriş hakkı',
    'Haritadaki boss alanına yeniden hazır girmek için tekli paket.',
    'Raid',
    'ticket-confirmation-outline',
    'purple',
    360,
    'ticket',
    1,
    20,
    true
  ),
  (
    'energy_5',
    '5 Enerji',
    'Anlık kısa akış takviyesi',
    'Harita ve sandık turuna hızla geri dönmek için hızlı enerji yüklemesi.',
    'Hızlı',
    'lightning-bolt-outline',
    'gold',
    120,
    'energy',
    5,
    30,
    true
  ),
  (
    'energy_10',
    '10 Enerji',
    'Uzun rota için güçlü stok',
    'Özellikle yoğun drop turu ve görev akışında daha uzun oynamak için.',
    'Pro',
    'battery-charging-medium',
    'gold',
    220,
    'energy',
    10,
    40,
    true
  )
on conflict (pack_key) do update
set
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  badge_label = excluded.badge_label,
  icon_name = excluded.icon_name,
  accent_key = excluded.accent_key,
  price_token = excluded.price_token,
  reward_kind = excluded.reward_kind,
  reward_amount = excluded.reward_amount,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

create or replace function public.dkd_market_shop_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_ui jsonb;
  dkd_packs jsonb;
begin
  select to_jsonb(dkd_row)
  into dkd_ui
  from (
    select
      hero_kicker,
      hero_title,
      hero_subtitle,
      logic_title,
      logic_body
    from public.dkd_market_ui_config
    where id = 1
  ) as dkd_row;

  select coalesce(jsonb_agg(to_jsonb(dkd_pack) order by dkd_pack.sort_order asc, dkd_pack.id asc), '[]'::jsonb)
  into dkd_packs
  from (
    select
      id,
      pack_key,
      title,
      subtitle,
      description,
      badge_label,
      icon_name,
      accent_key,
      price_token,
      reward_kind,
      reward_amount,
      sort_order,
      is_active
    from public.dkd_market_shop_defs
    where is_active = true
    order by sort_order asc, id asc
  ) as dkd_pack;

  return jsonb_build_object(
    'ui', coalesce(dkd_ui, '{}'::jsonb),
    'packs', coalesce(dkd_packs, '[]'::jsonb)
  );
end;
$$;

revoke all on function public.dkd_market_shop_snapshot() from public;
grant execute on function public.dkd_market_shop_snapshot() to authenticated;

create or replace function public.dkd_admin_market_command_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_ui jsonb;
  dkd_packs jsonb;
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  select to_jsonb(dkd_row)
  into dkd_ui
  from (
    select
      hero_kicker,
      hero_title,
      hero_subtitle,
      logic_title,
      logic_body
    from public.dkd_market_ui_config
    where id = 1
  ) as dkd_row;

  select coalesce(jsonb_agg(to_jsonb(dkd_pack) order by dkd_pack.sort_order asc, dkd_pack.id asc), '[]'::jsonb)
  into dkd_packs
  from (
    select
      id,
      pack_key,
      title,
      subtitle,
      description,
      badge_label,
      icon_name,
      accent_key,
      price_token,
      reward_kind,
      reward_amount,
      sort_order,
      is_active
    from public.dkd_market_shop_defs
    order by sort_order asc, id asc
  ) as dkd_pack;

  return jsonb_build_object(
    'ui', coalesce(dkd_ui, '{}'::jsonb),
    'packs', coalesce(dkd_packs, '[]'::jsonb)
  );
end;
$$;

revoke all on function public.dkd_admin_market_command_snapshot() from public;
grant execute on function public.dkd_admin_market_command_snapshot() to authenticated;

create or replace function public.dkd_admin_market_ui_save(
  dkd_param_hero_kicker text,
  dkd_param_hero_title text,
  dkd_param_hero_subtitle text,
  dkd_param_logic_title text,
  dkd_param_logic_body text
)
returns public.dkd_market_ui_config
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_row public.dkd_market_ui_config;
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  insert into public.dkd_market_ui_config (
    id,
    hero_kicker,
    hero_title,
    hero_subtitle,
    logic_title,
    logic_body,
    updated_at
  )
  values (
    1,
    coalesce(nullif(trim(dkd_param_hero_kicker), ''), 'TOKEN MAĞAZASI'),
    coalesce(nullif(trim(dkd_param_hero_title), ''), 'Anında al, anında kullan'),
    coalesce(nullif(trim(dkd_param_hero_subtitle), ''), 'Token cüzdanınla shard, boss bileti ve enerji satın al. Her paket ne işe yaradığını açık şekilde gösterir.'),
    coalesce(nullif(trim(dkd_param_logic_title), ''), 'Paket mantığı'),
    coalesce(nullif(trim(dkd_param_logic_body), ''), 'Shard = craft ve upgrade, Bilet = boss girişi, Enerji = daha fazla drop ve sandık akışı.'),
    now()
  )
  on conflict (id) do update
  set
    hero_kicker = excluded.hero_kicker,
    hero_title = excluded.hero_title,
    hero_subtitle = excluded.hero_subtitle,
    logic_title = excluded.logic_title,
    logic_body = excluded.logic_body,
    updated_at = now()
  returning * into dkd_row;

  return dkd_row;
end;
$$;

revoke all on function public.dkd_admin_market_ui_save(text, text, text, text, text) from public;
grant execute on function public.dkd_admin_market_ui_save(text, text, text, text, text) to authenticated;

create or replace function public.dkd_admin_market_shop_upsert(
  dkd_param_id bigint,
  dkd_param_pack_key text,
  dkd_param_title text,
  dkd_param_subtitle text,
  dkd_param_description text,
  dkd_param_badge_label text,
  dkd_param_icon_name text,
  dkd_param_accent_key text,
  dkd_param_price_token integer,
  dkd_param_reward_kind text,
  dkd_param_reward_amount integer,
  dkd_param_sort_order integer,
  dkd_param_is_active boolean
)
returns public.dkd_market_shop_defs
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_row public.dkd_market_shop_defs;
  dkd_reward_kind text;
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  dkd_reward_kind := lower(coalesce(trim(dkd_param_reward_kind), ''));
  if dkd_reward_kind not in ('shard', 'ticket', 'energy') then
    raise exception 'invalid_reward_kind';
  end if;

  if coalesce(nullif(trim(dkd_param_pack_key), ''), '') = '' then
    raise exception 'pack_key_required';
  end if;

  if coalesce(nullif(trim(dkd_param_title), ''), '') = '' then
    raise exception 'title_required';
  end if;

  if dkd_param_id is null then
    insert into public.dkd_market_shop_defs (
      pack_key,
      title,
      subtitle,
      description,
      badge_label,
      icon_name,
      accent_key,
      price_token,
      reward_kind,
      reward_amount,
      sort_order,
      is_active,
      updated_at
    )
    values (
      trim(dkd_param_pack_key),
      trim(dkd_param_title),
      nullif(trim(dkd_param_subtitle), ''),
      nullif(trim(dkd_param_description), ''),
      nullif(trim(dkd_param_badge_label), ''),
      coalesce(nullif(trim(dkd_param_icon_name), ''), 'cube-outline'),
      coalesce(nullif(trim(dkd_param_accent_key), ''), 'cyan'),
      greatest(coalesce(dkd_param_price_token, 0), 0),
      dkd_reward_kind,
      greatest(coalesce(dkd_param_reward_amount, 1), 1),
      coalesce(dkd_param_sort_order, 100),
      coalesce(dkd_param_is_active, true),
      now()
    )
    returning * into dkd_row;
  else
    update public.dkd_market_shop_defs
    set
      pack_key = trim(dkd_param_pack_key),
      title = trim(dkd_param_title),
      subtitle = nullif(trim(dkd_param_subtitle), ''),
      description = nullif(trim(dkd_param_description), ''),
      badge_label = nullif(trim(dkd_param_badge_label), ''),
      icon_name = coalesce(nullif(trim(dkd_param_icon_name), ''), 'cube-outline'),
      accent_key = coalesce(nullif(trim(dkd_param_accent_key), ''), 'cyan'),
      price_token = greatest(coalesce(dkd_param_price_token, 0), 0),
      reward_kind = dkd_reward_kind,
      reward_amount = greatest(coalesce(dkd_param_reward_amount, 1), 1),
      sort_order = coalesce(dkd_param_sort_order, 100),
      is_active = coalesce(dkd_param_is_active, true),
      updated_at = now()
    where id = dkd_param_id
    returning * into dkd_row;
  end if;

  return dkd_row;
end;
$$;

revoke all on function public.dkd_admin_market_shop_upsert(bigint, text, text, text, text, text, text, text, integer, text, integer, integer, boolean) from public;
grant execute on function public.dkd_admin_market_shop_upsert(bigint, text, text, text, text, text, text, text, integer, text, integer, integer, boolean) to authenticated;

create or replace function public.dkd_admin_market_shop_delete(dkd_param_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  delete from public.dkd_market_shop_defs
  where id = dkd_param_id;

  return jsonb_build_object('ok', true, 'id', dkd_param_id);
end;
$$;

revoke all on function public.dkd_admin_market_shop_delete(bigint) from public;
grant execute on function public.dkd_admin_market_shop_delete(bigint) to authenticated;

create or replace function public.dkd_market_token_shop_buy(dkd_param_kind text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid;
  dkd_pack public.dkd_market_shop_defs;
  dkd_token integer := 0;
  dkd_shards integer := 0;
  dkd_tickets integer := 0;
  dkd_energy integer := 0;
  dkd_energy_max integer := 20;
  dkd_energy_updated_at timestamptz := now();
  dkd_reward_shards integer := 0;
  dkd_reward_tickets integer := 0;
  dkd_reward_energy integer := 0;
begin
  dkd_user_id := auth.uid();
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  select *
  into dkd_pack
  from public.dkd_market_shop_defs
  where pack_key = lower(coalesce(trim(dkd_param_kind), ''))
    and is_active = true
  limit 1;

  if dkd_pack.id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_kind');
  end if;

  if dkd_pack.reward_kind = 'shard' then
    dkd_reward_shards := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
  elsif dkd_pack.reward_kind = 'ticket' then
    dkd_reward_tickets := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
  elsif dkd_pack.reward_kind = 'energy' then
    dkd_reward_energy := greatest(coalesce(dkd_pack.reward_amount, 0), 0);
  else
    return jsonb_build_object('ok', false, 'reason', 'invalid_reward_kind');
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id)
  on conflict (user_id) do nothing;

  select
    coalesce(token, 0),
    coalesce(shards, 0),
    coalesce(boss_tickets, 0),
    coalesce(energy, 0),
    greatest(1, coalesce(energy_max, 20)),
    coalesce(energy_updated_at, now())
  into
    dkd_token,
    dkd_shards,
    dkd_tickets,
    dkd_energy,
    dkd_energy_max,
    dkd_energy_updated_at
  from public.dkd_profiles
  where user_id = dkd_user_id
  for update;

  if dkd_token < coalesce(dkd_pack.price_token, 0) then
    return jsonb_build_object('ok', false, 'reason', 'not_enough_token');
  end if;

  if dkd_reward_energy > 0 and dkd_energy >= dkd_energy_max then
    return jsonb_build_object('ok', false, 'reason', 'energy_full');
  end if;

  update public.dkd_profiles
  set
    token = coalesce(token, 0) - coalesce(dkd_pack.price_token, 0),
    shards = coalesce(shards, 0) + dkd_reward_shards,
    boss_tickets = coalesce(boss_tickets, 0) + dkd_reward_tickets,
    energy = least(greatest(1, coalesce(energy_max, 20)), coalesce(energy, 0) + dkd_reward_energy),
    energy_updated_at = case
      when dkd_reward_energy > 0 then now()
      else coalesce(energy_updated_at, now())
    end,
    updated_at = now()
  where user_id = dkd_user_id
  returning
    coalesce(token, 0),
    coalesce(shards, 0),
    coalesce(boss_tickets, 0),
    coalesce(energy, 0),
    greatest(1, coalesce(energy_max, 20)),
    coalesce(energy_updated_at, now())
  into
    dkd_token,
    dkd_shards,
    dkd_tickets,
    dkd_energy,
    dkd_energy_max,
    dkd_energy_updated_at;

  return jsonb_build_object(
    'ok', true,
    'kind', dkd_pack.pack_key,
    'reward_kind', dkd_pack.reward_kind,
    'reward_amount', dkd_pack.reward_amount,
    'spent_token', dkd_pack.price_token,
    'reward_shards', dkd_reward_shards,
    'reward_tickets', dkd_reward_tickets,
    'reward_energy', dkd_reward_energy,
    'token', dkd_token,
    'shards', dkd_shards,
    'boss_tickets', dkd_tickets,
    'energy', dkd_energy,
    'energy_max', dkd_energy_max,
    'energy_updated_at', dkd_energy_updated_at
  );
end;
$$;

revoke all on function public.dkd_market_token_shop_buy(text) from public;
grant execute on function public.dkd_market_token_shop_buy(text) to authenticated;
