-- Lootonia DKD Courier live sync + weekly cleanup + urgent store total foundation
-- Tarih: 2026-04-26
-- Not: Supabase cron saatleri UTC çalışır. 20:59 UTC = Türkiye saatiyle Pazar 23:59.

begin;

-- DKD FIX: Mevcut RPC fonksiyonlarında eski default parametre varsa PostgreSQL CREATE OR REPLACE ile default kaldıramaz.
-- Bu yüzden önce sadece ilgili helper fonksiyonları düşürüp aynı SQL içinde temiz şekilde yeniden oluşturuyoruz.
drop function if exists public.dkd_urgent_courier_set_single_store_total_dkd(uuid, text, numeric);
drop function if exists public.dkd_urgent_courier_set_item_totals_dkd(uuid, jsonb);


create table if not exists public.dkd_courier_operation_cleanup_audit (
  dkd_id bigint generated by default as identity primary key,
  dkd_cleanup_started_at timestamptz not null default timezone('utc', now()),
  dkd_courier_jobs_closed_count integer not null default 0,
  dkd_cargo_shipments_closed_count integer not null default 0,
  dkd_urgent_orders_closed_count integer not null default 0,
  dkd_cleanup_note text null
);

alter table public.dkd_courier_operation_cleanup_audit enable row level security;

grant select, insert on public.dkd_courier_operation_cleanup_audit to service_role;

do $$
begin
  if to_regclass('public.dkd_urgent_courier_order_items') is not null then
    execute 'alter table public.dkd_urgent_courier_order_items add column if not exists dkd_product_total_tl numeric not null default 0';
    execute 'alter table public.dkd_urgent_courier_order_items replica identity full';
  end if;

  if to_regclass('public.dkd_urgent_courier_orders') is not null then
    execute 'alter table public.dkd_urgent_courier_orders replica identity full';
  end if;

  if to_regclass('public.dkd_urgent_courier_messages') is not null then
    execute 'alter table public.dkd_urgent_courier_messages replica identity full';
  end if;

  if to_regclass('public.dkd_courier_jobs') is not null then
    execute 'alter table public.dkd_courier_jobs replica identity full';
  end if;

  if to_regclass('public.dkd_cargo_shipments') is not null then
    execute 'alter table public.dkd_cargo_shipments replica identity full';
  end if;

  if to_regclass('public.dkd_business_product_orders') is not null then
    execute 'alter table public.dkd_business_product_orders replica identity full';
  end if;

  if to_regclass('public.dkd_business_order_status_history') is not null then
    execute 'alter table public.dkd_business_order_status_history replica identity full';
  end if;
end $$;

do $$
declare
  dkd_table_name_value text;
begin
  foreach dkd_table_name_value in array array[
    'dkd_courier_jobs',
    'dkd_cargo_shipments',
    'dkd_business_product_orders',
    'dkd_business_order_status_history',
    'dkd_urgent_courier_orders',
    'dkd_urgent_courier_order_items',
    'dkd_urgent_courier_messages'
  ] loop
    if to_regclass(format('public.%I', dkd_table_name_value)) is not null then
      begin
        execute format('alter publication supabase_realtime add table public.%I', dkd_table_name_value);
      exception
        when duplicate_object then null;
        when undefined_object then null;
        when insufficient_privilege then null;
      end;
    end if;
  end loop;
end $$;

create or replace function public.dkd_urgent_courier_set_item_totals_dkd(
  dkd_param_order_id uuid,
  dkd_param_item_totals jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_payload_value jsonb;
  dkd_item_id_value text;
  dkd_product_total_tl_value numeric;
  dkd_updated_count_value integer := 0;
  dkd_last_updated_count_value integer := 0;
  dkd_total_item_count_value integer := 0;
  dkd_ready_item_count_value integer := 0;
  dkd_all_product_total_tl_value numeric := 0;
  dkd_all_ready_value boolean := false;
begin
  if auth.uid() is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_auth_required');
  end if;

  if to_regclass('public.dkd_urgent_courier_orders') is null
     or to_regclass('public.dkd_urgent_courier_order_items') is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_urgent_tables_missing');
  end if;

  if dkd_param_order_id is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_order_id_required');
  end if;

  if jsonb_typeof(coalesce(dkd_param_item_totals, '[]'::jsonb)) <> 'array' then
    return jsonb_build_object('ok', false, 'reason', 'dkd_item_totals_array_required');
  end if;

  for dkd_payload_value in
    select dkd_payload_source_value
    from jsonb_array_elements(coalesce(dkd_param_item_totals, '[]'::jsonb)) as dkd_payload_source_table(dkd_payload_source_value)
  loop
    dkd_item_id_value := nullif(trim(coalesce(dkd_payload_value ->> 'dkd_item_id', dkd_payload_value ->> 'item_id', '')), '');
    dkd_product_total_tl_value := nullif(trim(coalesce(dkd_payload_value ->> 'dkd_product_total_tl', dkd_payload_value ->> 'product_total_tl', '0')), '')::numeric;

    if dkd_item_id_value is not null and coalesce(dkd_product_total_tl_value, 0) > 0 then
      begin
        execute '
          update public.dkd_urgent_courier_order_items
             set dkd_product_total_tl = $3,
                 dkd_updated_at = timezone(''utc'', now())
           where dkd_order_id = $1
             and dkd_item_id = $2
        ' using dkd_param_order_id, dkd_item_id_value, dkd_product_total_tl_value;
      exception
        when undefined_column then
          execute '
            update public.dkd_urgent_courier_order_items
               set dkd_product_total_tl = $3
             where dkd_order_id = $1
               and dkd_item_id = $2
          ' using dkd_param_order_id, dkd_item_id_value, dkd_product_total_tl_value;
      end;
      get diagnostics dkd_last_updated_count_value = row_count;
      dkd_updated_count_value := dkd_updated_count_value + dkd_last_updated_count_value;
    end if;
  end loop;

  execute '
    select count(*)::integer,
           count(*) filter (where coalesce(dkd_product_total_tl, 0) > 0)::integer,
           coalesce(sum(coalesce(dkd_product_total_tl, 0)), 0)::numeric
      from public.dkd_urgent_courier_order_items
     where dkd_order_id = $1
  ' into dkd_total_item_count_value, dkd_ready_item_count_value, dkd_all_product_total_tl_value
  using dkd_param_order_id;

  dkd_all_ready_value := dkd_total_item_count_value > 0 and dkd_total_item_count_value = dkd_ready_item_count_value;

  if dkd_all_ready_value then
    begin
      execute '
        update public.dkd_urgent_courier_orders
           set dkd_status_key = ''dkd_product_total_waiting'',
               dkd_product_total_tl = $2,
               dkd_updated_at = timezone(''utc'', now())
         where dkd_order_id = $1
      ' using dkd_param_order_id, dkd_all_product_total_tl_value;
    exception
      when undefined_column then
        begin
          execute '
            update public.dkd_urgent_courier_orders
               set dkd_status_key = ''dkd_product_total_waiting''
             where dkd_order_id = $1
          ' using dkd_param_order_id;
        exception
          when undefined_column then null;
        end;
    end;
  else
    begin
      execute '
        update public.dkd_urgent_courier_orders
           set dkd_product_total_tl = $2,
               dkd_updated_at = timezone(''utc'', now())
         where dkd_order_id = $1
      ' using dkd_param_order_id, dkd_all_product_total_tl_value;
    exception
      when undefined_column then null;
    end;
  end if;

  if to_regclass('public.dkd_urgent_courier_messages') is not null then
    begin
      execute '
        insert into public.dkd_urgent_courier_messages (
          dkd_order_id,
          dkd_sender_user_id,
          dkd_message_kind,
          dkd_message_text,
          dkd_created_at
        ) values ($1, auth.uid(), $2, $3, timezone(''utc'', now()))
      ' using
        dkd_param_order_id,
        case when dkd_all_ready_value then 'dkd_all_store_totals_ready' else 'dkd_single_store_total_ready' end,
        case when dkd_all_ready_value then 'Tüm mağaza ürün toplamları müşteriye gönderildi.' else 'Bir mağaza ürün toplamı müşteriye gönderildi.' end;
    exception
      when undefined_column then null;
      when undefined_table then null;
    end;
  end if;

  return jsonb_build_object(
    'ok', true,
    'dkd_updated_item_count', dkd_updated_count_value,
    'dkd_total_item_count', dkd_total_item_count_value,
    'dkd_ready_item_count', dkd_ready_item_count_value,
    'dkd_all_store_totals_ready', dkd_all_ready_value,
    'dkd_product_total_tl', dkd_all_product_total_tl_value
  );
end;
$$;

create or replace function public.dkd_urgent_courier_set_single_store_total_dkd(
  dkd_param_order_id uuid,
  dkd_param_item_id text,
  dkd_param_product_total_tl numeric
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select public.dkd_urgent_courier_set_item_totals_dkd(
    dkd_param_order_id,
    jsonb_build_array(jsonb_build_object(
      'dkd_item_id', dkd_param_item_id,
      'dkd_product_total_tl', dkd_param_product_total_tl
    ))
  );
$$;

create or replace function public.dkd_weekly_courier_operation_cleanup_dkd()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_courier_jobs_closed_count_value integer := 0;
  dkd_cargo_shipments_closed_count_value integer := 0;
  dkd_urgent_orders_closed_count_value integer := 0;
  dkd_completed_status_values text[] := array[
    'completed', 'cancelled', 'done', 'finished', 'closed', 'ended',
    'biten', 'tamamlandi', 'tamamlandı',
    'dkd_completed', 'dkd_cancelled', 'dkd_done', 'dkd_finished'
  ];
begin
  if to_regclass('public.dkd_courier_jobs') is not null then
    execute '
      update public.dkd_courier_jobs
         set is_active = false,
             updated_at = timezone(''utc'', now())
       where coalesce(is_active, true) = true
         and lower(coalesce(status, '''')) = any($1)
    ' using dkd_completed_status_values;
    get diagnostics dkd_courier_jobs_closed_count_value = row_count;
  end if;

  if to_regclass('public.dkd_cargo_shipments') is not null then
    execute '
      update public.dkd_cargo_shipments
         set status = case when lower(coalesce(status, '''')) = ''cancelled'' then status else ''archived_completed'' end,
             updated_at = timezone(''utc'', now())
       where lower(coalesce(status, '''')) = any($1)
    ' using dkd_completed_status_values;
    get diagnostics dkd_cargo_shipments_closed_count_value = row_count;
  end if;

  if to_regclass('public.dkd_urgent_courier_orders') is not null then
    execute '
      update public.dkd_urgent_courier_orders
         set dkd_status_key = case when lower(coalesce(dkd_status_key, '''')) = ''dkd_cancelled'' then dkd_status_key else ''dkd_archived_completed'' end,
             dkd_updated_at = timezone(''utc'', now())
       where lower(coalesce(dkd_status_key, '''')) = any($1)
    ' using dkd_completed_status_values;
    get diagnostics dkd_urgent_orders_closed_count_value = row_count;
  end if;

  insert into public.dkd_courier_operation_cleanup_audit (
    dkd_courier_jobs_closed_count,
    dkd_cargo_shipments_closed_count,
    dkd_urgent_orders_closed_count,
    dkd_cleanup_note
  ) values (
    dkd_courier_jobs_closed_count_value,
    dkd_cargo_shipments_closed_count_value,
    dkd_urgent_orders_closed_count_value,
    'Pazar 23:59 operasyon merkezi tamamlanan/biten sipariş temizliği'
  );

  return jsonb_build_object(
    'ok', true,
    'dkd_courier_jobs_closed_count', dkd_courier_jobs_closed_count_value,
    'dkd_cargo_shipments_closed_count', dkd_cargo_shipments_closed_count_value,
    'dkd_urgent_orders_closed_count', dkd_urgent_orders_closed_count_value
  );
end;
$$;

revoke all on function public.dkd_urgent_courier_set_item_totals_dkd(uuid, jsonb) from public;
revoke all on function public.dkd_urgent_courier_set_single_store_total_dkd(uuid, text, numeric) from public;
revoke all on function public.dkd_weekly_courier_operation_cleanup_dkd() from public;

grant execute on function public.dkd_urgent_courier_set_item_totals_dkd(uuid, jsonb) to authenticated, service_role;
grant execute on function public.dkd_urgent_courier_set_single_store_total_dkd(uuid, text, numeric) to authenticated, service_role;
grant execute on function public.dkd_weekly_courier_operation_cleanup_dkd() to service_role;

do $$
begin
  begin
    execute 'create extension if not exists pg_cron with schema extensions';
  exception
    when insufficient_privilege then null;
    when feature_not_supported then null;
    when undefined_file then null;
    when others then null;
  end;

  if to_regprocedure('cron.schedule(text,text,text)') is not null then
    begin
      if to_regprocedure('cron.unschedule(text)') is not null then
        execute 'select cron.unschedule($1)' using 'dkd_weekly_courier_operation_cleanup';
      end if;
    exception
      when others then null;
    end;

    execute 'select cron.schedule($1, $2, $3)'
      using
        'dkd_weekly_courier_operation_cleanup',
        '59 20 * * 0',
        'select public.dkd_weekly_courier_operation_cleanup_dkd();';
  end if;
end $$;

commit;
