begin;

create extension if not exists pgcrypto;

create table if not exists public.dkd_businesses (
  id uuid primary key default gen_random_uuid(),
  business_key text not null unique,
  name text not null,
  slug text not null unique,
  category text,
  address_text text,
  lat numeric(10,7),
  lng numeric(10,7),
  radius_m integer not null default 80 check (radius_m >= 20),
  is_active boolean not null default true,
  sponsor_enabled boolean not null default false,
  opens_at time,
  closes_at time,
  timezone_name text not null default 'Europe/Istanbul',
  stock_alert_threshold integer not null default 10 check (stock_alert_threshold >= 0),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dkd_business_memberships (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.dkd_businesses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role_key text not null default 'staff' check (role_key in ('owner', 'manager', 'staff', 'viewer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (business_id, user_id)
);

create table if not exists public.dkd_business_drop_links (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.dkd_businesses(id) on delete cascade,
  drop_id uuid not null references public.dkd_drops(id) on delete cascade,
  is_primary boolean not null default false,
  qr_label text,
  created_at timestamptz not null default now(),
  unique (business_id, drop_id),
  unique (drop_id)
);

create table if not exists public.dkd_business_campaigns (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.dkd_businesses(id) on delete cascade,
  campaign_key text not null unique,
  title text not null,
  subtitle text,
  task_key text,
  source_kind text not null default 'sponsor',
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  closes_at time,
  stock_total integer not null default 0 check (stock_total >= 0),
  stock_left integer not null default 0 check (stock_left >= 0),
  coupon_reward_label text,
  coupon_code_prefix text,
  is_active boolean not null default true,
  auto_close_on_stock_zero boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dkd_business_qr_scans (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.dkd_businesses(id) on delete cascade,
  drop_id uuid references public.dkd_drops(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  campaign_id bigint references public.dkd_business_campaigns(id) on delete set null,
  task_key text,
  source_kind text not null default 'drop',
  session_key text,
  scanned_at timestamptz not null default now(),
  local_day date generated always as ((scanned_at at time zone 'Europe/Istanbul')::date) stored,
  local_hour smallint generated always as (extract(hour from (scanned_at at time zone 'Europe/Istanbul'))::smallint) stored
);

create table if not exists public.dkd_business_coupon_uses (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.dkd_businesses(id) on delete cascade,
  campaign_id bigint references public.dkd_business_campaigns(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  coupon_code text,
  task_key text,
  status_key text not null default 'used' check (status_key in ('used', 'cancelled', 'reversed')),
  used_at timestamptz not null default now(),
  local_day date generated always as ((used_at at time zone 'Europe/Istanbul')::date) stored,
  local_hour smallint generated always as (extract(hour from (used_at at time zone 'Europe/Istanbul'))::smallint) stored
);

create index if not exists idx_dkd_business_memberships_business_user on public.dkd_business_memberships(business_id, user_id) where is_active = true;
create index if not exists idx_dkd_business_qr_scans_business_day on public.dkd_business_qr_scans(business_id, local_day desc);
create index if not exists idx_dkd_business_qr_scans_business_hour on public.dkd_business_qr_scans(business_id, local_day desc, local_hour asc);
create index if not exists idx_dkd_business_qr_scans_business_task on public.dkd_business_qr_scans(business_id, task_key, local_day desc);
create index if not exists idx_dkd_business_coupon_uses_business_day on public.dkd_business_coupon_uses(business_id, local_day desc);
create index if not exists idx_dkd_business_campaigns_business_active on public.dkd_business_campaigns(business_id, is_active, starts_at desc);

create or replace function public.dkd_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists dkd_touch_updated_at_businesses on public.dkd_businesses;
create trigger dkd_touch_updated_at_businesses
before update on public.dkd_businesses
for each row execute function public.dkd_touch_updated_at();

drop trigger if exists dkd_touch_updated_at_business_campaigns on public.dkd_business_campaigns;
create trigger dkd_touch_updated_at_business_campaigns
before update on public.dkd_business_campaigns
for each row execute function public.dkd_touch_updated_at();

create or replace function public.dkd_business_is_member(dkd_param_business_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.dkd_business_memberships dkd_membership
    where dkd_membership.business_id = dkd_param_business_id
      and dkd_membership.user_id = auth.uid()
      and dkd_membership.is_active = true
  );
$$;

revoke all on function public.dkd_business_is_member(uuid) from public;
grant execute on function public.dkd_business_is_member(uuid) to authenticated;

alter table public.dkd_businesses enable row level security;
alter table public.dkd_business_memberships enable row level security;
alter table public.dkd_business_drop_links enable row level security;
alter table public.dkd_business_campaigns enable row level security;
alter table public.dkd_business_qr_scans enable row level security;
alter table public.dkd_business_coupon_uses enable row level security;

drop policy if exists dkd_businesses_member_select on public.dkd_businesses;
create policy dkd_businesses_member_select
on public.dkd_businesses
for select
to authenticated
using (
  public.dkd_business_is_member(id)
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_business_memberships_member_select on public.dkd_business_memberships;
create policy dkd_business_memberships_member_select
on public.dkd_business_memberships
for select
to authenticated
using (
  user_id = auth.uid()
  or public.dkd_business_is_member(business_id)
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_business_drop_links_member_select on public.dkd_business_drop_links;
create policy dkd_business_drop_links_member_select
on public.dkd_business_drop_links
for select
to authenticated
using (
  public.dkd_business_is_member(business_id)
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_business_campaigns_member_select on public.dkd_business_campaigns;
create policy dkd_business_campaigns_member_select
on public.dkd_business_campaigns
for select
to authenticated
using (
  public.dkd_business_is_member(business_id)
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_business_qr_scans_member_select on public.dkd_business_qr_scans;
create policy dkd_business_qr_scans_member_select
on public.dkd_business_qr_scans
for select
to authenticated
using (
  public.dkd_business_is_member(business_id)
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_business_coupon_uses_member_select on public.dkd_business_coupon_uses;
create policy dkd_business_coupon_uses_member_select
on public.dkd_business_coupon_uses
for select
to authenticated
using (
  public.dkd_business_is_member(business_id)
  or coalesce(public.dkd_is_admin(), false)
);

create or replace function public.dkd_business_admin_upsert(
  dkd_param_id uuid,
  dkd_param_business_key text,
  dkd_param_name text,
  dkd_param_slug text,
  dkd_param_category text,
  dkd_param_address_text text,
  dkd_param_lat numeric,
  dkd_param_lng numeric,
  dkd_param_radius_m integer,
  dkd_param_is_active boolean,
  dkd_param_sponsor_enabled boolean,
  dkd_param_opens_at time,
  dkd_param_closes_at time,
  dkd_param_stock_alert_threshold integer
)
returns public.dkd_businesses
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_row public.dkd_businesses;
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  if coalesce(nullif(trim(dkd_param_business_key), ''), '') = '' then
    raise exception 'business_key_required';
  end if;

  if coalesce(nullif(trim(dkd_param_name), ''), '') = '' then
    raise exception 'name_required';
  end if;

  if coalesce(nullif(trim(dkd_param_slug), ''), '') = '' then
    raise exception 'slug_required';
  end if;

  if dkd_param_id is null then
    insert into public.dkd_businesses (
      business_key,
      name,
      slug,
      category,
      address_text,
      lat,
      lng,
      radius_m,
      is_active,
      sponsor_enabled,
      opens_at,
      closes_at,
      stock_alert_threshold,
      created_by
    )
    values (
      lower(trim(dkd_param_business_key)),
      trim(dkd_param_name),
      lower(trim(dkd_param_slug)),
      nullif(trim(dkd_param_category), ''),
      nullif(trim(dkd_param_address_text), ''),
      dkd_param_lat,
      dkd_param_lng,
      greatest(coalesce(dkd_param_radius_m, 80), 20),
      coalesce(dkd_param_is_active, true),
      coalesce(dkd_param_sponsor_enabled, false),
      dkd_param_opens_at,
      dkd_param_closes_at,
      greatest(coalesce(dkd_param_stock_alert_threshold, 10), 0),
      auth.uid()
    )
    returning * into dkd_row;
  else
    update public.dkd_businesses
    set
      business_key = lower(trim(dkd_param_business_key)),
      name = trim(dkd_param_name),
      slug = lower(trim(dkd_param_slug)),
      category = nullif(trim(dkd_param_category), ''),
      address_text = nullif(trim(dkd_param_address_text), ''),
      lat = dkd_param_lat,
      lng = dkd_param_lng,
      radius_m = greatest(coalesce(dkd_param_radius_m, 80), 20),
      is_active = coalesce(dkd_param_is_active, true),
      sponsor_enabled = coalesce(dkd_param_sponsor_enabled, false),
      opens_at = dkd_param_opens_at,
      closes_at = dkd_param_closes_at,
      stock_alert_threshold = greatest(coalesce(dkd_param_stock_alert_threshold, 10), 0),
      updated_at = now()
    where id = dkd_param_id
    returning * into dkd_row;
  end if;

  return dkd_row;
end;
$$;

revoke all on function public.dkd_business_admin_upsert(uuid, text, text, text, text, text, numeric, numeric, integer, boolean, boolean, time, time, integer) from public;
grant execute on function public.dkd_business_admin_upsert(uuid, text, text, text, text, text, numeric, numeric, integer, boolean, boolean, time, time, integer) to authenticated;

create or replace function public.dkd_business_link_drop(
  dkd_param_business_id uuid,
  dkd_param_drop_id uuid,
  dkd_param_is_primary boolean default true,
  dkd_param_qr_label text default null
)
returns public.dkd_business_drop_links
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_row public.dkd_business_drop_links;
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  insert into public.dkd_business_drop_links (
    business_id,
    drop_id,
    is_primary,
    qr_label
  )
  values (
    dkd_param_business_id,
    dkd_param_drop_id,
    coalesce(dkd_param_is_primary, true),
    nullif(trim(coalesce(dkd_param_qr_label, '')), '')
  )
  on conflict (drop_id) do update
  set
    business_id = excluded.business_id,
    is_primary = excluded.is_primary,
    qr_label = excluded.qr_label
  returning * into dkd_row;

  return dkd_row;
end;
$$;

revoke all on function public.dkd_business_link_drop(uuid, uuid, boolean, text) from public;
grant execute on function public.dkd_business_link_drop(uuid, uuid, boolean, text) to authenticated;

create or replace function public.dkd_business_campaign_upsert(
  dkd_param_id bigint,
  dkd_param_business_id uuid,
  dkd_param_campaign_key text,
  dkd_param_title text,
  dkd_param_subtitle text,
  dkd_param_task_key text,
  dkd_param_source_kind text,
  dkd_param_starts_at timestamptz,
  dkd_param_ends_at timestamptz,
  dkd_param_closes_at time,
  dkd_param_stock_total integer,
  dkd_param_stock_left integer,
  dkd_param_coupon_reward_label text,
  dkd_param_coupon_code_prefix text,
  dkd_param_is_active boolean,
  dkd_param_auto_close_on_stock_zero boolean
)
returns public.dkd_business_campaigns
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_row public.dkd_business_campaigns;
begin
  if not coalesce(public.dkd_is_admin(), false) then
    raise exception 'not_admin';
  end if;

  if coalesce(nullif(trim(dkd_param_campaign_key), ''), '') = '' then
    raise exception 'campaign_key_required';
  end if;

  if coalesce(nullif(trim(dkd_param_title), ''), '') = '' then
    raise exception 'title_required';
  end if;

  if dkd_param_id is null then
    insert into public.dkd_business_campaigns (
      business_id,
      campaign_key,
      title,
      subtitle,
      task_key,
      source_kind,
      starts_at,
      ends_at,
      closes_at,
      stock_total,
      stock_left,
      coupon_reward_label,
      coupon_code_prefix,
      is_active,
      auto_close_on_stock_zero
    )
    values (
      dkd_param_business_id,
      lower(trim(dkd_param_campaign_key)),
      trim(dkd_param_title),
      nullif(trim(coalesce(dkd_param_subtitle, '')), ''),
      nullif(trim(coalesce(dkd_param_task_key, '')), ''),
      coalesce(nullif(trim(coalesce(dkd_param_source_kind, '')), ''), 'sponsor'),
      coalesce(dkd_param_starts_at, now()),
      dkd_param_ends_at,
      dkd_param_closes_at,
      greatest(coalesce(dkd_param_stock_total, 0), 0),
      greatest(coalesce(dkd_param_stock_left, coalesce(dkd_param_stock_total, 0)), 0),
      nullif(trim(coalesce(dkd_param_coupon_reward_label, '')), ''),
      nullif(trim(coalesce(dkd_param_coupon_code_prefix, '')), ''),
      coalesce(dkd_param_is_active, true),
      coalesce(dkd_param_auto_close_on_stock_zero, true)
    )
    returning * into dkd_row;
  else
    update public.dkd_business_campaigns
    set
      business_id = dkd_param_business_id,
      campaign_key = lower(trim(dkd_param_campaign_key)),
      title = trim(dkd_param_title),
      subtitle = nullif(trim(coalesce(dkd_param_subtitle, '')), ''),
      task_key = nullif(trim(coalesce(dkd_param_task_key, '')), ''),
      source_kind = coalesce(nullif(trim(coalesce(dkd_param_source_kind, '')), ''), 'sponsor'),
      starts_at = coalesce(dkd_param_starts_at, starts_at),
      ends_at = dkd_param_ends_at,
      closes_at = dkd_param_closes_at,
      stock_total = greatest(coalesce(dkd_param_stock_total, 0), 0),
      stock_left = greatest(coalesce(dkd_param_stock_left, 0), 0),
      coupon_reward_label = nullif(trim(coalesce(dkd_param_coupon_reward_label, '')), ''),
      coupon_code_prefix = nullif(trim(coalesce(dkd_param_coupon_code_prefix, '')), ''),
      is_active = coalesce(dkd_param_is_active, true),
      auto_close_on_stock_zero = coalesce(dkd_param_auto_close_on_stock_zero, true),
      updated_at = now()
    where id = dkd_param_id
    returning * into dkd_row;
  end if;

  return dkd_row;
end;
$$;

revoke all on function public.dkd_business_campaign_upsert(bigint, uuid, text, text, text, text, text, timestamptz, timestamptz, time, integer, integer, text, text, boolean, boolean) from public;
grant execute on function public.dkd_business_campaign_upsert(bigint, uuid, text, text, text, text, text, timestamptz, timestamptz, time, integer, integer, text, text, boolean, boolean) to authenticated;

create or replace function public.dkd_business_qr_scan_log(
  dkd_param_business_id uuid,
  dkd_param_drop_id uuid default null,
  dkd_param_campaign_id bigint default null,
  dkd_param_task_key text default null,
  dkd_param_source_kind text default 'drop',
  dkd_param_session_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_scan_id bigint;
begin
  insert into public.dkd_business_qr_scans (
    business_id,
    drop_id,
    user_id,
    campaign_id,
    task_key,
    source_kind,
    session_key
  )
  values (
    dkd_param_business_id,
    dkd_param_drop_id,
    auth.uid(),
    dkd_param_campaign_id,
    nullif(trim(coalesce(dkd_param_task_key, '')), ''),
    coalesce(nullif(trim(coalesce(dkd_param_source_kind, '')), ''), 'drop'),
    nullif(trim(coalesce(dkd_param_session_key, '')), '')
  )
  returning id into dkd_scan_id;

  return jsonb_build_object(
    'ok', true,
    'scan_id', dkd_scan_id
  );
end;
$$;

revoke all on function public.dkd_business_qr_scan_log(uuid, uuid, bigint, text, text, text) from public;
grant execute on function public.dkd_business_qr_scan_log(uuid, uuid, bigint, text, text, text) to authenticated;

create or replace function public.dkd_business_coupon_use_log(
  dkd_param_business_id uuid,
  dkd_param_campaign_id bigint default null,
  dkd_param_coupon_code text default null,
  dkd_param_task_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_row_id bigint;
begin
  insert into public.dkd_business_coupon_uses (
    business_id,
    campaign_id,
    user_id,
    coupon_code,
    task_key,
    status_key
  )
  values (
    dkd_param_business_id,
    dkd_param_campaign_id,
    auth.uid(),
    nullif(trim(coalesce(dkd_param_coupon_code, '')), ''),
    nullif(trim(coalesce(dkd_param_task_key, '')), ''),
    'used'
  )
  returning id into dkd_row_id;

  if dkd_param_campaign_id is not null then
    update public.dkd_business_campaigns
    set
      stock_left = greatest(coalesce(stock_left, 0) - 1, 0),
      is_active = case
        when auto_close_on_stock_zero = true and greatest(coalesce(stock_left, 0) - 1, 0) = 0 then false
        else is_active
      end,
      updated_at = now()
    where id = dkd_param_campaign_id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'coupon_use_id', dkd_row_id
  );
end;
$$;

revoke all on function public.dkd_business_coupon_use_log(uuid, bigint, text, text) from public;
grant execute on function public.dkd_business_coupon_use_log(uuid, bigint, text, text) to authenticated;

create or replace view public.dkd_business_today_metrics as
with dkd_business_day as (
  select
    dkd_business.id as business_id,
    (now() at time zone coalesce(dkd_business.timezone_name, 'Europe/Istanbul'))::date as local_day
  from public.dkd_businesses dkd_business
),
dkd_scan_agg as (
  select
    dkd_scan.business_id,
    dkd_scan.local_day,
    count(*) as qr_scan_count,
    count(distinct dkd_scan.user_id) as unique_today_players,
    max(dkd_scan.scanned_at) as last_scan_at
  from public.dkd_business_qr_scans dkd_scan
  group by dkd_scan.business_id, dkd_scan.local_day
),
dkd_coupon_agg as (
  select
    dkd_coupon.business_id,
    dkd_coupon.local_day,
    count(*) as coupon_use_count
  from public.dkd_business_coupon_uses dkd_coupon
  group by dkd_coupon.business_id, dkd_coupon.local_day
)
select
  dkd_day.business_id,
  dkd_day.local_day,
  coalesce(dkd_scan_agg.qr_scan_count, 0) as qr_scan_count,
  coalesce(dkd_scan_agg.unique_today_players, 0) as unique_player_count,
  coalesce(dkd_scan_agg.unique_today_players, 0) as unique_today_players,
  coalesce(dkd_coupon_agg.coupon_use_count, 0) as coupon_use_count,
  dkd_scan_agg.last_scan_at
from dkd_business_day dkd_day
left join dkd_scan_agg
  on dkd_scan_agg.business_id = dkd_day.business_id
 and dkd_scan_agg.local_day = dkd_day.local_day
left join dkd_coupon_agg
  on dkd_coupon_agg.business_id = dkd_day.business_id
 and dkd_coupon_agg.local_day = dkd_day.local_day;

create or replace view public.dkd_business_hourly_heatmap as
select
  dkd_scan.business_id,
  dkd_scan.local_day,
  dkd_scan.local_hour,
  count(*) as qr_scan_count,
  count(distinct dkd_scan.user_id) as unique_player_count
from public.dkd_business_qr_scans dkd_scan
group by dkd_scan.business_id, dkd_scan.local_day, dkd_scan.local_hour;

create or replace view public.dkd_business_task_attribution as
select
  dkd_scan.business_id,
  dkd_scan.local_day,
  coalesce(nullif(dkd_scan.task_key, ''), 'organic') as task_key,
  coalesce(nullif(dkd_scan.source_kind, ''), 'drop') as source_kind,
  count(*) as qr_scan_count,
  count(distinct dkd_scan.user_id) as unique_player_count
from public.dkd_business_qr_scans dkd_scan
group by
  dkd_scan.business_id,
  dkd_scan.local_day,
  coalesce(nullif(dkd_scan.task_key, ''), 'organic'),
  coalesce(nullif(dkd_scan.source_kind, ''), 'drop');

create or replace function public.dkd_business_dashboard_snapshot(
  dkd_param_business_id uuid,
  dkd_param_limit_days integer default 7
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_is_allowed boolean;
  dkd_today jsonb;
  dkd_hours jsonb;
  dkd_tasks jsonb;
  dkd_campaigns jsonb;
begin
  dkd_is_allowed := public.dkd_business_is_member(dkd_param_business_id) or coalesce(public.dkd_is_admin(), false);
  if not coalesce(dkd_is_allowed, false) then
    raise exception 'not_business_member';
  end if;

  select to_jsonb(dkd_row)
  into dkd_today
  from (
    select
      dkd_metric.business_id,
      dkd_metric.local_day,
      coalesce(dkd_metric.unique_today_players, 0) as today_player_count,
      coalesce(dkd_metric.qr_scan_count, 0) as today_qr_scan_count,
      coalesce(dkd_metric.coupon_use_count, 0) as today_coupon_use_count,
      coalesce(round((coalesce(dkd_metric.coupon_use_count, 0)::numeric / nullif(coalesce(dkd_metric.qr_scan_count, 0), 0)) * 100, 2), 0) as coupon_conversion_rate,
      dkd_metric.last_scan_at
    from public.dkd_business_today_metrics dkd_metric
    where dkd_metric.business_id = dkd_param_business_id
  ) as dkd_row;

  select coalesce(jsonb_agg(to_jsonb(dkd_row) order by dkd_row.local_day desc, dkd_row.local_hour asc), '[]'::jsonb)
  into dkd_hours
  from (
    select
      business_id,
      local_day,
      local_hour,
      qr_scan_count,
      unique_player_count
    from public.dkd_business_hourly_heatmap
    where business_id = dkd_param_business_id
      and local_day >= ((now() at time zone 'Europe/Istanbul')::date - greatest(coalesce(dkd_param_limit_days, 7), 1) + 1)
    order by local_day desc, local_hour asc
  ) as dkd_row;

  select coalesce(jsonb_agg(to_jsonb(dkd_row) order by dkd_row.local_day desc, dkd_row.qr_scan_count desc, dkd_row.task_key asc), '[]'::jsonb)
  into dkd_tasks
  from (
    select
      business_id,
      local_day,
      task_key,
      source_kind,
      qr_scan_count,
      unique_player_count
    from public.dkd_business_task_attribution
    where business_id = dkd_param_business_id
      and local_day >= ((now() at time zone 'Europe/Istanbul')::date - greatest(coalesce(dkd_param_limit_days, 7), 1) + 1)
    order by local_day desc, qr_scan_count desc, task_key asc
  ) as dkd_row;

  select coalesce(jsonb_agg(to_jsonb(dkd_row) order by dkd_row.is_active desc, dkd_row.starts_at desc, dkd_row.id desc), '[]'::jsonb)
  into dkd_campaigns
  from (
    select
      id,
      campaign_key,
      title,
      subtitle,
      task_key,
      source_kind,
      starts_at,
      ends_at,
      closes_at,
      stock_total,
      stock_left,
      coupon_reward_label,
      is_active,
      auto_close_on_stock_zero
    from public.dkd_business_campaigns
    where business_id = dkd_param_business_id
    order by is_active desc, starts_at desc, id desc
  ) as dkd_row;

  return jsonb_build_object(
    'today', coalesce(dkd_today, '{}'::jsonb),
    'hours', coalesce(dkd_hours, '[]'::jsonb),
    'tasks', coalesce(dkd_tasks, '[]'::jsonb),
    'campaigns', coalesce(dkd_campaigns, '[]'::jsonb)
  );
end;
$$;

revoke all on function public.dkd_business_dashboard_snapshot(uuid, integer) from public;
grant execute on function public.dkd_business_dashboard_snapshot(uuid, integer) to authenticated;

commit;
