begin;

alter table if exists public.dkd_profiles
  add column if not exists wallet_tl numeric(12,2) not null default 0,
  add column if not exists courier_city text not null default 'Ankara',
  add column if not exists courier_zone text not null default '',
  add column if not exists courier_vehicle_type text not null default 'moto',
  add column if not exists courier_profile_meta jsonb not null default '{}'::jsonb;

create table if not exists public.dkd_courier_license_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  city text not null default 'Ankara',
  zone text not null default '',
  vehicle_type text not null default 'moto',
  first_name text,
  last_name text,
  national_id text,
  phone text,
  email text,
  plate_no text,
  address_text text,
  emergency_name text,
  emergency_phone text,
  identity_front_url text,
  identity_back_url text,
  selfie_url text,
  driver_license_url text,
  vehicle_license_url text,
  insurance_url text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists dkd_courier_license_applications_user_idx
  on public.dkd_courier_license_applications(user_id);

alter table public.dkd_courier_license_applications enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_courier_license_applications'
      and policyname = 'dkd_courier_license_applications_select_own'
  ) then
    create policy dkd_courier_license_applications_select_own
      on public.dkd_courier_license_applications
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_courier_license_applications'
      and policyname = 'dkd_courier_license_applications_insert_own'
  ) then
    create policy dkd_courier_license_applications_insert_own
      on public.dkd_courier_license_applications
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dkd_courier_license_applications'
      and policyname = 'dkd_courier_license_applications_update_own'
  ) then
    create policy dkd_courier_license_applications_update_own
      on public.dkd_courier_license_applications
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  select 'lootonia-courier-docs', 'lootonia-courier-docs', true, 8388608, array['image/jpeg','image/png','image/webp','image/heic']
  where not exists (select 1 from storage.buckets where id = 'lootonia-courier-docs');
exception
  when undefined_table then
    null;
end $$;

do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'storage' and table_name = 'objects') then
    if not exists (
      select 1 from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and policyname = 'lootonia_courier_docs_read'
    ) then
      create policy lootonia_courier_docs_read
        on storage.objects
        for select
        to authenticated
        using (bucket_id = 'lootonia-courier-docs');
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and policyname = 'lootonia_courier_docs_insert'
    ) then
      create policy lootonia_courier_docs_insert
        on storage.objects
        for insert
        to authenticated
        with check (bucket_id = 'lootonia-courier-docs');
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and policyname = 'lootonia_courier_docs_update'
    ) then
      create policy lootonia_courier_docs_update
        on storage.objects
        for update
        to authenticated
        using (bucket_id = 'lootonia-courier-docs')
        with check (bucket_id = 'lootonia-courier-docs');
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and policyname = 'lootonia_courier_docs_delete'
    ) then
      create policy lootonia_courier_docs_delete
        on storage.objects
        for delete
        to authenticated
        using (bucket_id = 'lootonia-courier-docs');
    end if;
  end if;
end $$;

create or replace function public.dkd_apply_courier_license()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
begin
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id)
  on conflict (user_id) do nothing;

  update public.dkd_profiles
  set
    courier_status = case
      when coalesce(courier_status, 'none') = 'approved' then 'approved'
      else 'pending'
    end,
    updated_at = now()
  where user_id = dkd_user_id;

  insert into public.dkd_courier_license_applications (user_id, status)
  values (
    dkd_user_id,
    case
      when (select courier_status from public.dkd_profiles where user_id = dkd_user_id) = 'approved' then 'approved'
      else 'pending'
    end
  )
  on conflict (user_id) do update
    set status = excluded.status,
        updated_at = now();

  return (select courier_status from public.dkd_profiles where user_id = dkd_user_id limit 1);
end;
$$;

revoke all on function public.dkd_apply_courier_license() from public;
grant execute on function public.dkd_apply_courier_license() to authenticated;

drop function if exists public.dkd_courier_job_complete(bigint);
create function public.dkd_courier_job_complete(dkd_param_job_id bigint)
returns table (
  courier_score integer,
  courier_completed_jobs integer,
  token integer,
  wallet_tl numeric,
  courier_wallet_tl numeric,
  courier_total_earned_tl numeric,
  courier_withdrawn_tl numeric,
  courier_active_days integer,
  courier_last_completed_at timestamptz,
  courier_fastest_eta_min integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_user_id uuid := auth.uid();
  dkd_reward_score integer := 0;
  dkd_status text := 'open';
  dkd_assigned_user_id uuid;
  dkd_token_reward integer := 0;
  dkd_fee_tl numeric(12,2) := 0;
  dkd_eta_min integer := 0;
  dkd_last_completed_at timestamptz;
  dkd_is_new_active_day boolean := false;
begin
  if dkd_user_id is null then
    raise exception 'auth_required';
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id)
  on conflict (user_id) do nothing;

  select
    coalesce(j.reward_score, 0),
    coalesce(j.status, 'open'),
    j.assigned_user_id,
    coalesce(j.fee_tl, 0)::numeric(12,2),
    coalesce(j.eta_min, 0)
  into
    dkd_reward_score,
    dkd_status,
    dkd_assigned_user_id,
    dkd_fee_tl,
    dkd_eta_min
  from public.dkd_courier_jobs j
  where j.id = dkd_param_job_id
    and coalesce(j.is_active, true) = true
  for update;

  if dkd_assigned_user_id is null then
    raise exception 'job_not_found';
  end if;

  if dkd_assigned_user_id <> dkd_user_id then
    raise exception 'job_not_owned';
  end if;

  if dkd_status = 'completed' then
    return query
    select
      coalesce(dkd_alias_p.courier_score, 0),
      coalesce(dkd_alias_p.courier_completed_jobs, 0),
      coalesce(dkd_alias_p.token, 0),
      coalesce(dkd_alias_p.wallet_tl, coalesce(dkd_alias_p.courier_wallet_tl, 0))::numeric(12,2),
      coalesce(dkd_alias_p.courier_wallet_tl, 0)::numeric(12,2),
      coalesce(dkd_alias_p.courier_total_earned_tl, 0)::numeric(12,2),
      coalesce(dkd_alias_p.courier_withdrawn_tl, 0)::numeric(12,2),
      coalesce(dkd_alias_p.courier_active_days, 0),
      dkd_alias_p.courier_last_completed_at,
      dkd_alias_p.courier_fastest_eta_min
    from public.dkd_profiles dkd_alias_p
    where dkd_alias_p.user_id = dkd_user_id
    limit 1;
    return;
  end if;

  if dkd_status <> 'accepted' then
    raise exception 'job_not_accepted';
  end if;

  dkd_token_reward := greatest(dkd_reward_score * 4, 10);

  select dkd_alias_p.courier_last_completed_at
  into dkd_last_completed_at
  from public.dkd_profiles dkd_alias_p
  where dkd_alias_p.user_id = dkd_user_id
  for update;

  dkd_is_new_active_day := dkd_last_completed_at is null or (dkd_last_completed_at at time zone 'utc')::date <> (now() at time zone 'utc')::date;

  update public.dkd_courier_jobs
  set
    status = 'completed',
    completed_at = now(),
    updated_at = now()
  where id = dkd_param_job_id;

  update public.dkd_profiles
  set
    courier_score = coalesce(courier_score, 0) + dkd_reward_score,
    courier_completed_jobs = coalesce(courier_completed_jobs, 0) + 1,
    token = coalesce(token, 0) + dkd_token_reward,
    wallet_tl = coalesce(wallet_tl, 0) + dkd_fee_tl,
    courier_wallet_tl = coalesce(courier_wallet_tl, 0) + dkd_fee_tl,
    courier_total_earned_tl = coalesce(courier_total_earned_tl, 0) + dkd_fee_tl,
    courier_active_days = coalesce(courier_active_days, 0) + case when dkd_is_new_active_day then 1 else 0 end,
    courier_last_completed_at = now(),
    courier_fastest_eta_min = case
      when dkd_eta_min <= 0 then courier_fastest_eta_min
      when courier_fastest_eta_min is null then dkd_eta_min
      else least(courier_fastest_eta_min, dkd_eta_min)
    end,
    updated_at = now()
  where user_id = dkd_user_id;

  insert into public.dkd_courier_wallet_ledger (
    user_id,
    job_id,
    order_id,
    direction,
    source_type,
    amount_tl,
    balance_after_tl,
    note,
    meta
  )
  select
    dkd_user_id,
    j.id,
    j.order_id,
    'credit',
    'delivery_fee',
    dkd_fee_tl,
    coalesce(dkd_alias_p.wallet_tl, coalesce(dkd_alias_p.courier_wallet_tl, 0))::numeric(12,2),
    concat(coalesce(j.merchant_name, 'İşletme'), ' teslimat ücreti'),
    jsonb_build_object(
      'merchant_name', j.merchant_name,
      'product_title', j.product_title,
      'reward_score', dkd_reward_score,
      'token_reward', dkd_token_reward
    )
  from public.dkd_courier_jobs j
  join public.dkd_profiles dkd_alias_p on dkd_alias_p.user_id = dkd_user_id
  where j.id = dkd_param_job_id;

  return query
  select
    coalesce(dkd_alias_p.courier_score, 0),
    coalesce(dkd_alias_p.courier_completed_jobs, 0),
    coalesce(dkd_alias_p.token, 0),
    coalesce(dkd_alias_p.wallet_tl, coalesce(dkd_alias_p.courier_wallet_tl, 0))::numeric(12,2),
    coalesce(dkd_alias_p.courier_wallet_tl, 0)::numeric(12,2),
    coalesce(dkd_alias_p.courier_total_earned_tl, 0)::numeric(12,2),
    coalesce(dkd_alias_p.courier_withdrawn_tl, 0)::numeric(12,2),
    coalesce(dkd_alias_p.courier_active_days, 0),
    dkd_alias_p.courier_last_completed_at,
    dkd_alias_p.courier_fastest_eta_min
  from public.dkd_profiles dkd_alias_p
  where dkd_alias_p.user_id = dkd_user_id
  limit 1;
end;
$$;

revoke all on function public.dkd_courier_job_complete(bigint) from public;
grant execute on function public.dkd_courier_job_complete(bigint) to authenticated;

commit;
